// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module ConfigMem_12(
  input         clock,
                reset,
                io_cfg_en,
  input  [1:0]  io_cfg_addr,
  input  [31:0] io_cfg_data,
  output [64:0] io_out_0
);

  reg [64:0] regs_0;	// @[ConfigMem.scala:27:21]
  always @(posedge clock) begin
    if (reset)
      regs_0 <= 65'h0;	// @[ConfigMem.scala:27:{21,29}]
    else if (io_cfg_en & io_cfg_addr == 2'h2)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {io_cfg_data[0], regs_0[63:0]};	// @[ConfigMem.scala:27:21, :43:{19,46}]
    else if (io_cfg_en & io_cfg_addr == 2'h1)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[64], io_cfg_data, regs_0[31:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 2'h0)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[64:32], io_cfg_data};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :41:33]
  end // always @(posedge)
  assign io_out_0 = regs_0;	// @[ConfigMem.scala:27:21]
endmodule

