// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module fpDiv(
  input         clock,
                reset,
  input  [31:0] io_in1,
                io_in2,
  output [31:0] io_out
);

  wire [23:0] _inverter_io_out;	// @[fpDiv.scala:23:32]
  reg  [31:0] in1Reg0;	// @[fpDiv.scala:28:30]
  reg  [31:0] in1Reg1;	// @[fpDiv.scala:30:30]
  reg  [31:0] in1Reg2;	// @[fpDiv.scala:31:30]
  reg  [31:0] in1Reg3;	// @[fpDiv.scala:32:30]
  reg  [7:0]  in2ExpReg0;	// @[fpDiv.scala:36:33]
  reg         in2SignReg0;	// @[fpDiv.scala:38:34]
  reg  [7:0]  in2ExpReg1;	// @[fpDiv.scala:40:34]
  reg         in2SignReg1;	// @[fpDiv.scala:41:34]
  reg  [7:0]  in2ExpReg2;	// @[fpDiv.scala:42:34]
  reg         in2SignReg2;	// @[fpDiv.scala:43:34]
  reg  [7:0]  in2ExpReg3;	// @[fpDiv.scala:44:34]
  reg         in2SignReg3;	// @[fpDiv.scala:45:34]
  reg  [23:0] invMant;	// @[fpDiv.scala:46:33]
  wire [7:0]  negExpTmp = 8'hFE - in2ExpReg3;	// @[fpDiv.scala:44:34, :50:35]
  always @(posedge clock) begin
    if (reset) begin
      in1Reg0 <= 32'h0;	// @[fpDiv.scala:28:30]
      in2ExpReg0 <= 8'h0;	// @[fpDiv.scala:36:33]
      in2SignReg0 <= 1'h0;	// @[fpDiv.scala:30:30, :38:34]
      invMant <= 24'h0;	// @[fpDiv.scala:46:33]
    end
    else begin
      in1Reg0 <= io_in1;	// @[fpDiv.scala:28:30]
      in2ExpReg0 <= io_in2[30:23];	// @[fpDiv.scala:36:33, :37:29]
      in2SignReg0 <= io_in2[31];	// @[fpDiv.scala:38:34, :39:30]
      invMant <= _inverter_io_out;	// @[fpDiv.scala:23:32, :46:33]
    end
    in1Reg1 <= in1Reg0;	// @[fpDiv.scala:28:30, :30:30]
    in1Reg2 <= in1Reg1;	// @[fpDiv.scala:30:30, :31:30]
    in1Reg3 <= in1Reg2;	// @[fpDiv.scala:31:30, :32:30]
    in2ExpReg1 <= in2ExpReg0;	// @[fpDiv.scala:36:33, :40:34]
    in2SignReg1 <= in2SignReg0;	// @[fpDiv.scala:38:34, :41:34]
    in2ExpReg2 <= in2ExpReg1;	// @[fpDiv.scala:40:34, :42:34]
    in2SignReg2 <= in2SignReg1;	// @[fpDiv.scala:41:34, :43:34]
    in2ExpReg3 <= in2ExpReg2;	// @[fpDiv.scala:42:34, :44:34]
    in2SignReg3 <= in2SignReg2;	// @[fpDiv.scala:43:34, :45:34]
  end // always @(posedge)
  fpInverter inverter (	// @[fpDiv.scala:23:32]
    .clock  (clock),
    .io_in1 (io_in2[22:0]),	// @[fpDiv.scala:26:34]
    .io_out (_inverter_io_out)
  );
  FPMult multiplier (	// @[fpDiv.scala:24:32]
    .clock  (clock),
    .io_a   (in1Reg3),	// @[fpDiv.scala:32:30]
    .io_b   ({in2SignReg3, invMant == 24'h0 ? negExpTmp : negExpTmp - 8'h1, invMant[23:1]}),	// @[Cat.scala:33:92, fpDiv.scala:45:34, :46:33, :50:35, :51:{32,41,71}, :56:60]
    .io_res (io_out)
  );
endmodule

