// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module GPE_10(
  input         clock,
                reset,
                io_cfg_en,
  input  [13:0] io_cfg_addr,
  input  [31:0] io_cfg_data,
  input         io_en,
  input  [31:0] io_in_cg_0,
                io_in_cg_1,
                io_in_cg_2,
                io_in_cg_3,
                io_in_cg_4,
                io_in_cg_5,
                io_in_cg_6,
                io_in_cg_7,
  output [31:0] io_out_cg_0
);

  wire [57:0] _cfg_io_out_0;	// @[PE.scala:480:19]
  wire [31:0] _Muxn_1_io_out;	// @[PE.scala:155:46]
  wire [31:0] _Muxn_io_out;	// @[PE.scala:155:46]
  wire [31:0] _delayPipeCG_io_out_0;	// @[PE.scala:145:27]
  wire [31:0] _delayPipeCG_io_out_1;	// @[PE.scala:145:27]
  wire [31:0] _alu_io_out_0;	// @[PE.scala:140:19]
  ALU_6 alu (	// @[PE.scala:140:19]
    .clock     (clock),
    .reset     (reset),
    .io_config (_cfg_io_out_0[38:32]),	// @[PE.scala:480:19, :504:28]
    .io_in_1   (_delayPipeCG_io_out_1),	// @[PE.scala:145:27]
    .io_in_0   (_delayPipeCG_io_out_0),	// @[PE.scala:145:27]
    .io_out_0  (_alu_io_out_0)
  );
  DualModeReg dmr (	// @[PE.scala:144:19]
    .clock    (clock),
    .io_in_0  (_alu_io_out_0),	// @[PE.scala:140:19]
    .io_out_0 (io_out_cg_0)
  );
  SharedDelayPipe_24 delayPipeCG (	// @[PE.scala:145:27]
    .clock     (clock),
    .reset     (reset),
    .io_en     (io_en),
    .io_config (_cfg_io_out_0[51:42]),	// @[PE.scala:480:19, :519:36]
    .io_in_0   (_Muxn_io_out),	// @[PE.scala:155:46]
    .io_in_1   (_Muxn_1_io_out),	// @[PE.scala:155:46]
    .io_out_0  (_delayPipeCG_io_out_0),
    .io_out_1  (_delayPipeCG_io_out_1)
  );
  Muxn_36 Muxn (	// @[PE.scala:155:46]
    .io_config (_cfg_io_out_0[54:52]),	// @[PE.scala:480:19, :527:34]
    .io_in_0   (_cfg_io_out_0[31:0]),	// @[PE.scala:480:19, :496:18]
    .io_in_1   (io_in_cg_0),
    .io_in_2   (io_in_cg_1),
    .io_in_3   (io_in_cg_2),
    .io_in_4   (io_in_cg_3),
    .io_out    (_Muxn_io_out)
  );
  Muxn_36 Muxn_1 (	// @[PE.scala:155:46]
    .io_config (_cfg_io_out_0[57:55]),	// @[PE.scala:480:19, :527:34]
    .io_in_0   (_cfg_io_out_0[31:0]),	// @[PE.scala:480:19, :496:18]
    .io_in_1   (io_in_cg_4),
    .io_in_2   (io_in_cg_5),
    .io_in_3   (io_in_cg_6),
    .io_in_4   (io_in_cg_7),
    .io_out    (_Muxn_1_io_out)
  );
  ConfigMem_18 cfg (	// @[PE.scala:480:19]
    .clock       (clock),
    .reset       (reset),
    .io_cfg_en   (io_cfg_en & io_cfg_addr[13:6] == 8'h2F),	// @[PE.scala:481:{30,48,63}]
    .io_cfg_addr (io_cfg_addr[0]),	// @[PE.scala:482:{19,33}]
    .io_cfg_data (io_cfg_data),
    .io_out_0    (_cfg_io_out_0)
  );
endmodule

