// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module lookupL(
  input         clock,
  input  [5:0]  io_addr,
  output [26:0] io_out
);

  reg  [26:0]       data;	// @[lookups.scala:86:31]
  wire [63:0][26:0] _GEN = '{27'h4081020, 27'h4104104, 27'h4189374, 27'h4210842, 27'h429A042, 27'h4325C53, 27'h43B3D5A, 27'h4444444, 27'h44D7204, 27'h456C797, 27'h4604604, 27'h469EE58, 27'h473C1AB, 27'h47DC11F, 27'h487EDE0, 27'h4924924, 27'h49CD42E, 27'h4A7904A, 27'h4B27ED3, 27'h4BDA12F, 27'h4C8F8D2, 27'h4D4873E, 27'h4E04E04, 27'h4EC4EC4, 27'h4F88B2F, 27'h5050505, 27'h511BE19, 27'h51EB851, 27'h52BF5A8, 27'h5397829, 27'h54741FA, 27'h5555555, 27'h563B48C, 27'h572620A, 27'h5816058, 27'h590B216, 27'h5A05A05, 27'h5B05B05, 27'h5C0B817, 27'h5D1745D, 27'h5E29320, 27'h5F417D0, 27'h6060606, 27'h6186186, 27'h62B2E43, 27'h63E7063, 27'h6522C3F, 27'h6666666, 27'h67B23A5, 27'h6906906, 27'h6A63BD8, 27'h6BCA1AF, 27'h6D3A06D, 27'h6EB3E45, 27'h70381C0, 27'h71C71C7, 27'h73615A2, 27'h7507507, 27'h76B981D, 27'h7878787, 27'h7A44C6A, 27'h7C1F07C, 27'h7E07E07, 27'h0};	// @[lookups.scala:86:31]
  always @(posedge clock)
    data <= _GEN[io_addr];	// @[lookups.scala:86:31]
  assign io_out = data;	// @[lookups.scala:86:31]
endmodule

