// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module Queue_69(
  input         clock,
                reset,
                io_enq_valid,
  input  [6:0]  io_enq_bits_inst_funct,
  input  [4:0]  io_enq_bits_inst_rs2,
                io_enq_bits_inst_rs1,
  input         io_enq_bits_inst_xd,
                io_enq_bits_inst_xs1,
                io_enq_bits_inst_xs2,
  input  [4:0]  io_enq_bits_inst_rd,
  input  [6:0]  io_enq_bits_inst_opcode,
  input  [63:0] io_enq_bits_rs1,
                io_enq_bits_rs2,
  input         io_enq_bits_status_debug,
                io_enq_bits_status_cease,
                io_enq_bits_status_wfi,
  input  [31:0] io_enq_bits_status_isa,
  input  [1:0]  io_enq_bits_status_dprv,
  input         io_enq_bits_status_dv,
  input  [1:0]  io_enq_bits_status_prv,
  input         io_enq_bits_status_v,
                io_enq_bits_status_sd,
  input  [22:0] io_enq_bits_status_zero2,
  input         io_enq_bits_status_mpv,
                io_enq_bits_status_gva,
                io_enq_bits_status_mbe,
                io_enq_bits_status_sbe,
  input  [1:0]  io_enq_bits_status_sxl,
                io_enq_bits_status_uxl,
  input         io_enq_bits_status_sd_rv32,
  input  [7:0]  io_enq_bits_status_zero1,
  input         io_enq_bits_status_tsr,
                io_enq_bits_status_tw,
                io_enq_bits_status_tvm,
                io_enq_bits_status_mxr,
                io_enq_bits_status_sum,
                io_enq_bits_status_mprv,
  input  [1:0]  io_enq_bits_status_xs,
                io_enq_bits_status_fs,
                io_enq_bits_status_mpp,
                io_enq_bits_status_vs,
  input         io_enq_bits_status_spp,
                io_enq_bits_status_mpie,
                io_enq_bits_status_ube,
                io_enq_bits_status_spie,
                io_enq_bits_status_upie,
                io_enq_bits_status_mie,
                io_enq_bits_status_hie,
                io_enq_bits_status_sie,
                io_enq_bits_status_uie,
                io_deq_ready,
  output        io_enq_ready,
                io_deq_valid,
  output [63:0] io_deq_bits_rs1,
                io_deq_bits_rs2,
  output [1:0]  io_deq_bits_status_prv
);

  wire [264:0] _ram_ext_R0_data;	// @[Decoupled.scala:273:95]
  reg  [2:0]   enq_ptr_value;	// @[Counter.scala:61:40]
  reg  [2:0]   deq_ptr_value;	// @[Counter.scala:61:40]
  reg          maybe_full;	// @[Decoupled.scala:276:27]
  wire         ptr_match = enq_ptr_value == deq_ptr_value;	// @[Counter.scala:61:40, Decoupled.scala:277:33]
  wire         empty = ptr_match & ~maybe_full;	// @[Decoupled.scala:276:27, :277:33, :278:{25,28}]
  wire         full = ptr_match & maybe_full;	// @[Decoupled.scala:276:27, :277:33, :279:24]
  wire         do_enq = ~full & io_enq_valid;	// @[Decoupled.scala:51:35, :279:24, :303:19]
  wire         do_deq = io_deq_ready & ~empty;	// @[Decoupled.scala:51:35, :278:25, :302:19]
  always @(posedge clock) begin
    if (reset) begin
      enq_ptr_value <= 3'h0;	// @[Counter.scala:61:40]
      deq_ptr_value <= 3'h0;	// @[Counter.scala:61:40]
      maybe_full <= 1'h0;	// @[Decoupled.scala:276:27]
    end
    else begin
      if (do_enq)	// @[Decoupled.scala:51:35]
        enq_ptr_value <= enq_ptr_value + 3'h1;	// @[Counter.scala:61:40, :77:24]
      if (do_deq)	// @[Decoupled.scala:51:35]
        deq_ptr_value <= deq_ptr_value + 3'h1;	// @[Counter.scala:61:40, :77:24]
      if (do_enq != do_deq)	// @[Decoupled.scala:51:35, :293:15]
        maybe_full <= do_enq;	// @[Decoupled.scala:51:35, :276:27]
    end
  end // always @(posedge)
  ram_combMem_45 ram_ext (	// @[Decoupled.scala:273:95]
    .R0_addr (deq_ptr_value),	// @[Counter.scala:61:40]
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .W0_addr (enq_ptr_value),	// @[Counter.scala:61:40]
    .W0_en   (do_enq),	// @[Decoupled.scala:51:35]
    .W0_clk  (clock),
    .W0_data ({io_enq_bits_status_uie, io_enq_bits_status_sie, io_enq_bits_status_hie, io_enq_bits_status_mie, io_enq_bits_status_upie, io_enq_bits_status_spie, io_enq_bits_status_ube, io_enq_bits_status_mpie, io_enq_bits_status_spp, io_enq_bits_status_vs, io_enq_bits_status_mpp, io_enq_bits_status_fs, io_enq_bits_status_xs, io_enq_bits_status_mprv, io_enq_bits_status_sum, io_enq_bits_status_mxr, io_enq_bits_status_tvm, io_enq_bits_status_tw, io_enq_bits_status_tsr, io_enq_bits_status_zero1, io_enq_bits_status_sd_rv32, io_enq_bits_status_uxl, io_enq_bits_status_sxl, io_enq_bits_status_sbe, io_enq_bits_status_mbe, io_enq_bits_status_gva, io_enq_bits_status_mpv, io_enq_bits_status_zero2, io_enq_bits_status_sd, io_enq_bits_status_v, io_enq_bits_status_prv, io_enq_bits_status_dv, io_enq_bits_status_dprv, io_enq_bits_status_isa, io_enq_bits_status_wfi, io_enq_bits_status_cease, io_enq_bits_status_debug, io_enq_bits_rs2, io_enq_bits_rs1, io_enq_bits_inst_opcode, io_enq_bits_inst_rd, io_enq_bits_inst_xs2, io_enq_bits_inst_xs1, io_enq_bits_inst_xd, io_enq_bits_inst_rs1, io_enq_bits_inst_rs2, io_enq_bits_inst_funct}),	// @[Decoupled.scala:273:95]
    .R0_data (_ram_ext_R0_data)
  );
  assign io_enq_ready = ~full;	// @[Decoupled.scala:279:24, :303:19]
  assign io_deq_valid = ~empty;	// @[Decoupled.scala:278:25, :302:19]
  assign io_deq_bits_rs1 = _ram_ext_R0_data[95:32];	// @[Decoupled.scala:273:95]
  assign io_deq_bits_rs2 = _ram_ext_R0_data[159:96];	// @[Decoupled.scala:273:95]
  assign io_deq_bits_status_prv = _ram_ext_R0_data[199:198];	// @[Decoupled.scala:273:95]
endmodule

