// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module RRArbiter(
  input         clock,
                io_in_0_valid,
  input  [39:0] io_in_0_bits_vaddr,
  input  [2:0]  io_in_0_bits_size,
  input  [1:0]  io_in_0_bits_status_prv,
  input         io_in_1_valid,
  input  [39:0] io_in_1_bits_vaddr,
  input  [2:0]  io_in_1_bits_size,
  input  [1:0]  io_in_1_bits_status_prv,
  input         io_out_ready,
  output        io_in_0_ready,
                io_in_1_ready,
                io_out_valid,
  output [39:0] io_out_bits_vaddr,
  output [2:0]  io_out_bits_size,
  output [4:0]  io_out_bits_cmd,
  output [1:0]  io_out_bits_status_prv
);

  wire choice;	// @[Arbiter.scala:91:26, :93:{24,33}]
  wire _io_out_valid_output = choice ? io_in_1_valid : io_in_0_valid;	// @[Arbiter.scala:55:16, :91:26, :93:{24,33}]
  reg  lastGrant;	// @[Reg.scala:19:16]
  wire validMask_1 = io_in_1_valid & ~lastGrant;	// @[Arbiter.scala:81:49, :82:76, Reg.scala:19:16]
  assign choice = validMask_1 | ~io_in_0_valid;	// @[Arbiter.scala:82:76, :89:41, :91:{26,35}, :93:{24,33}]
  always @(posedge clock) begin
    if (io_out_ready & _io_out_valid_output)	// @[Arbiter.scala:55:16, Decoupled.scala:51:35]
      lastGrant <= choice;	// @[Arbiter.scala:91:26, :93:{24,33}, Reg.scala:19:16]
  end // always @(posedge)
  assign io_in_0_ready = ~validMask_1 & io_out_ready;	// @[Arbiter.scala:45:78, :74:21, :82:76]
  assign io_in_1_ready = (~lastGrant | ~(validMask_1 | io_in_0_valid)) & io_out_ready;	// @[Arbiter.scala:45:{68,78}, :74:21, :81:49, :82:76, :86:50, Reg.scala:19:16]
  assign io_out_valid = _io_out_valid_output;	// @[Arbiter.scala:55:16]
  assign io_out_bits_vaddr = choice ? io_in_1_bits_vaddr : io_in_0_bits_vaddr;	// @[Arbiter.scala:55:16, :91:26, :93:{24,33}]
  assign io_out_bits_size = choice ? io_in_1_bits_size : io_in_0_bits_size;	// @[Arbiter.scala:55:16, :91:26, :93:{24,33}]
  assign io_out_bits_cmd = {4'h0, choice};	// @[Arbiter.scala:55:16, :91:26, :93:{24,33}]
  assign io_out_bits_status_prv = choice ? io_in_1_bits_status_prv : io_in_0_bits_status_prv;	// @[Arbiter.scala:55:16, :91:26, :93:{24,33}]
endmodule

