// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module SharedDelayPipe_25(
  input        clock,
               reset,
               io_en,
  input  [3:0] io_config,
  input        io_in_0,
  output       io_out_0
);

  reg        regs_0;	// @[DelayPipe.scala:80:25]
  reg        regs_1;	// @[DelayPipe.scala:80:25]
  reg        regs_2;	// @[DelayPipe.scala:80:25]
  reg        regs_3;	// @[DelayPipe.scala:80:25]
  reg        regs_4;	// @[DelayPipe.scala:80:25]
  reg        regs_5;	// @[DelayPipe.scala:80:25]
  reg        regs_6;	// @[DelayPipe.scala:80:25]
  reg        regs_7;	// @[DelayPipe.scala:80:25]
  reg        regs_8;	// @[DelayPipe.scala:80:25]
  reg  [3:0] wptr_0;	// @[DelayPipe.scala:81:25]
  reg  [3:0] rptr_0;	// @[DelayPipe.scala:82:25]
  wire [4:0] _rptr_0_diff_T_1 = {1'h0, wptr_0} - {1'h0, io_config};	// @[DelayPipe.scala:81:25, :104:19, :105:14]
  wire       _T = wptr_0 < 4'h9;	// @[DelayPipe.scala:81:25, :103:62, :127:22]
  always @(posedge clock) begin
    if (reset) begin
      regs_0 <= 1'h0;	// @[DelayPipe.scala:80:25, :105:14]
      regs_1 <= 1'h0;	// @[DelayPipe.scala:80:25, :105:14]
      regs_2 <= 1'h0;	// @[DelayPipe.scala:80:25, :105:14]
      regs_3 <= 1'h0;	// @[DelayPipe.scala:80:25, :105:14]
      regs_4 <= 1'h0;	// @[DelayPipe.scala:80:25, :105:14]
      regs_5 <= 1'h0;	// @[DelayPipe.scala:80:25, :105:14]
      regs_6 <= 1'h0;	// @[DelayPipe.scala:80:25, :105:14]
      regs_7 <= 1'h0;	// @[DelayPipe.scala:80:25, :105:14]
      regs_8 <= 1'h0;	// @[DelayPipe.scala:80:25, :105:14]
      wptr_0 <= 4'h0;	// @[DelayPipe.scala:81:{25,33}]
      rptr_0 <= 4'h0;	// @[DelayPipe.scala:81:33, :82:25]
    end
    else begin
      regs_0 <= io_en & (_T & wptr_0 == 4'h0 ? io_in_0 : regs_0);	// @[DelayPipe.scala:80:25, :81:{25,33}, :125:16, :127:{22,34,51}, :130:41]
      regs_1 <= io_en & (_T & wptr_0 == 4'h1 ? io_in_0 : regs_1);	// @[DelayPipe.scala:80:25, :81:25, :125:16, :127:{22,34,51}, :130:41]
      regs_2 <= io_en & (_T & wptr_0 == 4'h2 ? io_in_0 : regs_2);	// @[DelayPipe.scala:80:25, :81:25, :125:16, :127:{22,34,51}, :130:41]
      regs_3 <= io_en & (_T & wptr_0 == 4'h3 ? io_in_0 : regs_3);	// @[DelayPipe.scala:80:25, :81:25, :125:16, :127:{22,34,51}, :130:41]
      regs_4 <= io_en & (_T & wptr_0 == 4'h4 ? io_in_0 : regs_4);	// @[DelayPipe.scala:80:25, :81:25, :125:16, :127:{22,34,51}, :130:41]
      regs_5 <= io_en & (_T & wptr_0 == 4'h5 ? io_in_0 : regs_5);	// @[DelayPipe.scala:80:25, :81:25, :125:16, :127:{22,34,51}, :130:41]
      regs_6 <= io_en & (_T & wptr_0 == 4'h6 ? io_in_0 : regs_6);	// @[DelayPipe.scala:80:25, :81:25, :125:16, :127:{22,34,51}, :130:41]
      regs_7 <= io_en & (_T & wptr_0 == 4'h7 ? io_in_0 : regs_7);	// @[DelayPipe.scala:80:25, :81:25, :125:16, :127:{22,34,51}, :130:41]
      regs_8 <= io_en & (_T & wptr_0 == 4'h8 ? io_in_0 : regs_8);	// @[DelayPipe.scala:80:25, :81:25, :101:13, :125:16, :127:{22,34,51}, :130:41]
      if (~io_en | wptr_0 == 4'h8)	// @[DelayPipe.scala:81:25, :101:13, :112:18, :114:15, :118:15]
        wptr_0 <= 4'h0;	// @[DelayPipe.scala:81:{25,33}]
      else	// @[DelayPipe.scala:112:18, :114:15, :118:15]
        wptr_0 <= wptr_0 + 4'h1;	// @[DelayPipe.scala:81:25, :101:37, :127:51]
      if (io_en) begin
        if (rptr_0 == 4'h8)	// @[DelayPipe.scala:82:25, :101:13]
          rptr_0 <= 4'h0;	// @[DelayPipe.scala:81:33, :82:25]
        else	// @[DelayPipe.scala:101:13]
          rptr_0 <= rptr_0 + 4'h1;	// @[DelayPipe.scala:82:25, :101:37, :127:51]
      end
      else
        rptr_0 <= $signed(_rptr_0_diff_T_1) > -5'sh1 ? _rptr_0_diff_T_1[3:0] : _rptr_0_diff_T_1[3:0] - 4'h7;	// @[DelayPipe.scala:82:25, :104:19, :105:{8,14,39}]
    end
  end // always @(posedge)
  assign io_out_0 = io_en & (io_config == 4'h0 ? io_in_0 : rptr_0 == 4'h0 & regs_0 | rptr_0 == 4'h1 & regs_1 | rptr_0 == 4'h2 & regs_2 | rptr_0 == 4'h3 & regs_3 | rptr_0 == 4'h4 & regs_4 | rptr_0 == 4'h5 & regs_5 | rptr_0 == 4'h6 & regs_6 | rptr_0 == 4'h7 & regs_7 | rptr_0 == 4'h8 & regs_8);	// @[DelayPipe.scala:80:25, :81:33, :82:25, :101:13, :127:51, :136:{10,19}, :137:16, :138:{21,32,40}]
endmodule

