// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module ConfigController(
  input          clock,
                 reset,
                 io_start,
  input  [7:0]   io_base_addr,
  input  [13:0]  io_cfg_num,
  input  [127:0] io_sram_dout,
  output         io_done,
                 io_sram_en,
  output [7:0]   io_sram_addr,
  output         io_cfg_en,
  output [13:0]  io_cfg_addr,
  output [31:0]  io_cfg_data
);

  reg  [1:0]   state;	// @[ConfigController.scala:35:22]
  reg  [13:0]  cnt;	// @[ConfigController.scala:36:20]
  reg  [383:0] dataReg;	// @[ConfigController.scala:38:24]
  reg  [8:0]   wOffset;	// @[ConfigController.scala:39:24]
  reg  [8:0]   availOffset;	// @[ConfigController.scala:40:28]
  wire         _T_1 = state == 2'h1;	// @[ConfigController.scala:35:22, :41:73]
  wire         sramRen = availOffset < 9'h101 & _T_1;	// @[ConfigController.scala:40:28, :41:{30,63,73}]
  reg          wen;	// @[Reg.scala:19:16]
  wire         ren = wOffset > 9'h2F & cnt < io_cfg_num;	// @[ConfigController.scala:36:20, :39:24, :43:{22,37,45}]
  reg  [4:0]   waitCnt;	// @[ConfigController.scala:44:24]
  reg          done;	// @[ConfigController.scala:45:21]
  reg  [7:0]   addrSram;	// @[ConfigController.scala:106:25]
  wire [894:0] _GEN = {886'h0, 9'h180 - wOffset};	// @[ConfigController.scala:39:24, :95:{26,41}, :99:{26,41}]
  wire         _GEN_0 = state == 2'h2 & waitCnt > 5'h14;	// @[ConfigController.scala:35:22, :44:24, :48:16, :57:15, :61:{20,35}, :62:15]
  wire [894:0] _GEN_1 = {511'h0, dataReg};	// @[ConfigController.scala:38:24, :95:26]
  wire [638:0] _GEN_2 = {511'h0, io_sram_dout};	// @[ConfigController.scala:95:26, :96:31]
  wire [638:0] _dataReg_T_10 = _GEN_2 << wOffset - 9'h30;	// @[ConfigController.scala:39:24, :96:{31,43}]
  wire [894:0] _dataReg_T_7 = _GEN_1 << 9'h180 - wOffset >> 9'h1B0 - wOffset;	// @[ConfigController.scala:39:24, :95:{26,41,53,81}]
  wire [638:0] _dataReg_T_18 = _GEN_2 << wOffset;	// @[ConfigController.scala:39:24, :96:31, :100:21]
  wire [894:0] _dataReg_T_17 = _GEN_1 << _GEN >> _GEN;	// @[ConfigController.scala:95:26, :99:{26,53}]
  always @(posedge clock) begin
    if (reset) begin
      state <= 2'h0;	// @[ConfigController.scala:35:22]
      cnt <= 14'h0;	// @[ConfigController.scala:36:20]
      dataReg <= 384'h0;	// @[ConfigController.scala:38:24]
      wOffset <= 9'h0;	// @[ConfigController.scala:39:24]
      availOffset <= 9'h0;	// @[ConfigController.scala:39:24, :40:28]
      waitCnt <= 5'h0;	// @[ConfigController.scala:44:24]
      done <= 1'h0;	// @[ConfigController.scala:45:21, Reg.scala:19:16]
      addrSram <= 8'h0;	// @[ConfigController.scala:106:25]
    end
    else if (state == 2'h0) begin	// @[ConfigController.scala:35:22, :48:16]
      if (io_start)
        state <= 2'h1;	// @[ConfigController.scala:35:22, :41:73]
      cnt <= 14'h0;	// @[ConfigController.scala:36:20]
      dataReg <= 384'h0;	// @[ConfigController.scala:38:24]
      wOffset <= 9'h0;	// @[ConfigController.scala:39:24]
      availOffset <= 9'h0;	// @[ConfigController.scala:39:24, :40:28]
      waitCnt <= 5'h0;	// @[ConfigController.scala:44:24]
      done <= ~io_start & done;	// @[ConfigController.scala:45:21, :50:21, :52:14]
      addrSram <= io_base_addr;	// @[ConfigController.scala:106:25]
    end
    else begin	// @[ConfigController.scala:48:16]
      if (_T_1) begin	// @[ConfigController.scala:41:73]
        if (cnt >= io_cfg_num)	// @[ConfigController.scala:36:20, :56:16]
          state <= 2'h2;	// @[ConfigController.scala:35:22, :57:15]
      end
      else if (_GEN_0)	// @[ConfigController.scala:35:22, :48:16, :61:35, :62:15]
        state <= 2'h0;	// @[ConfigController.scala:35:22]
      if (ren)	// @[ConfigController.scala:43:37]
        cnt <= cnt + 14'h1;	// @[ConfigController.scala:36:20, :71:16]
      if (wen & ren) begin	// @[ConfigController.scala:43:37, :93:18, Reg.scala:19:16]
        dataReg <= _dataReg_T_7[383:0] | _dataReg_T_10[383:0];	// @[ConfigController.scala:38:24, :95:{53,100}, :96:31]
        wOffset <= wOffset + 9'h50;	// @[ConfigController.scala:39:24, :83:50, :94:42]
      end
      else if (wen) begin	// @[Reg.scala:19:16]
        dataReg <= _dataReg_T_17[383:0] | _dataReg_T_18[383:0];	// @[ConfigController.scala:38:24, :99:{53,87}, :100:21]
        wOffset <= wOffset + 9'h80;	// @[ConfigController.scala:39:24, :83:32, :98:24]
      end
      else if (ren) begin	// @[ConfigController.scala:43:37]
        dataReg <= {48'h0, dataReg[383:48]};	// @[ConfigController.scala:38:24, :43:22, :103:25]
        wOffset <= wOffset - 9'h30;	// @[ConfigController.scala:39:24, :102:24]
      end
      if (sramRen & ren)	// @[ConfigController.scala:41:63, :43:37, :82:22]
        availOffset <= availOffset + 9'h50;	// @[ConfigController.scala:40:28, :83:50]
      else if (sramRen)	// @[ConfigController.scala:41:63]
        availOffset <= availOffset + 9'h80;	// @[ConfigController.scala:40:28, :83:32, :85:32]
      else if (ren)	// @[ConfigController.scala:43:37]
        availOffset <= availOffset - 9'h30;	// @[ConfigController.scala:40:28, :87:32]
      if (state == 2'h2)	// @[ConfigController.scala:35:22, :57:15, :76:20]
        waitCnt <= waitCnt + 5'h1;	// @[ConfigController.scala:44:24, :77:24]
      done <= ~_T_1 & _GEN_0 | done;	// @[ConfigController.scala:35:22, :41:73, :45:21, :48:16, :61:35, :62:15]
      if (sramRen)	// @[ConfigController.scala:41:63]
        addrSram <= addrSram + 8'h1;	// @[ConfigController.scala:106:25, :110:26]
    end
    wen <= sramRen;	// @[ConfigController.scala:41:63, Reg.scala:19:16]
  end // always @(posedge)
  assign io_done = done;	// @[ConfigController.scala:45:21]
  assign io_sram_en = sramRen;	// @[ConfigController.scala:41:63]
  assign io_sram_addr = addrSram;	// @[ConfigController.scala:106:25]
  assign io_cfg_en = ren;	// @[ConfigController.scala:43:37]
  assign io_cfg_addr = dataReg[45:32];	// @[ConfigController.scala:38:24, :117:{15,25}]
  assign io_cfg_data = dataReg[31:0];	// @[ConfigController.scala:38:24, :118:25]
endmodule

