// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module ConfigMem_84(
  input         clock,
                reset,
                io_cfg_en,
  input  [31:0] io_cfg_data,
  output [25:0] io_out_0
);

  reg [25:0] regs_0;	// @[ConfigMem.scala:27:21]
  always @(posedge clock) begin
    if (reset)
      regs_0 <= 26'h0;	// @[ConfigMem.scala:27:{21,29}]
    else if (io_cfg_en)
      regs_0 <= io_cfg_data[25:0];	// @[ConfigMem.scala:27:21, :33:31]
  end // always @(posedge)
  assign io_out_0 = regs_0;	// @[ConfigMem.scala:27:21]
endmodule

