// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module DualModeReg_6(
  input         clock,
                reset,
                io_start,
  input  [2:0]  io_mode,
  input  [78:0] io_config,
  input  [31:0] io_in_0,
                io_in_1,
  output [31:0] io_out_0,
                io_out_1
);

  CtrlReg acr (	// @[DMR.scala:318:21]
    .clock     (clock),
    .reset     (reset),
    .io_start  (io_start),
    .io_mode   (io_mode),
    .io_config (io_config),
    .io_in_0   (io_in_0),
    .io_in_1   (io_in_1),
    .io_out_0  (io_out_0),
    .io_out_1  (io_out_1)
  );
endmodule

