// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module fpInverter(
  input         clock,
  input  [22:0] io_in1,
  output [23:0] io_out
);

  wire [24:0] _adder_io_out;	// @[fpInverter.scala:72:31]
  wire [26:0] _sub2_io_out;	// @[fpInverter.scala:63:30]
  wire [28:0] _mul2_io_out;	// @[fpInverter.scala:37:26]
  wire [23:0] _mul1_io_out;	// @[fpInverter.scala:32:26]
  wire [22:0] _tableJ_io_out;	// @[fpInverter.scala:21:28]
  wire [26:0] _tableL_io_out;	// @[fpInverter.scala:20:28]
  wire [23:0] _tableC_io_out;	// @[fpInverter.scala:19:28]
  wire [33:0] _GEN = {17'h0, io_in1[16:0]};	// @[fpInverter.scala:34:30, :39:42]
  wire [33:0] _mul2_io_in2_T_2 = _GEN * _GEN;	// @[fpInverter.scala:39:42]
  reg  [22:0] w_sub1_reg;	// @[fpInverter.scala:43:33]
  reg  [23:0] w_mul1_reg;	// @[fpInverter.scala:44:33]
  reg  [28:0] w_mul2_reg;	// @[fpInverter.scala:45:33]
  reg  [26:0] tableL_out_reg;	// @[fpInverter.scala:55:37]
  reg  [22:0] sub1_out_reg1;	// @[fpInverter.scala:57:37]
  reg  [23:0] mul1_out_reg;	// @[fpInverter.scala:58:37]
  reg  [28:0] mul2_out_reg;	// @[fpInverter.scala:59:37]
  reg  [22:0] sub1_out_reg2;	// @[fpInverter.scala:80:36]
  reg  [24:0] adder_out_reg;	// @[fpInverter.scala:81:36]
  always @(posedge clock) begin
    w_sub1_reg <= ~io_in1 + 23'h1;	// @[fpInverter.scala:30:{28,60}, :43:33]
    w_mul1_reg <= _mul1_io_out;	// @[fpInverter.scala:32:26, :44:33]
    w_mul2_reg <= _mul2_io_out;	// @[fpInverter.scala:37:26, :45:33]
    tableL_out_reg <= _tableL_io_out;	// @[fpInverter.scala:20:28, :55:37]
    sub1_out_reg1 <= w_sub1_reg;	// @[fpInverter.scala:43:33, :57:37]
    mul1_out_reg <= w_mul1_reg;	// @[fpInverter.scala:44:33, :58:37]
    mul2_out_reg <= w_mul2_reg;	// @[fpInverter.scala:45:33, :59:37]
    sub1_out_reg2 <= sub1_out_reg1;	// @[fpInverter.scala:57:37, :80:36]
    adder_out_reg <= _adder_io_out;	// @[fpInverter.scala:72:31, :81:36]
  end // always @(posedge)
  lookupC tableC (	// @[fpInverter.scala:19:28]
    .io_addr (io_in1[22:17]),	// @[fpInverter.scala:25:33]
    .io_out  (_tableC_io_out)
  );
  lookupL tableL (	// @[fpInverter.scala:20:28]
    .clock   (clock),
    .io_addr (io_in1[22:17]),	// @[fpInverter.scala:25:33]
    .io_out  (_tableL_io_out)
  );
  lookupJ tableJ (	// @[fpInverter.scala:21:28]
    .io_addr (io_in1[22:17]),	// @[fpInverter.scala:25:33]
    .io_out  (_tableJ_io_out)
  );
  VarSizeMul mul1 (	// @[fpInverter.scala:32:26]
    .io_in1 (_tableJ_io_out),	// @[fpInverter.scala:21:28]
    .io_in2 (io_in1[16:0]),	// @[fpInverter.scala:34:30]
    .io_out (_mul1_io_out)
  );
  mul2 mul2 (	// @[fpInverter.scala:37:26]
    .io_in1 (_tableC_io_out),	// @[fpInverter.scala:19:28]
    .io_in2 (_mul2_io_in2_T_2[33:17]),	// @[fpInverter.scala:39:{42,61}]
    .io_out (_mul2_io_out)
  );
  VarSizeSub sub2 (	// @[fpInverter.scala:63:30]
    .io_in1 (tableL_out_reg),	// @[fpInverter.scala:55:37]
    .io_in2 ({~mul1_out_reg + 24'h1, 3'h0}),	// @[Cat.scala:33:92, fpInverter.scala:58:37, :64:{38,71}]
    .io_out (_sub2_io_out)
  );
  VarSizeAdder adder (	// @[fpInverter.scala:72:31]
    .io_in1 ({_sub2_io_out, 2'h0}),	// @[Cat.scala:33:92, fpInverter.scala:63:30]
    .io_in2 (mul2_out_reg),	// @[fpInverter.scala:59:37]
    .io_out (_adder_io_out)
  );
  mul3 mul3 (	// @[fpInverter.scala:83:30]
    .io_in1 (sub1_out_reg2),	// @[fpInverter.scala:80:36]
    .io_in2 (adder_out_reg),	// @[fpInverter.scala:81:36]
    .io_out (io_out)
  );
endmodule

