// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module FPUFMAPipe(
  input         clock,
                reset,
                io_in_valid,
                io_in_bits_ren3,
                io_in_bits_swap23,
  input  [2:0]  io_in_bits_rm,
  input  [1:0]  io_in_bits_fmaCmd,
  input  [64:0] io_in_bits_in1,
                io_in_bits_in2,
                io_in_bits_in3,
  output [64:0] io_out_bits_data,
  output [4:0]  io_out_bits_exc
);

  wire [32:0] _fma_io_out;	// @[FPU.scala:710:19]
  reg         valid;	// @[FPU.scala:698:22]
  reg  [2:0]  in_rm;	// @[FPU.scala:699:15]
  reg  [1:0]  in_fmaCmd;	// @[FPU.scala:699:15]
  reg  [64:0] in_in1;	// @[FPU.scala:699:15]
  reg  [64:0] in_in2;	// @[FPU.scala:699:15]
  reg  [64:0] in_in3;	// @[FPU.scala:699:15]
  always @(posedge clock) begin
    valid <= io_in_valid;	// @[FPU.scala:698:22]
    if (io_in_valid) begin
      in_rm <= io_in_bits_rm;	// @[FPU.scala:699:15]
      in_fmaCmd <= io_in_bits_fmaCmd;	// @[FPU.scala:699:15]
      in_in1 <= io_in_bits_in1;	// @[FPU.scala:699:15]
      if (io_in_bits_swap23)
        in_in2 <= 65'h80000000;	// @[FPU.scala:699:15, :706:32]
      else
        in_in2 <= io_in_bits_in2;	// @[FPU.scala:699:15]
      if (io_in_bits_ren3 | io_in_bits_swap23)	// @[FPU.scala:707:21]
        in_in3 <= io_in_bits_in3;	// @[FPU.scala:699:15]
      else	// @[FPU.scala:707:21]
        in_in3 <= (io_in_bits_in1 ^ io_in_bits_in2) & 65'h100000000;	// @[FPU.scala:699:15, :702:{32,50}]
    end
  end // always @(posedge)
  MulAddRecFNPipe fma (	// @[FPU.scala:710:19]
    .clock             (clock),
    .reset             (reset),
    .io_validin        (valid),	// @[FPU.scala:698:22]
    .io_op             (in_fmaCmd),	// @[FPU.scala:699:15]
    .io_a              (in_in1[32:0]),	// @[FPU.scala:699:15, :715:12]
    .io_b              (in_in2[32:0]),	// @[FPU.scala:699:15, :716:12]
    .io_c              (in_in3[32:0]),	// @[FPU.scala:699:15, :717:12]
    .io_roundingMode   (in_rm),	// @[FPU.scala:699:15]
    .io_out            (_fma_io_out),
    .io_exceptionFlags (io_out_bits_exc)
  );
  assign io_out_bits_data = {32'h0, _fma_io_out};	// @[FPU.scala:710:19, :720:12]
endmodule

