// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module GIB_89(
  input         clock,
                reset,
                io_cfg_en,
  input  [13:0] io_cfg_addr,
  input  [31:0] io_cfg_data,
  input         io_opinNW_0,
                io_opinNW_1,
                io_opinNE_0,
                io_opinNE_1,
                io_opinSE_0,
                io_opinSW_0,
                io_itrackW_0,
                io_itrackN_0,
                io_itrackE_0,
                io_itrackS_0,
  output        io_ipinNW_0,
                io_ipinNW_1,
                io_ipinNW_2,
                io_ipinNE_0,
                io_ipinNE_1,
                io_ipinNE_2,
                io_ipinSE_0,
                io_ipinSW_0,
                io_otrackW_0,
                io_otrackN_0,
                io_otrackE_0,
                io_otrackS_0
);

  wire [27:0] _cfg_io_out_0;	// @[Interconnect.scala:493:21]
  ConfigMem_70 cfg (	// @[Interconnect.scala:493:21]
    .clock       (clock),
    .reset       (reset),
    .io_cfg_en   (io_cfg_en & io_cfg_addr[13:6] == 8'h7D),	// @[Interconnect.scala:494:{32,50,65}]
    .io_cfg_data (io_cfg_data),
    .io_out_0    (_cfg_io_out_0)
  );
  Muxn_749 mux (	// @[Interconnect.scala:503:25]
    .io_config (_cfg_io_out_0[1:0]),	// @[Interconnect.scala:493:21, :513:39]
    .io_in_0   (io_opinSE_0),
    .io_in_1   (io_itrackE_0),
    .io_in_2   (io_itrackS_0),
    .io_out    (io_ipinNW_0)
  );
  Muxn_749 mux_1 (	// @[Interconnect.scala:503:25]
    .io_config (_cfg_io_out_0[3:2]),	// @[Interconnect.scala:493:21, :513:39]
    .io_in_0   (io_opinSW_0),
    .io_in_1   (io_itrackE_0),
    .io_in_2   (io_itrackS_0),
    .io_out    (io_ipinNW_1)
  );
  Muxn_2 mux_2 (	// @[Interconnect.scala:503:25]
    .io_config (_cfg_io_out_0[4]),	// @[Interconnect.scala:493:21, :513:39]
    .io_in_0   (io_itrackE_0),
    .io_in_1   (io_itrackS_0),
    .io_out    (io_ipinNW_2)
  );
  Muxn_747 mux_3 (	// @[Interconnect.scala:503:25]
    .io_config (_cfg_io_out_0[6:5]),	// @[Interconnect.scala:493:21, :513:39]
    .io_in_0   (io_opinNW_0),
    .io_in_1   (io_opinSW_0),
    .io_in_2   (io_itrackW_0),
    .io_in_3   (io_itrackS_0),
    .io_out    (io_ipinNE_0)
  );
  Muxn_2 mux_4 (	// @[Interconnect.scala:503:25]
    .io_config (_cfg_io_out_0[7]),	// @[Interconnect.scala:493:21, :513:39]
    .io_in_0   (io_itrackW_0),
    .io_in_1   (io_itrackS_0),
    .io_out    (io_ipinNE_1)
  );
  Muxn_749 mux_5 (	// @[Interconnect.scala:503:25]
    .io_config (_cfg_io_out_0[9:8]),	// @[Interconnect.scala:493:21, :513:39]
    .io_in_0   (io_opinNW_1),
    .io_in_1   (io_itrackW_0),
    .io_in_2   (io_itrackS_0),
    .io_out    (io_ipinNE_2)
  );
  Muxn_38 mux_6 (	// @[Interconnect.scala:503:25]
    .io_config (_cfg_io_out_0[12:10]),	// @[Interconnect.scala:493:21, :513:39]
    .io_in_0   (io_opinNW_0),
    .io_in_1   (io_opinNW_1),
    .io_in_2   (io_opinNE_0),
    .io_in_3   (io_opinNE_1),
    .io_in_4   (io_itrackW_0),
    .io_in_5   (io_itrackN_0),
    .io_out    (io_ipinSE_0)
  );
  Muxn_792 mux_7 (	// @[Interconnect.scala:503:25]
    .io_config (_cfg_io_out_0[15:13]),	// @[Interconnect.scala:493:21, :513:39]
    .io_in_0   (io_opinNE_0),
    .io_in_1   (io_opinNE_1),
    .io_in_2   (io_opinSE_0),
    .io_in_3   (io_itrackN_0),
    .io_in_4   (io_itrackE_0),
    .io_out    (io_ipinSW_0)
  );
  Muxn_38 mux_8 (	// @[Interconnect.scala:503:25]
    .io_config (_cfg_io_out_0[18:16]),	// @[Interconnect.scala:493:21, :513:39]
    .io_in_0   (io_opinNE_0),
    .io_in_1   (io_opinNE_1),
    .io_in_2   (io_opinSE_0),
    .io_in_3   (io_itrackN_0),
    .io_in_4   (io_itrackE_0),
    .io_in_5   (io_itrackS_0),
    .io_out    (io_otrackW_0)
  );
  Muxn_792 mux_9 (	// @[Interconnect.scala:503:25]
    .io_config (_cfg_io_out_0[21:19]),	// @[Interconnect.scala:493:21, :513:39]
    .io_in_0   (io_opinSE_0),
    .io_in_1   (io_opinSW_0),
    .io_in_2   (io_itrackW_0),
    .io_in_3   (io_itrackE_0),
    .io_in_4   (io_itrackS_0),
    .io_out    (io_otrackN_0)
  );
  Muxn_38 mux_10 (	// @[Interconnect.scala:503:25]
    .io_config (_cfg_io_out_0[24:22]),	// @[Interconnect.scala:493:21, :513:39]
    .io_in_0   (io_opinNW_0),
    .io_in_1   (io_opinNW_1),
    .io_in_2   (io_opinSW_0),
    .io_in_3   (io_itrackW_0),
    .io_in_4   (io_itrackN_0),
    .io_in_5   (io_itrackS_0),
    .io_out    (io_otrackE_0)
  );
  Muxn_110 mux_11 (	// @[Interconnect.scala:503:25]
    .io_config (_cfg_io_out_0[27:25]),	// @[Interconnect.scala:493:21, :513:39]
    .io_in_0   (io_opinNW_0),
    .io_in_1   (io_opinNW_1),
    .io_in_2   (io_opinNE_0),
    .io_in_3   (io_opinNE_1),
    .io_in_4   (io_itrackW_0),
    .io_in_5   (io_itrackN_0),
    .io_in_6   (io_itrackE_0),
    .io_out    (io_otrackS_0)
  );
endmodule

