// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module IOController(
  input          clock,
                 reset,
  input  [31:0]  io_sram_dout,
  input          io_start,
  input  [106:0] io_config,
  input  [31:0]  io_in_cg_0,
                 io_in_cg_1,
  input          io_in_fg_0,
  output         io_sram_en,
                 io_sram_we,
  output [11:0]  io_sram_addr,
  output [31:0]  io_sram_din,
  output         io_done,
  output [31:0]  io_out_cg_0,
  output         io_out_fg_0
);

  reg  [1:0]  state;	// @[IOController.scala:131:22]
  reg  [5:0]  latCnt;	// @[IOController.scala:132:23]
  reg  [12:0] cycleCnt_0;	// @[IOController.scala:133:49]
  reg  [12:0] cycleCnt_1;	// @[IOController.scala:133:49]
  reg  [12:0] cycleCnt_2;	// @[IOController.scala:133:49]
  reg  [3:0]  iiCnt;	// @[IOController.scala:134:22]
  reg         done;	// @[IOController.scala:135:21]
  wire [12:0] _cycleCntEnd_T_1 = cycleCnt_0 + 13'h1;	// @[IOController.scala:133:49, :138:37]
  wire [12:0] _cycleCntEnd_T_6 = cycleCnt_1 + 13'h1;	// @[IOController.scala:133:49, :138:37]
  wire [12:0] _cycleCntEnd_T_15 = cycleCnt_2 + 13'h1;	// @[IOController.scala:133:49, :138:37]
  wire        launch = state == 2'h2;	// @[IOController.scala:131:22, :155:15, :189:23]
  wire        _raValid_T_1 = iiCnt == 4'h0;	// @[IOController.scala:134:22, :223:44]
  reg  [12:0] genAddrReg;	// @[IOController.scala:228:27]
  wire        realEn = ~(io_config[102]) & launch & _raValid_T_1 & ((io_config[22:12] == 11'h0 & _cycleCntEnd_T_1 >= io_config[35:23] | (|(io_config[22:12]))) & (io_config[46:36] == 11'h0 & _cycleCntEnd_T_6 >= io_config[59:47] | (|(io_config[46:36]))) & (io_config[70:60] == 11'h0 & _cycleCntEnd_T_15 >= io_config[83:71] | (|(io_config[70:60]))) | io_config[105]) | io_config[102] & launch & _raValid_T_1;	// @[IOController.scala:81:24, :84:24, :119:25, :122:26, :138:37, :189:23, :213:{16,24,45,59,72}, :214:14, :223:{16,44}, :226:34, :240:{24,39,52}]
  reg         first_en;	// @[IOController.scala:252:25]
  wire        _wen_T_4 = realEn & ~(io_config[102]) & io_in_fg_0;	// @[IOController.scala:119:25, :223:16, :240:52, :271:46]
  wire        _wen_T_8 = realEn & ~(io_config[102]);	// @[IOController.scala:119:25, :223:16, :240:52, :271:85]
  wire        wen = io_config[103] ? _wen_T_4 : _wen_T_8;	// @[IOController.scala:120:26, :271:{17,46,85}]
  wire        _T_34 = io_config[105] & io_config[102];	// @[IOController.scala:119:25, :122:26, :291:18]
  wire [11:0] _GEN = io_config[11:0] + io_in_cg_0[13:2];	// @[IOController.scala:74:27, :292:29]
  wire        _T_36 = io_config[105] & ~(io_config[102]);	// @[IOController.scala:119:25, :122:26, :223:16, :293:24]
  wire [11:0] _GEN_0 = io_config[11:0] + io_in_cg_1[13:2];	// @[IOController.scala:74:27, :294:29]
  wire [11:0] addr_temp = _T_34 ? _GEN : _T_36 ? _GEN_0 : genAddrReg[11:0];	// @[IOController.scala:228:27, :291:{18,28}, :292:{17,29}, :293:{24,34}, :294:{17,29}, :296:17]
  wire [11:0] _BankIdx_T = addr_temp >> io_config[101:98];	// @[IOController.scala:115:23, :291:28, :292:17, :293:34, :298:34]
  wire [3:0]  _GEN_1 = {2'h0, io_config[97:96]};	// @[IOController.scala:107:23, :131:22, :298:58]
  wire [3:0]  _BankIdx_T_1 = 4'h1 << _GEN_1;	// @[IOController.scala:298:58]
  wire [26:0] _BankOffset_T_3 = {15'h0, addr_temp >> _GEN_1 + io_config[101:98]} << io_config[101:98];	// @[IOController.scala:115:23, :291:28, :292:17, :293:34, :298:58, :299:{38,47,63}]
  wire [15:0] _BankOffset_T_4 = 16'h1 << io_config[101:98];	// @[IOController.scala:115:23, :299:107]
  wire        _T_37 = io_config[97:96] == 2'h0;	// @[IOController.scala:107:23, :131:22, :300:15]
  wire [11:0] _GEN_2 = {io_config[95:94] + (_BankIdx_T[1:0] & _BankIdx_T_1[1:0] - 2'h1), 10'h0} + {2'h0, _BankOffset_T_3[9:0] + (addr_temp[9:0] & _BankOffset_T_4[9:0] - 10'h1)};	// @[IOController.scala:103:31, :131:22, :291:28, :292:17, :293:34, :298:{34,50,58,74}, :299:{63,79,99,107,123}, :303:{30,41,70}]
  reg  [11:0] addrReg;	// @[IOController.scala:328:26]
  wire        _io_sram_en_T_1 = wen | (~(io_config[103]) | io_in_fg_0 | first_en) & realEn & io_config[102];	// @[IOController.scala:119:25, :120:26, :240:52, :252:25, :271:17, :272:17, :329:14]
  reg  [31:0] wDataReg;	// @[IOController.scala:332:27]
  reg  [31:0] io_out_cg_0_REG;	// @[IOController.scala:341:30]
  reg         io_sram_en_REG;	// @[IOController.scala:343:28]
  wire        _io_sram_en_output = io_config[102] ? _io_sram_en_T_1 : io_sram_en_REG;	// @[IOController.scala:119:25, :329:14, :336:17, :337:18, :343:{18,28}]
  reg         io_sram_we_REG;	// @[IOController.scala:344:28]
  wire        _io_sram_we_output = io_config[102] ? wen : io_sram_we_REG;	// @[IOController.scala:119:25, :271:17, :336:17, :338:18, :344:{18,28}]
  reg         io_out_fg_0_REG;	// @[IOController.scala:365:28]
  wire [5:0]  _T_10 = latCnt + 6'h1;	// @[IOController.scala:132:23, :163:19]
  wire        cntEnd = _cycleCntEnd_T_1 >= io_config[35:23] & _cycleCntEnd_T_6 >= io_config[59:47] & _cycleCntEnd_T_15 >= io_config[83:71];	// @[IOController.scala:84:24, :138:{37,43,67}]
  wire        _T_8 = state == 2'h1;	// @[IOController.scala:131:22, :151:16, :158:15]
  wire [3:0]  _iiEnd_T_1 = iiCnt + 4'h1;	// @[IOController.scala:134:22, :136:22, :298:58]
  wire        iiEnd = _iiEnd_T_1 >= io_config[87:84];	// @[IOController.scala:95:21, :136:{22,28}]
  wire        cycleCntEnd_0 = _cycleCntEnd_T_1 >= io_config[35:23];	// @[IOController.scala:84:24, :138:{37,43}]
  wire        cycleCntEnd_1 = _cycleCntEnd_T_1 >= io_config[35:23] & _cycleCntEnd_T_6 >= io_config[59:47];	// @[IOController.scala:84:24, :138:{37,43,67}]
  wire        _T_5 = io_start & ~(|(io_config[93:88]));	// @[IOController.scala:99:26, :154:{21,32}]
  wire        _T_7 = io_start & (|(io_config[93:88]));	// @[IOController.scala:99:26, :157:{27,38}]
  wire        _GEN_3 = state == 2'h2 & cntEnd & iiEnd;	// @[IOController.scala:131:22, :136:28, :138:67, :151:16, :155:15, :169:54, :170:15]
  wire [10:0] _genAddrReg_T_3 = cycleCntEnd_1 ? io_config[70:60] : cycleCntEnd_0 ? io_config[46:36] : io_config[22:12];	// @[IOController.scala:81:24, :138:{43,67}, Mux.scala:47:70]
  always @(posedge clock) begin
    if (reset) begin
      state <= 2'h0;	// @[IOController.scala:131:22]
      latCnt <= 6'h0;	// @[IOController.scala:132:23]
      cycleCnt_0 <= 13'h0;	// @[IOController.scala:133:49, :228:27]
      cycleCnt_1 <= 13'h0;	// @[IOController.scala:133:49, :228:27]
      cycleCnt_2 <= 13'h0;	// @[IOController.scala:133:49, :228:27]
      iiCnt <= 4'h0;	// @[IOController.scala:134:22]
      done <= 1'h0;	// @[IOController.scala:135:21]
      genAddrReg <= 13'h0;	// @[IOController.scala:228:27]
      first_en <= 1'h0;	// @[IOController.scala:135:21, :252:25]
      addrReg <= 12'h0;	// @[IOController.scala:328:26]
      wDataReg <= 32'h0;	// @[IOController.scala:332:27]
    end
    else begin
      if (state == 2'h0) begin	// @[IOController.scala:131:22, :151:16]
        if (_T_5)	// @[IOController.scala:154:21]
          state <= 2'h2;	// @[IOController.scala:131:22, :155:15]
        else if (_T_7)	// @[IOController.scala:157:27]
          state <= 2'h1;	// @[IOController.scala:131:22, :158:15]
        latCnt <= 6'h0;	// @[IOController.scala:132:23]
        cycleCnt_0 <= 13'h0;	// @[IOController.scala:133:49, :228:27]
        cycleCnt_1 <= 13'h0;	// @[IOController.scala:133:49, :228:27]
        cycleCnt_2 <= 13'h0;	// @[IOController.scala:133:49, :228:27]
        iiCnt <= 4'h0;	// @[IOController.scala:134:22]
        done <= ~(_T_5 | _T_7) & done;	// @[IOController.scala:135:21, :154:{21,40}, :156:14, :157:{27,46}, :159:14]
      end
      else begin	// @[IOController.scala:151:16]
        if (_T_8) begin	// @[IOController.scala:151:16]
          if (_T_10 == io_config[93:88])	// @[IOController.scala:99:26, :163:{19,25}]
            state <= 2'h2;	// @[IOController.scala:131:22, :155:15]
          latCnt <= _T_10;	// @[IOController.scala:132:23, :163:19]
        end
        else if (_GEN_3)	// @[IOController.scala:131:22, :151:16, :169:54, :170:15]
          state <= 2'h0;	// @[IOController.scala:131:22]
        if (launch) begin	// @[IOController.scala:189:23]
          if (iiEnd & ~cycleCntEnd_0)	// @[IOController.scala:136:28, :138:43, :200:{18,21}]
            cycleCnt_0 <= _cycleCntEnd_T_1;	// @[IOController.scala:133:49, :138:37]
          else if (iiEnd)	// @[IOController.scala:136:28]
            cycleCnt_0 <= 13'h0;	// @[IOController.scala:133:49, :228:27]
          if (iiEnd & ~cycleCntEnd_1)	// @[IOController.scala:136:28, :138:67, :200:{18,21}]
            cycleCnt_1 <= cycleCnt_1 + {12'h0, cycleCntEnd_0};	// @[IOController.scala:133:49, :138:43, :201:36, :328:26]
          else if (iiEnd)	// @[IOController.scala:136:28]
            cycleCnt_1 <= 13'h0;	// @[IOController.scala:133:49, :228:27]
          if (iiEnd & ~cntEnd)	// @[IOController.scala:136:28, :138:67, :200:{18,21}]
            cycleCnt_2 <= cycleCnt_2 + {12'h0, cycleCntEnd_1};	// @[IOController.scala:133:49, :138:67, :201:36, :328:26]
          else if (iiEnd)	// @[IOController.scala:136:28]
            cycleCnt_2 <= 13'h0;	// @[IOController.scala:133:49, :228:27]
          if (iiEnd)	// @[IOController.scala:136:28]
            iiCnt <= 4'h0;	// @[IOController.scala:134:22]
          else	// @[IOController.scala:136:28]
            iiCnt <= _iiEnd_T_1;	// @[IOController.scala:134:22, :136:22]
        end
        done <= ~_T_8 & _GEN_3 | done;	// @[IOController.scala:131:22, :135:21, :151:16, :169:54, :170:15]
      end
      if (launch) begin	// @[IOController.scala:189:23]
        if (iiEnd)	// @[IOController.scala:136:28]
          genAddrReg <= genAddrReg + {{2{_genAddrReg_T_3[10]}}, _genAddrReg_T_3};	// @[IOController.scala:228:27, :283:30, Mux.scala:47:70]
      end
      else	// @[IOController.scala:189:23]
        genAddrReg <= {1'h0, io_config[11:0]};	// @[Cat.scala:33:92, IOController.scala:74:27, :135:21, :228:27]
      first_en <= io_start & ~(|(io_config[93:88])) & ~first_en | ~(realEn & first_en) & first_en;	// @[IOController.scala:99:26, :154:32, :240:52, :252:25, :253:{28,36,48,56}, :254:14, :255:{21,41}, :256:14, :258:14]
      if (_io_sram_en_T_1) begin	// @[IOController.scala:329:14]
        if (_T_37) begin	// @[IOController.scala:300:15]
          if (_T_34)	// @[IOController.scala:291:18]
            addrReg <= _GEN;	// @[IOController.scala:292:29, :328:26]
          else if (_T_36)	// @[IOController.scala:293:24]
            addrReg <= _GEN_0;	// @[IOController.scala:294:29, :328:26]
          else	// @[IOController.scala:293:24]
            addrReg <= genAddrReg[11:0];	// @[IOController.scala:228:27, :296:17, :328:26]
        end
        else	// @[IOController.scala:300:15]
          addrReg <= _GEN_2;	// @[IOController.scala:303:70, :328:26]
      end
      if (wen)	// @[IOController.scala:271:17]
        wDataReg <= io_in_cg_0;	// @[IOController.scala:332:27]
    end
    io_out_cg_0_REG <= io_sram_dout;	// @[IOController.scala:341:30]
    io_sram_en_REG <= _io_sram_en_T_1;	// @[IOController.scala:329:14, :343:28]
    if (io_config[103])	// @[IOController.scala:120:26]
      io_sram_we_REG <= _wen_T_4;	// @[IOController.scala:271:46, :344:28]
    else	// @[IOController.scala:120:26]
      io_sram_we_REG <= _wen_T_8;	// @[IOController.scala:271:85, :344:28]
    io_out_fg_0_REG <= ~_io_sram_en_output & ~_io_sram_we_output & io_config[104];	// @[IOController.scala:121:27, :336:17, :337:18, :338:18, :343:18, :344:18, :365:{28,40,62,71}]
  end // always @(posedge)
  assign io_sram_en = _io_sram_en_output;	// @[IOController.scala:336:17, :337:18, :343:18]
  assign io_sram_we = _io_sram_we_output;	// @[IOController.scala:336:17, :338:18, :344:18]
  assign io_sram_addr = io_config[102] ? (_T_37 ? addr_temp : _GEN_2) : addrReg;	// @[IOController.scala:119:25, :291:28, :292:17, :293:34, :300:{15,23}, :301:12, :303:{12,70}, :328:26, :336:17, :339:20, :345:20]
  assign io_sram_din = io_config[102] ? io_in_cg_0 : wDataReg;	// @[IOController.scala:119:25, :332:27, :336:17, :340:19, :346:19]
  assign io_done = done;	// @[IOController.scala:135:21]
  assign io_out_cg_0 = io_out_cg_0_REG;	// @[IOController.scala:341:30]
  assign io_out_fg_0 = io_out_fg_0_REG;	// @[IOController.scala:365:28]
endmodule

