// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module JtagBypassChain(
  input  clock,
         reset,
         io_chainIn_shift,
         io_chainIn_data,
         io_chainIn_capture,
         io_chainIn_update,
  output io_chainOut_data
);

  reg reg_0;	// @[JtagShifter.scala:61:16]
  `ifndef SYNTHESIS	// @[JtagShifter.scala:72:9]
    always @(posedge clock) begin	// @[JtagShifter.scala:72:9]
      if (~reset & ~(~(io_chainIn_capture & io_chainIn_update) & ~(io_chainIn_capture & io_chainIn_shift) & ~(io_chainIn_update & io_chainIn_shift))) begin	// @[JtagShifter.scala:72:{9,10,31}, :73:{10,31}, :74:{7,10,30}]
        if (`ASSERT_VERBOSE_COND_)	// @[JtagShifter.scala:72:9]
          $error("Assertion failed\n    at JtagShifter.scala:72 assert(!(io.chainIn.capture && io.chainIn.update)\n");	// @[JtagShifter.scala:72:9]
        if (`STOP_COND_)	// @[JtagShifter.scala:72:9]
          $fatal;	// @[JtagShifter.scala:72:9]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  always @(posedge clock) begin
    if (io_chainIn_capture)
      reg_0 <= 1'h0;	// @[JtagShifter.scala:61:16]
    else if (io_chainIn_shift)
      reg_0 <= io_chainIn_data;	// @[JtagShifter.scala:61:16]
  end // always @(posedge)
  assign io_chainOut_data = reg_0;	// @[JtagShifter.scala:61:16]
endmodule

