// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module LoadController(
  input          clock,
                 reset,
                 io_core_req_valid,
  input  [63:0]  io_core_req_bits_cmd_rs1,
                 io_core_req_bits_cmd_rs2,
  input  [1:0]   io_core_req_bits_cmd_status_prv,
  input  [7:0]   io_core_req_bits_id,
  input          io_dma_req_ready,
                 io_dma_stream_valid,
  input  [127:0] io_dma_stream_bits_data,
  input  [7:0]   io_dma_stream_bits_id,
  input          io_dma_stream_bits_last,
                 io_dma_exp_req,
                 io_spad_req_ready,
                 io_spad_stream_ready,
                 io_spad_exp_ack,
  output         io_core_req_ready,
                 io_core_resp_valid,
  output [7:0]   io_core_resp_bits_id,
  output         io_dma_req_valid,
  output [39:0]  io_dma_req_bits_addr,
  output [15:0]  io_dma_req_bits_len,
  output [7:0]   io_dma_req_bits_id,
  output [1:0]   io_dma_req_bits_status_prv,
  output         io_dma_stream_ready,
                 io_dma_exp_ack,
                 io_spad_req_valid,
  output [15:0]  io_spad_req_bits_addrs_0,
                 io_spad_req_bits_addrs_1,
                 io_spad_req_bits_addrs_2,
                 io_spad_req_bits_addrs_3,
                 io_spad_req_bits_addrs_4,
  output [2:0]   io_spad_req_bits_num,
  output [15:0]  io_spad_req_bits_len,
  output [1:0]   io_spad_req_bits_lgPartitionSize,
  output [3:0]   io_spad_req_bits_lgPartitionBlockSize,
  output [1:0]   io_spad_req_bits_offsetId_0,
                 io_spad_req_bits_offsetId_1,
                 io_spad_req_bits_offsetId_2,
                 io_spad_req_bits_offsetId_3,
                 io_spad_req_bits_offsetId_4,
  output         io_spad_stream_valid,
  output [127:0] io_spad_stream_bits_data,
  output         io_spad_exp_req
);

  wire        _que_io_enq_ready;	// @[LoadController.scala:190:21]
  wire        _spadReqQue_io_enq_ready;	// @[LoadController.scala:42:26]
  wire        _spadReqQue_io_deq_valid;	// @[LoadController.scala:42:26]
  wire [2:0]  _spadReqQue_io_deq_bits_num;	// @[LoadController.scala:42:26]
  wire [15:0] _spadReqQue_io_deq_bits_len;	// @[LoadController.scala:42:26]
  wire [7:0]  _spadReqQue_io_deq_bits_id;	// @[LoadController.scala:42:26]
  reg         state;	// @[LoadController.scala:46:22]
  reg  [39:0] remote_addr;	// @[LoadController.scala:47:28]
  reg  [15:0] spad_addrs_0;	// @[LoadController.scala:49:27]
  reg  [15:0] spad_addrs_1;	// @[LoadController.scala:49:27]
  reg  [15:0] spad_addrs_2;	// @[LoadController.scala:49:27]
  reg  [15:0] spad_addrs_3;	// @[LoadController.scala:49:27]
  reg  [15:0] spad_addrs_4;	// @[LoadController.scala:49:27]
  reg  [1:0]  bank_offsets_0;	// @[LoadController.scala:50:29]
  reg  [1:0]  bank_offsets_1;	// @[LoadController.scala:50:29]
  reg  [1:0]  bank_offsets_2;	// @[LoadController.scala:50:29]
  reg  [1:0]  bank_offsets_3;	// @[LoadController.scala:50:29]
  reg  [1:0]  bank_offsets_4;	// @[LoadController.scala:50:29]
  reg  [2:0]  addr_num;	// @[LoadController.scala:51:25]
  reg  [1:0]  lgPartitionSize;	// @[LoadController.scala:56:32]
  reg  [3:0]  lgPartitionBlockSize;	// @[LoadController.scala:57:37]
  reg  [1:0]  status_prv;	// @[LoadController.scala:58:19]
  reg  [7:0]  id;	// @[LoadController.scala:59:19]
  reg  [15:0] real_request_len;	// @[LoadController.scala:65:33]
  wire        _io_dma_req_valid_output = state & _spadReqQue_io_enq_ready;	// @[LoadController.scala:42:26, :46:22, :101:45]
  reg  [2:0]  spadState;	// @[LoadController.scala:119:26]
  reg  [15:0] leftLen;	// @[LoadController.scala:120:24]
  reg  [7:0]  spadReqId;	// @[LoadController.scala:121:26]
  reg  [2:0]  leftNum;	// @[LoadController.scala:123:24]
  wire        _io_spad_req_valid_T = spadState == 3'h0;	// @[LoadController.scala:51:25, :119:26, :125:20]
  wire        _io_spad_req_valid_output = _io_spad_req_valid_T & _spadReqQue_io_deq_valid;	// @[LoadController.scala:42:26, :125:20, :171:51]
  wire        _io_spad_exp_req_output = spadState == 3'h2;	// @[LoadController.scala:73:30, :119:26, :181:33]
  wire        _que_io_enq_valid_T = spadState == 3'h1;	// @[LoadController.scala:73:30, :119:26, :192:59]
  wire        _io_dma_stream_ready_output = _que_io_enq_ready & _que_io_enq_valid_T;	// @[LoadController.scala:190:21, :192:{45,59}]
  wire        _io_core_resp_valid_output = spadState == 3'h3 | spadState == 3'h4;	// @[LoadController.scala:73:30, :83:44, :119:26, :199:{36,52,66}]
  wire        _T_11 = spadState == 3'h1;	// @[LoadController.scala:73:30, :119:26, :125:20]
  wire        _T_12 = _io_dma_stream_ready_output & io_dma_stream_valid;	// @[Decoupled.scala:51:35, LoadController.scala:192:45]
  wire        _T_13 = spadState == 3'h2;	// @[LoadController.scala:73:30, :119:26, :125:20]
  wire        _T_14 = spadState == 3'h3;	// @[LoadController.scala:73:30, :119:26, :125:20]
  wire        _T_5 = ~(io_core_req_bits_cmd_rs2[48]) | addr_num == 3'h4;	// @[LoadController.scala:51:25, :61:46, :83:{14,32,44}]
  wire        _GEN = state & io_dma_req_ready & _io_dma_req_valid_output;	// @[LoadController.scala:46:22, :69:16, :92:28, :93:15, :101:45]
  wire        _T_9 = io_spad_req_ready & _io_spad_req_valid_output;	// @[Decoupled.scala:51:35, LoadController.scala:171:51]
  wire        _T_1 = ~state & io_core_req_valid;	// @[Decoupled.scala:51:35, LoadController.scala:46:22, :69:16]
  wire        _GEN_0 = ~state & _T_1;	// @[Decoupled.scala:51:35, LoadController.scala:46:22, :47:28, :69:16, :71:29, :72:21]
  always @(posedge clock) begin
    if (reset) begin
      state <= 1'h0;	// @[LoadController.scala:46:22]
      remote_addr <= 40'h0;	// @[LoadController.scala:47:28]
      spad_addrs_0 <= 16'h0;	// @[LoadController.scala:49:{27,35}]
      spad_addrs_1 <= 16'h0;	// @[LoadController.scala:49:{27,35}]
      spad_addrs_2 <= 16'h0;	// @[LoadController.scala:49:{27,35}]
      spad_addrs_3 <= 16'h0;	// @[LoadController.scala:49:{27,35}]
      spad_addrs_4 <= 16'h0;	// @[LoadController.scala:49:{27,35}]
      bank_offsets_0 <= 2'h0;	// @[LoadController.scala:50:{29,37}]
      bank_offsets_1 <= 2'h0;	// @[LoadController.scala:50:{29,37}]
      bank_offsets_2 <= 2'h0;	// @[LoadController.scala:50:{29,37}]
      bank_offsets_3 <= 2'h0;	// @[LoadController.scala:50:{29,37}]
      bank_offsets_4 <= 2'h0;	// @[LoadController.scala:50:{29,37}]
      addr_num <= 3'h0;	// @[LoadController.scala:51:25]
      lgPartitionSize <= 2'h0;	// @[LoadController.scala:50:37, :56:32]
      lgPartitionBlockSize <= 4'h0;	// @[LoadController.scala:57:37]
      id <= 8'h0;	// @[LoadController.scala:59:19]
      real_request_len <= 16'h0;	// @[LoadController.scala:49:35, :65:33]
      spadState <= 3'h0;	// @[LoadController.scala:51:25, :119:26]
      leftLen <= 16'h0;	// @[LoadController.scala:49:35, :120:24]
      spadReqId <= 8'h0;	// @[LoadController.scala:59:19, :121:26]
      leftNum <= 3'h0;	// @[LoadController.scala:51:25, :123:24]
    end
    else begin
      if (state)	// @[LoadController.scala:46:22]
        state <= ~_GEN & state;	// @[LoadController.scala:46:22, :69:16, :92:28, :93:15]
      else if (_T_1)	// @[Decoupled.scala:51:35]
        state <= _T_5;	// @[LoadController.scala:46:22, :83:32]
      if (_GEN_0) begin	// @[LoadController.scala:47:28, :69:16, :71:29, :72:21]
        remote_addr <= io_core_req_bits_cmd_rs1[39:0];	// @[LoadController.scala:47:28, :72:21]
        lgPartitionSize <= io_core_req_bits_cmd_rs2[54:53];	// @[LoadController.scala:56:32, :61:46]
        lgPartitionBlockSize <= io_core_req_bits_cmd_rs2[52:49];	// @[LoadController.scala:57:37, :61:46]
        id <= io_core_req_bits_id;	// @[LoadController.scala:59:19]
        if (io_core_req_bits_cmd_rs1[3:2] == 2'h0)	// @[LoadController.scala:50:37, :66:41, :79:50]
          real_request_len <= io_core_req_bits_cmd_rs2[47:32];	// @[LoadController.scala:61:46, :65:33]
        else	// @[LoadController.scala:79:50]
          real_request_len <= io_core_req_bits_cmd_rs2[47:32] + 16'h10;	// @[LoadController.scala:61:46, :65:33, :79:88, :145:34]
      end
      if (~state & _T_1 & addr_num == 3'h0) begin	// @[Decoupled.scala:51:35, LoadController.scala:46:22, :49:27, :51:25, :69:16, :71:29, :73:30]
        spad_addrs_0 <= io_core_req_bits_cmd_rs2[15:0];	// @[LoadController.scala:49:27, :73:30]
        bank_offsets_0 <= addr_num[1:0];	// @[LoadController.scala:50:29, :51:25, :74:32]
      end
      if (~state & _T_1 & addr_num == 3'h1) begin	// @[Decoupled.scala:51:35, LoadController.scala:46:22, :49:27, :51:25, :69:16, :71:29, :73:30]
        spad_addrs_1 <= io_core_req_bits_cmd_rs2[15:0];	// @[LoadController.scala:49:27, :73:30]
        bank_offsets_1 <= addr_num[1:0];	// @[LoadController.scala:50:29, :51:25, :74:32]
      end
      if (~state & _T_1 & addr_num == 3'h2) begin	// @[Decoupled.scala:51:35, LoadController.scala:46:22, :49:27, :51:25, :69:16, :71:29, :73:30]
        spad_addrs_2 <= io_core_req_bits_cmd_rs2[15:0];	// @[LoadController.scala:49:27, :73:30]
        bank_offsets_2 <= addr_num[1:0];	// @[LoadController.scala:50:29, :51:25, :74:32]
      end
      if (~state & _T_1 & addr_num == 3'h3) begin	// @[Decoupled.scala:51:35, LoadController.scala:46:22, :49:27, :51:25, :69:16, :71:29, :73:30]
        spad_addrs_3 <= io_core_req_bits_cmd_rs2[15:0];	// @[LoadController.scala:49:27, :73:30]
        bank_offsets_3 <= addr_num[1:0];	// @[LoadController.scala:50:29, :51:25, :74:32]
      end
      if (~state & _T_1 & addr_num == 3'h4) begin	// @[Decoupled.scala:51:35, LoadController.scala:46:22, :49:27, :51:25, :69:16, :71:29, :73:30, :83:44]
        spad_addrs_4 <= io_core_req_bits_cmd_rs2[15:0];	// @[LoadController.scala:49:27, :73:30]
        bank_offsets_4 <= addr_num[1:0];	// @[LoadController.scala:50:29, :51:25, :74:32]
      end
      if (state) begin	// @[LoadController.scala:46:22]
        if (_GEN)	// @[LoadController.scala:46:22, :69:16, :92:28, :93:15]
          addr_num <= 3'h0;	// @[LoadController.scala:51:25]
      end
      else if (~_T_1 | _T_5) begin	// @[Decoupled.scala:51:35, LoadController.scala:51:25, :71:29, :83:{32,66}]
      end
      else	// @[LoadController.scala:51:25, :71:29, :83:66]
        addr_num <= addr_num + 3'h1;	// @[LoadController.scala:51:25, :73:30, :87:32]
      if (_io_spad_req_valid_T) begin	// @[LoadController.scala:125:20]
        if (_T_9) begin	// @[Decoupled.scala:51:35]
          spadState <= {1'h0, |_spadReqQue_io_deq_bits_num, 1'h1};	// @[LoadController.scala:42:26, :119:26, :132:{41,47}, :133:21, :135:21]
          leftLen <= _spadReqQue_io_deq_bits_len;	// @[LoadController.scala:42:26, :120:24]
          leftNum <= _spadReqQue_io_deq_bits_num;	// @[LoadController.scala:42:26, :123:24]
        end
      end
      else begin	// @[LoadController.scala:125:20]
        if (_T_11) begin	// @[LoadController.scala:125:20]
          if (io_dma_exp_req)
            spadState <= 3'h2;	// @[LoadController.scala:73:30, :119:26]
          else if (_T_12) begin	// @[Decoupled.scala:51:35]
            if (leftLen < 16'h11)	// @[LoadController.scala:120:24, :145:34]
              spadState <= 3'h4;	// @[LoadController.scala:83:44, :119:26]
            else	// @[LoadController.scala:145:34]
              spadState <= 3'h1;	// @[LoadController.scala:73:30, :119:26]
          end
        end
        else if (_T_13) begin	// @[LoadController.scala:125:20]
          if (io_spad_exp_ack)
            spadState <= 3'h4;	// @[LoadController.scala:83:44, :119:26]
        end
        else if (_T_14) begin	// @[LoadController.scala:125:20]
          if (_io_core_resp_valid_output & leftNum == 3'h1)	// @[LoadController.scala:73:30, :119:26, :123:24, :154:30, :156:{22,30}, :157:21, :199:52]
            spadState <= 3'h1;	// @[LoadController.scala:73:30, :119:26]
        end
        else if (spadState == 3'h4 & _io_core_resp_valid_output)	// @[LoadController.scala:83:44, :119:26, :125:20, :162:30, :163:19, :199:52]
          spadState <= 3'h0;	// @[LoadController.scala:51:25, :119:26]
        if (~_T_11 | io_dma_exp_req | ~_T_12) begin	// @[Decoupled.scala:51:35, LoadController.scala:120:24, :125:20, :140:27, :143:37]
        end
        else	// @[LoadController.scala:120:24, :125:20, :140:27]
          leftLen <= leftLen - 16'h10;	// @[LoadController.scala:120:24, :144:28]
        if (_T_11 | _T_13 | ~(_T_14 & _io_core_resp_valid_output)) begin	// @[LoadController.scala:123:24, :125:20, :154:30, :155:17, :199:52]
        end
        else	// @[LoadController.scala:123:24, :125:20]
          leftNum <= leftNum - 3'h1;	// @[LoadController.scala:123:24, :155:28]
      end
      if (_io_spad_req_valid_T & _T_9)	// @[Decoupled.scala:51:35, LoadController.scala:121:26, :125:20, :127:29, :130:19]
        spadReqId <= _spadReqQue_io_deq_bits_id;	// @[LoadController.scala:42:26, :121:26]
    end
    if (_GEN_0)	// @[LoadController.scala:47:28, :69:16, :71:29, :72:21]
      status_prv <= io_core_req_bits_cmd_status_prv;	// @[LoadController.scala:58:19]
  end // always @(posedge)
  Queue_76 spadReqQue (	// @[LoadController.scala:42:26]
    .clock                            (clock),
    .reset                            (reset),
    .io_enq_valid                     (state & io_dma_req_ready),	// @[LoadController.scala:46:22, :107:52]
    .io_enq_bits_addrs_0              (spad_addrs_0),	// @[LoadController.scala:49:27]
    .io_enq_bits_addrs_1              (spad_addrs_1),	// @[LoadController.scala:49:27]
    .io_enq_bits_addrs_2              (spad_addrs_2),	// @[LoadController.scala:49:27]
    .io_enq_bits_addrs_3              (spad_addrs_3),	// @[LoadController.scala:49:27]
    .io_enq_bits_addrs_4              (spad_addrs_4),	// @[LoadController.scala:49:27]
    .io_enq_bits_num                  (addr_num),	// @[LoadController.scala:51:25]
    .io_enq_bits_len                  (real_request_len),	// @[LoadController.scala:65:33]
    .io_enq_bits_id                   (id),	// @[LoadController.scala:59:19]
    .io_enq_bits_lgPartitionSize      (lgPartitionSize),	// @[LoadController.scala:56:32]
    .io_enq_bits_lgPartitionBlockSize (lgPartitionBlockSize),	// @[LoadController.scala:57:37]
    .io_enq_bits_offsetId_0           (bank_offsets_0),	// @[LoadController.scala:50:29]
    .io_enq_bits_offsetId_1           (bank_offsets_1),	// @[LoadController.scala:50:29]
    .io_enq_bits_offsetId_2           (bank_offsets_2),	// @[LoadController.scala:50:29]
    .io_enq_bits_offsetId_3           (bank_offsets_3),	// @[LoadController.scala:50:29]
    .io_enq_bits_offsetId_4           (bank_offsets_4),	// @[LoadController.scala:50:29]
    .io_deq_ready                     (_io_spad_req_valid_T & io_spad_req_ready),	// @[LoadController.scala:125:20, :169:57]
    .io_enq_ready                     (_spadReqQue_io_enq_ready),
    .io_deq_valid                     (_spadReqQue_io_deq_valid),
    .io_deq_bits_addrs_0              (io_spad_req_bits_addrs_0),
    .io_deq_bits_addrs_1              (io_spad_req_bits_addrs_1),
    .io_deq_bits_addrs_2              (io_spad_req_bits_addrs_2),
    .io_deq_bits_addrs_3              (io_spad_req_bits_addrs_3),
    .io_deq_bits_addrs_4              (io_spad_req_bits_addrs_4),
    .io_deq_bits_num                  (_spadReqQue_io_deq_bits_num),
    .io_deq_bits_len                  (_spadReqQue_io_deq_bits_len),
    .io_deq_bits_id                   (_spadReqQue_io_deq_bits_id),
    .io_deq_bits_lgPartitionSize      (io_spad_req_bits_lgPartitionSize),
    .io_deq_bits_lgPartitionBlockSize (io_spad_req_bits_lgPartitionBlockSize),
    .io_deq_bits_offsetId_0           (io_spad_req_bits_offsetId_0),
    .io_deq_bits_offsetId_1           (io_spad_req_bits_offsetId_1),
    .io_deq_bits_offsetId_2           (io_spad_req_bits_offsetId_2),
    .io_deq_bits_offsetId_3           (io_spad_req_bits_offsetId_3),
    .io_deq_bits_offsetId_4           (io_spad_req_bits_offsetId_4)
  );
  Queue_77 que (	// @[LoadController.scala:190:21]
    .clock            (clock),
    .reset            (reset),
    .io_enq_valid     (io_dma_stream_valid & _que_io_enq_valid_T),	// @[LoadController.scala:192:59, :193:45]
    .io_enq_bits_data (io_dma_stream_bits_data),
    .io_enq_bits_id   (io_dma_stream_bits_id),
    .io_enq_bits_last (io_dma_stream_bits_last),
    .io_deq_ready     (io_spad_stream_ready),
    .io_flush         (_io_spad_exp_req_output),	// @[LoadController.scala:181:33]
    .io_enq_ready     (_que_io_enq_ready),
    .io_deq_valid     (io_spad_stream_valid),
    .io_deq_bits_data (io_spad_stream_bits_data)
  );
  assign io_core_req_ready = ~state;	// @[LoadController.scala:46:22, :69:16]
  assign io_core_resp_valid = _io_core_resp_valid_output;	// @[LoadController.scala:199:52]
  assign io_core_resp_bits_id = spadReqId;	// @[LoadController.scala:121:26]
  assign io_dma_req_valid = _io_dma_req_valid_output;	// @[LoadController.scala:101:45]
  assign io_dma_req_bits_addr = remote_addr;	// @[LoadController.scala:47:28]
  assign io_dma_req_bits_len = real_request_len;	// @[LoadController.scala:65:33]
  assign io_dma_req_bits_id = id;	// @[LoadController.scala:59:19]
  assign io_dma_req_bits_status_prv = status_prv;	// @[LoadController.scala:58:19]
  assign io_dma_stream_ready = _io_dma_stream_ready_output;	// @[LoadController.scala:192:45]
  assign io_dma_exp_ack = io_spad_exp_ack;
  assign io_spad_req_valid = _io_spad_req_valid_output;	// @[LoadController.scala:171:51]
  assign io_spad_req_bits_num = _spadReqQue_io_deq_bits_num;	// @[LoadController.scala:42:26]
  assign io_spad_req_bits_len = _spadReqQue_io_deq_bits_len;	// @[LoadController.scala:42:26]
  assign io_spad_exp_req = _io_spad_exp_req_output;	// @[LoadController.scala:181:33]
endmodule

