// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module lookupJ(
  input  [5:0]  io_addr,
  output [22:0] io_out
);

  wire [63:0][26:0] _GEN = '{27'h8205, 27'h8417, 27'h8636, 27'h8863, 27'h8A9D, 27'h8CE5, 27'h8F3B, 27'h91A1, 27'h9416, 27'h969B, 27'h9931, 27'h9BD8, 27'h9E91, 27'hA15C, 27'hA43B, 27'hA72D, 27'hAA33, 27'hAD4F, 27'hB081, 27'hB3CA, 27'hB72A, 27'hBAA3, 27'hBE35, 27'hC1E2, 27'hC5AA, 27'hC98F, 27'hCD92, 27'hD1B4, 27'hD5F6, 27'hDA59, 27'hDEE0, 27'hE38B, 27'hE85B, 27'hED54, 27'hF275, 27'hF7C2, 27'hFD3B, 27'h102E4, 27'h108BD, 27'h10ECA, 27'h1150D, 27'h11B88, 27'h1223E, 27'h12931, 27'h13066, 27'h137DE, 27'h13F9D, 27'h147A7, 27'h15000, 27'h158AB, 27'h161AE, 27'h16B0C, 27'h174CB, 27'h17EEF, 27'h1897F, 27'h19481, 27'h19FFA, 27'h1ABF2, 27'h1B870, 27'h1C57D, 27'h1D31F, 27'h1E162, 27'h1F04F, 27'h1FFF0};	// @[lookups.scala:206:16]
  assign io_out = _GEN[io_addr][22:0];	// @[lookups.scala:206:16]
endmodule

