// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module ReservationStation(
  input         clock,
                reset,
                io_cmd_valid,
  input  [6:0]  io_cmd_bits_inst_funct,
  input  [4:0]  io_cmd_bits_inst_rs2,
                io_cmd_bits_inst_rs1,
  input         io_cmd_bits_inst_xd,
                io_cmd_bits_inst_xs1,
                io_cmd_bits_inst_xs2,
  input  [4:0]  io_cmd_bits_inst_rd,
  input  [6:0]  io_cmd_bits_inst_opcode,
  input  [63:0] io_cmd_bits_rs1,
                io_cmd_bits_rs2,
  input         io_cmd_bits_status_debug,
                io_cmd_bits_status_cease,
                io_cmd_bits_status_wfi,
  input  [31:0] io_cmd_bits_status_isa,
  input  [1:0]  io_cmd_bits_status_dprv,
  input         io_cmd_bits_status_dv,
  input  [1:0]  io_cmd_bits_status_prv,
  input         io_cmd_bits_status_v,
                io_cmd_bits_status_sd,
  input  [22:0] io_cmd_bits_status_zero2,
  input         io_cmd_bits_status_mpv,
                io_cmd_bits_status_gva,
                io_cmd_bits_status_mbe,
                io_cmd_bits_status_sbe,
  input  [1:0]  io_cmd_bits_status_sxl,
                io_cmd_bits_status_uxl,
  input         io_cmd_bits_status_sd_rv32,
  input  [7:0]  io_cmd_bits_status_zero1,
  input         io_cmd_bits_status_tsr,
                io_cmd_bits_status_tw,
                io_cmd_bits_status_tvm,
                io_cmd_bits_status_mxr,
                io_cmd_bits_status_sum,
                io_cmd_bits_status_mprv,
  input  [1:0]  io_cmd_bits_status_xs,
                io_cmd_bits_status_fs,
                io_cmd_bits_status_mpp,
                io_cmd_bits_status_vs,
  input         io_cmd_bits_status_spp,
                io_cmd_bits_status_mpie,
                io_cmd_bits_status_ube,
                io_cmd_bits_status_spie,
                io_cmd_bits_status_upie,
                io_cmd_bits_status_mie,
                io_cmd_bits_status_hie,
                io_cmd_bits_status_sie,
                io_cmd_bits_status_uie,
                io_resp_ready,
                io_ld_req_ready,
                io_ld_resp_valid,
  input  [7:0]  io_ld_resp_bits_id,
  input         io_st_req_ready,
                io_st_resp_valid,
                io_ex_req_ready,
                io_ex_resp_valid,
  output        io_cmd_ready,
                io_resp_valid,
  output [4:0]  io_resp_bits_rd,
  output        io_ld_req_valid,
  output [63:0] io_ld_req_bits_cmd_rs1,
                io_ld_req_bits_cmd_rs2,
  output [1:0]  io_ld_req_bits_cmd_status_prv,
  output [7:0]  io_ld_req_bits_id,
  output        io_st_req_valid,
  output [63:0] io_st_req_bits_cmd_rs1,
                io_st_req_bits_cmd_rs2,
  output [1:0]  io_st_req_bits_cmd_status_prv,
  output [7:0]  io_st_req_bits_id,
  output        io_ex_req_valid,
  output [6:0]  io_ex_req_bits_cmd_inst_funct,
  output [63:0] io_ex_req_bits_cmd_rs1,
                io_ex_req_bits_cmd_rs2,
  output        io_busy,
                io_flush
);

  wire        _ex_resv_que_io_enq_ready;	// @[ReservationStation.scala:59:27]
  wire        _ex_resv_que_io_deq_valid;	// @[ReservationStation.scala:59:27]
  wire [5:0]  _ex_resv_que_io_deq_bits;	// @[ReservationStation.scala:59:27]
  wire        _st_resv_que_io_enq_ready;	// @[ReservationStation.scala:58:27]
  wire        _st_resv_que_io_deq_valid;	// @[ReservationStation.scala:58:27]
  wire [4:0]  _st_resv_que_io_deq_bits;	// @[ReservationStation.scala:58:27]
  wire        _ld_cfg_resv_que_io_enq_ready;	// @[ReservationStation.scala:57:31]
  wire        _ld_cfg_resv_que_io_deq_valid;	// @[ReservationStation.scala:57:31]
  wire [4:0]  _ld_cfg_resv_que_io_deq_bits;	// @[ReservationStation.scala:57:31]
  wire        _ld_dat_resv_que_io_enq_ready;	// @[ReservationStation.scala:56:31]
  wire        _ld_dat_resv_que_io_deq_valid;	// @[ReservationStation.scala:56:31]
  wire [4:0]  _ld_dat_resv_que_io_deq_bits;	// @[ReservationStation.scala:56:31]
  wire        _ex_cmd_que_io_enq_ready;	// @[ReservationStation.scala:54:26]
  wire        _ex_cmd_que_io_deq_valid;	// @[ReservationStation.scala:54:26]
  wire [6:0]  _ex_cmd_que_io_deq_bits_inst_funct;	// @[ReservationStation.scala:54:26]
  wire [4:0]  _ex_cmd_que_io_deq_bits_inst_rs2;	// @[ReservationStation.scala:54:26]
  wire [4:0]  _ex_cmd_que_io_deq_bits_inst_rs1;	// @[ReservationStation.scala:54:26]
  wire        _ex_cmd_que_io_deq_bits_inst_xd;	// @[ReservationStation.scala:54:26]
  wire        _ex_cmd_que_io_deq_bits_inst_xs1;	// @[ReservationStation.scala:54:26]
  wire        _ex_cmd_que_io_deq_bits_inst_xs2;	// @[ReservationStation.scala:54:26]
  wire [4:0]  _ex_cmd_que_io_deq_bits_inst_rd;	// @[ReservationStation.scala:54:26]
  wire [6:0]  _ex_cmd_que_io_deq_bits_inst_opcode;	// @[ReservationStation.scala:54:26]
  wire [63:0] _ex_cmd_que_io_deq_bits_rs2;	// @[ReservationStation.scala:54:26]
  wire        _ex_cmd_que_io_deq_bits_status_debug;	// @[ReservationStation.scala:54:26]
  wire        _ex_cmd_que_io_deq_bits_status_cease;	// @[ReservationStation.scala:54:26]
  wire        _ex_cmd_que_io_deq_bits_status_wfi;	// @[ReservationStation.scala:54:26]
  wire [31:0] _ex_cmd_que_io_deq_bits_status_isa;	// @[ReservationStation.scala:54:26]
  wire [1:0]  _ex_cmd_que_io_deq_bits_status_dprv;	// @[ReservationStation.scala:54:26]
  wire        _ex_cmd_que_io_deq_bits_status_dv;	// @[ReservationStation.scala:54:26]
  wire [1:0]  _ex_cmd_que_io_deq_bits_status_prv;	// @[ReservationStation.scala:54:26]
  wire        _ex_cmd_que_io_deq_bits_status_v;	// @[ReservationStation.scala:54:26]
  wire        _ex_cmd_que_io_deq_bits_status_sd;	// @[ReservationStation.scala:54:26]
  wire [22:0] _ex_cmd_que_io_deq_bits_status_zero2;	// @[ReservationStation.scala:54:26]
  wire        _ex_cmd_que_io_deq_bits_status_mpv;	// @[ReservationStation.scala:54:26]
  wire        _ex_cmd_que_io_deq_bits_status_gva;	// @[ReservationStation.scala:54:26]
  wire        _ex_cmd_que_io_deq_bits_status_mbe;	// @[ReservationStation.scala:54:26]
  wire        _ex_cmd_que_io_deq_bits_status_sbe;	// @[ReservationStation.scala:54:26]
  wire [1:0]  _ex_cmd_que_io_deq_bits_status_sxl;	// @[ReservationStation.scala:54:26]
  wire [1:0]  _ex_cmd_que_io_deq_bits_status_uxl;	// @[ReservationStation.scala:54:26]
  wire        _ex_cmd_que_io_deq_bits_status_sd_rv32;	// @[ReservationStation.scala:54:26]
  wire [7:0]  _ex_cmd_que_io_deq_bits_status_zero1;	// @[ReservationStation.scala:54:26]
  wire        _ex_cmd_que_io_deq_bits_status_tsr;	// @[ReservationStation.scala:54:26]
  wire        _ex_cmd_que_io_deq_bits_status_tw;	// @[ReservationStation.scala:54:26]
  wire        _ex_cmd_que_io_deq_bits_status_tvm;	// @[ReservationStation.scala:54:26]
  wire        _ex_cmd_que_io_deq_bits_status_mxr;	// @[ReservationStation.scala:54:26]
  wire        _ex_cmd_que_io_deq_bits_status_sum;	// @[ReservationStation.scala:54:26]
  wire        _ex_cmd_que_io_deq_bits_status_mprv;	// @[ReservationStation.scala:54:26]
  wire [1:0]  _ex_cmd_que_io_deq_bits_status_xs;	// @[ReservationStation.scala:54:26]
  wire [1:0]  _ex_cmd_que_io_deq_bits_status_fs;	// @[ReservationStation.scala:54:26]
  wire [1:0]  _ex_cmd_que_io_deq_bits_status_mpp;	// @[ReservationStation.scala:54:26]
  wire [1:0]  _ex_cmd_que_io_deq_bits_status_vs;	// @[ReservationStation.scala:54:26]
  wire        _ex_cmd_que_io_deq_bits_status_spp;	// @[ReservationStation.scala:54:26]
  wire        _ex_cmd_que_io_deq_bits_status_mpie;	// @[ReservationStation.scala:54:26]
  wire        _ex_cmd_que_io_deq_bits_status_ube;	// @[ReservationStation.scala:54:26]
  wire        _ex_cmd_que_io_deq_bits_status_spie;	// @[ReservationStation.scala:54:26]
  wire        _ex_cmd_que_io_deq_bits_status_upie;	// @[ReservationStation.scala:54:26]
  wire        _ex_cmd_que_io_deq_bits_status_mie;	// @[ReservationStation.scala:54:26]
  wire        _ex_cmd_que_io_deq_bits_status_hie;	// @[ReservationStation.scala:54:26]
  wire        _ex_cmd_que_io_deq_bits_status_sie;	// @[ReservationStation.scala:54:26]
  wire        _ex_cmd_que_io_deq_bits_status_uie;	// @[ReservationStation.scala:54:26]
  wire        _st_cmd_que_io_enq_ready;	// @[ReservationStation.scala:53:26]
  wire        _st_cmd_que_io_deq_valid;	// @[ReservationStation.scala:53:26]
  wire [63:0] _st_cmd_que_io_deq_bits_rs2;	// @[ReservationStation.scala:53:26]
  wire        _ld_cmd_que_io_enq_ready;	// @[ReservationStation.scala:52:26]
  wire        _ld_cmd_que_io_deq_valid;	// @[ReservationStation.scala:52:26]
  wire [63:0] _ld_cmd_que_io_deq_bits_rs2;	// @[ReservationStation.scala:52:26]
  wire        _cmd_que_io_enq_ready;	// @[ReservationStation.scala:49:23]
  wire        _cmd_que_io_deq_valid;	// @[ReservationStation.scala:49:23]
  wire [6:0]  _cmd_que_io_deq_bits_inst_funct;	// @[ReservationStation.scala:49:23]
  wire [4:0]  _cmd_que_io_deq_bits_inst_rs2;	// @[ReservationStation.scala:49:23]
  wire [4:0]  _cmd_que_io_deq_bits_inst_rs1;	// @[ReservationStation.scala:49:23]
  wire        _cmd_que_io_deq_bits_inst_xd;	// @[ReservationStation.scala:49:23]
  wire        _cmd_que_io_deq_bits_inst_xs1;	// @[ReservationStation.scala:49:23]
  wire        _cmd_que_io_deq_bits_inst_xs2;	// @[ReservationStation.scala:49:23]
  wire [4:0]  _cmd_que_io_deq_bits_inst_rd;	// @[ReservationStation.scala:49:23]
  wire [6:0]  _cmd_que_io_deq_bits_inst_opcode;	// @[ReservationStation.scala:49:23]
  wire [63:0] _cmd_que_io_deq_bits_rs1;	// @[ReservationStation.scala:49:23]
  wire [63:0] _cmd_que_io_deq_bits_rs2;	// @[ReservationStation.scala:49:23]
  wire        _cmd_que_io_deq_bits_status_debug;	// @[ReservationStation.scala:49:23]
  wire        _cmd_que_io_deq_bits_status_cease;	// @[ReservationStation.scala:49:23]
  wire        _cmd_que_io_deq_bits_status_wfi;	// @[ReservationStation.scala:49:23]
  wire [31:0] _cmd_que_io_deq_bits_status_isa;	// @[ReservationStation.scala:49:23]
  wire [1:0]  _cmd_que_io_deq_bits_status_dprv;	// @[ReservationStation.scala:49:23]
  wire        _cmd_que_io_deq_bits_status_dv;	// @[ReservationStation.scala:49:23]
  wire [1:0]  _cmd_que_io_deq_bits_status_prv;	// @[ReservationStation.scala:49:23]
  wire        _cmd_que_io_deq_bits_status_v;	// @[ReservationStation.scala:49:23]
  wire        _cmd_que_io_deq_bits_status_sd;	// @[ReservationStation.scala:49:23]
  wire [22:0] _cmd_que_io_deq_bits_status_zero2;	// @[ReservationStation.scala:49:23]
  wire        _cmd_que_io_deq_bits_status_mpv;	// @[ReservationStation.scala:49:23]
  wire        _cmd_que_io_deq_bits_status_gva;	// @[ReservationStation.scala:49:23]
  wire        _cmd_que_io_deq_bits_status_mbe;	// @[ReservationStation.scala:49:23]
  wire        _cmd_que_io_deq_bits_status_sbe;	// @[ReservationStation.scala:49:23]
  wire [1:0]  _cmd_que_io_deq_bits_status_sxl;	// @[ReservationStation.scala:49:23]
  wire [1:0]  _cmd_que_io_deq_bits_status_uxl;	// @[ReservationStation.scala:49:23]
  wire        _cmd_que_io_deq_bits_status_sd_rv32;	// @[ReservationStation.scala:49:23]
  wire [7:0]  _cmd_que_io_deq_bits_status_zero1;	// @[ReservationStation.scala:49:23]
  wire        _cmd_que_io_deq_bits_status_tsr;	// @[ReservationStation.scala:49:23]
  wire        _cmd_que_io_deq_bits_status_tw;	// @[ReservationStation.scala:49:23]
  wire        _cmd_que_io_deq_bits_status_tvm;	// @[ReservationStation.scala:49:23]
  wire        _cmd_que_io_deq_bits_status_mxr;	// @[ReservationStation.scala:49:23]
  wire        _cmd_que_io_deq_bits_status_sum;	// @[ReservationStation.scala:49:23]
  wire        _cmd_que_io_deq_bits_status_mprv;	// @[ReservationStation.scala:49:23]
  wire [1:0]  _cmd_que_io_deq_bits_status_xs;	// @[ReservationStation.scala:49:23]
  wire [1:0]  _cmd_que_io_deq_bits_status_fs;	// @[ReservationStation.scala:49:23]
  wire [1:0]  _cmd_que_io_deq_bits_status_mpp;	// @[ReservationStation.scala:49:23]
  wire [1:0]  _cmd_que_io_deq_bits_status_vs;	// @[ReservationStation.scala:49:23]
  wire        _cmd_que_io_deq_bits_status_spp;	// @[ReservationStation.scala:49:23]
  wire        _cmd_que_io_deq_bits_status_mpie;	// @[ReservationStation.scala:49:23]
  wire        _cmd_que_io_deq_bits_status_ube;	// @[ReservationStation.scala:49:23]
  wire        _cmd_que_io_deq_bits_status_spie;	// @[ReservationStation.scala:49:23]
  wire        _cmd_que_io_deq_bits_status_upie;	// @[ReservationStation.scala:49:23]
  wire        _cmd_que_io_deq_bits_status_mie;	// @[ReservationStation.scala:49:23]
  wire        _cmd_que_io_deq_bits_status_hie;	// @[ReservationStation.scala:49:23]
  wire        _cmd_que_io_deq_bits_status_sie;	// @[ReservationStation.scala:49:23]
  wire        _cmd_que_io_deq_bits_status_uie;	// @[ReservationStation.scala:49:23]
  reg  [1:0]  state;	// @[ReservationStation.scala:62:22]
  wire        isLoadCmd = _cmd_que_io_deq_bits_inst_funct == 7'h1;	// @[ReservationStation.scala:49:23, :65:26]
  wire        isCfgCmd = _cmd_que_io_deq_bits_inst_funct == 7'h3;	// @[ReservationStation.scala:49:23, :66:25]
  wire        isExeCmd = _cmd_que_io_deq_bits_inst_funct == 7'h4;	// @[ReservationStation.scala:49:23, :67:25]
  wire        isStoreCmd = _cmd_que_io_deq_bits_inst_funct == 7'h2;	// @[ReservationStation.scala:49:23, :68:27]
  reg         flush;	// @[ReservationStation.scala:71:22]
  reg  [4:0]  req_rd;	// @[ReservationStation.scala:72:19]
  reg         req_xd;	// @[ReservationStation.scala:73:23]
  reg         cmd_ready;	// @[ReservationStation.scala:74:26]
  wire        _st_cmd_que_io_enq_valid_T = cmd_ready & _cmd_que_io_deq_valid;	// @[Decoupled.scala:51:35, ReservationStation.scala:49:23, :74:26]
  reg         ld_state;	// @[ReservationStation.scala:152:25]
  reg         ex_state;	// @[ReservationStation.scala:153:25]
  reg         st_state;	// @[ReservationStation.scala:154:25]
  reg  [4:0]  last_ld_cmd_task_id;	// @[ReservationStation.scala:161:36]
  wire        ld_resv_que_ready = ~(_ld_cmd_que_io_deq_bits_rs2[55]) & _ld_dat_resv_que_io_enq_ready | _ld_cmd_que_io_deq_bits_rs2[55] & _ld_cfg_resv_que_io_enq_ready;	// @[ReservationStation.scala:52:26, :56:31, :57:31, :160:54, :164:{28,39,72,86}]
  wire        _T_20 = isLoadCmd & _ld_cmd_que_io_enq_ready | (isCfgCmd | isExeCmd) & _ex_cmd_que_io_enq_ready | isStoreCmd & _st_cmd_que_io_enq_ready;	// @[ReservationStation.scala:52:26, :53:26, :54:26, :65:26, :66:25, :67:25, :68:27, :94:31, :95:{31,44,72}, :96:32]
  wire        _T_21 = state == 2'h1;	// @[ReservationStation.scala:62:22, :80:17, :97:17]
  wire        _T_22 = state == 2'h2;	// @[ReservationStation.scala:62:22, :68:27, :80:17]
  wire        _GEN = (&state) & io_resp_ready;	// @[ReservationStation.scala:62:22, :80:17, :132:26, :133:15]
  wire        _T_43 = _ld_cmd_que_io_deq_bits_rs2[60:56] == _ex_cmd_que_io_deq_bits_rs2[60:56];	// @[ReservationStation.scala:52:26, :54:26, :155:59, :156:59, :169:30]
  wire        is_cfg_cmd = _ex_cmd_que_io_deq_bits_inst_funct == 7'h3;	// @[ReservationStation.scala:54:26, :66:25, :212:54]
  wire        _GEN_0 = ld_state & io_ld_req_ready & ld_resv_que_ready;	// @[ReservationStation.scala:152:25, :164:72, :166:19, :205:49, :206:18]
  wire        isFlushCmd = _cmd_que_io_deq_bits_inst_funct == 7'h5;	// @[ReservationStation.scala:49:23, :69:27]
  wire        _T = state == 2'h0;	// @[ReservationStation.scala:62:22, :80:17]
  wire        _T_14 = _cmd_que_io_deq_bits_inst_funct == 7'h0 & ~_ld_cmd_que_io_deq_valid & ~_ex_cmd_que_io_deq_valid & ~_st_cmd_que_io_deq_valid & ~_ld_dat_resv_que_io_deq_valid & ~_ld_cfg_resv_que_io_deq_valid & ~_ex_resv_que_io_deq_valid & ~_st_resv_que_io_deq_valid;	// @[ReservationStation.scala:49:23, :52:26, :53:26, :54:26, :56:31, :57:31, :58:27, :59:27, :70:27, :88:{34,62,90}, :89:{19,52,85,111,114}]
  always @(posedge clock) begin
    if (reset) begin
      state <= 2'h0;	// @[ReservationStation.scala:62:22]
      flush <= 1'h0;	// @[ReservationStation.scala:70:27, :71:22]
      req_xd <= 1'h0;	// @[ReservationStation.scala:70:27, :73:23]
      cmd_ready <= 1'h0;	// @[ReservationStation.scala:70:27, :74:26]
      ld_state <= 1'h0;	// @[ReservationStation.scala:70:27, :152:25]
      ex_state <= 1'h0;	// @[ReservationStation.scala:70:27, :153:25]
      st_state <= 1'h0;	// @[ReservationStation.scala:70:27, :154:25]
      last_ld_cmd_task_id <= 5'h0;	// @[ReservationStation.scala:161:36]
    end
    else begin
      if (_T) begin	// @[ReservationStation.scala:80:17]
        if (_cmd_que_io_deq_valid) begin	// @[ReservationStation.scala:49:23]
          if (isFlushCmd)	// @[ReservationStation.scala:69:27]
            state <= 2'h3;	// @[ReservationStation.scala:62:22, :66:25]
          else if (_T_14)	// @[ReservationStation.scala:89:111]
            state <= 2'h2;	// @[ReservationStation.scala:62:22, :68:27]
          else if (_T_20)	// @[ReservationStation.scala:95:72]
            state <= 2'h1;	// @[ReservationStation.scala:62:22, :97:17]
        end
        flush <= _cmd_que_io_deq_valid & isFlushCmd | flush;	// @[ReservationStation.scala:49:23, :69:27, :71:22, :82:22, :83:26, :87:17]
        cmd_ready <= _cmd_que_io_deq_valid & (isFlushCmd | _T_14 | _T_20) | cmd_ready;	// @[ReservationStation.scala:49:23, :69:27, :74:26, :82:22, :83:26, :86:21, :89:{111,140}, :93:21, :95:72, :96:60, :98:21]
      end
      else begin	// @[ReservationStation.scala:80:17]
        if (_T_21 | (_T_22 ? ~req_xd | io_resp_ready : _GEN))	// @[ReservationStation.scala:62:22, :73:23, :80:17, :117:13, :126:{12,20,37}, :127:15, :132:26, :133:15]
          state <= 2'h0;	// @[ReservationStation.scala:62:22]
        flush <= (_T_21 | _T_22 | ~_GEN) & flush;	// @[ReservationStation.scala:62:22, :71:22, :80:17, :132:26, :133:15, :134:15]
        cmd_ready <= ~(_T_21 | _T_22 | (&state)) & cmd_ready;	// @[ReservationStation.scala:62:22, :74:26, :80:17, :116:17, :125:17, :131:17]
      end
      if (~(_T & _cmd_que_io_deq_valid) | isFlushCmd | ~_T_14) begin	// @[ReservationStation.scala:49:23, :69:27, :73:23, :80:17, :82:22, :83:26, :89:{111,140}]
      end
      else	// @[ReservationStation.scala:73:23, :80:17, :82:22, :83:26]
        req_xd <= _cmd_que_io_deq_bits_inst_xd;	// @[ReservationStation.scala:49:23, :73:23]
      if (ld_state)	// @[ReservationStation.scala:152:25]
        ld_state <= ~_GEN_0 & ld_state;	// @[ReservationStation.scala:152:25, :166:19, :205:49, :206:18]
      else if (_ld_cmd_que_io_deq_valid) begin	// @[ReservationStation.scala:52:26]
        if ((_T_43 | ~_ex_cmd_que_io_deq_valid) & (_ld_cmd_que_io_deq_bits_rs2[60:56] == _st_cmd_que_io_deq_bits_rs2[60:56] | ~_st_cmd_que_io_deq_valid))	// @[ReservationStation.scala:52:26, :53:26, :54:26, :155:59, :157:59, :169:{30,49,52,78}, :170:{30,49,52}]
          ld_state <= ~((_ld_cmd_que_io_deq_bits_rs2[63:61] == 3'h3 | _ld_cmd_que_io_deq_bits_rs2[63:61] == 3'h1) & _st_resv_que_io_deq_valid | _ld_cmd_que_io_deq_bits_rs2[63:61] == 3'h2 & _ex_resv_que_io_deq_valid & (~(_ld_cmd_que_io_deq_bits_rs2[55]) | _ex_resv_que_io_deq_bits[5]));	// @[ReservationStation.scala:52:26, :58:27, :59:27, :152:25, :158:55, :160:54, :163:47, :164:28, :171:{28,52,66,95,123}, :172:22, :173:{33,85}, :174:{33,53}, :175:22, :177:22]
        else if ((_T_43 | ~_ex_cmd_que_io_deq_valid) & _ld_cmd_que_io_deq_bits_rs2[60:56] != _st_cmd_que_io_deq_bits_rs2[60:56] & _st_cmd_que_io_deq_valid & _ld_cmd_que_io_deq_bits_rs2[63:61] != 3'h3)	// @[ReservationStation.scala:52:26, :53:26, :54:26, :155:59, :157:59, :158:55, :169:{30,52}, :171:28, :179:55, :180:{36,83}, :181:32]
          ld_state <= ~(_ld_cmd_que_io_deq_bits_rs2[63:61] == 3'h1 & _st_resv_que_io_deq_valid | _ld_cmd_que_io_deq_bits_rs2[63:61] == 3'h2 & _ex_resv_que_io_deq_valid & (~(_ld_cmd_que_io_deq_bits_rs2[55]) | _ex_resv_que_io_deq_bits[5]));	// @[ReservationStation.scala:52:26, :58:27, :59:27, :152:25, :158:55, :160:54, :163:47, :164:28, :171:66, :173:33, :182:{27,55,84}, :183:22, :184:{33,85}, :185:{33,53}, :186:22, :188:22]
        else if (_ex_cmd_que_io_deq_valid & _ld_cmd_que_io_deq_bits_rs2[60:56] != _ex_cmd_que_io_deq_bits_rs2[60:56] & _st_cmd_que_io_deq_valid & _ex_cmd_que_io_deq_bits_rs2[60:56] == _st_cmd_que_io_deq_bits_rs2[60:56])	// @[ReservationStation.scala:52:26, :53:26, :54:26, :155:59, :156:59, :157:59, :190:62, :191:{44,62}]
          ld_state <= ~(_ld_cmd_que_io_deq_bits_rs2[63:61] == 3'h3 | _ld_cmd_que_io_deq_bits_rs2[63:61] == 3'h2 | _ld_cmd_que_io_deq_bits_rs2[60:56] != last_ld_cmd_task_id & _ex_cmd_que_io_deq_bits_rs2[60:56] != last_ld_cmd_task_id | _ld_cmd_que_io_deq_bits_rs2[63:61] == 3'h1 & _st_resv_que_io_deq_valid);	// @[ReservationStation.scala:52:26, :54:26, :58:27, :152:25, :155:59, :156:59, :158:55, :161:36, :171:{28,66}, :173:33, :192:{27,65,90}, :193:22, :194:{37,61,79,103}, :195:22, :196:{33,61,89}, :197:22, :199:22]
      end
      if (ex_state)	// @[ReservationStation.scala:153:25]
        ex_state <= ~(ex_state & io_ex_req_ready & _ex_resv_que_io_enq_ready) & ex_state;	// @[ReservationStation.scala:59:27, :153:25, :213:19, :228:56, :229:18]
      else if (_ex_cmd_que_io_deq_valid & (~_st_cmd_que_io_deq_valid | _ex_cmd_que_io_deq_bits_rs2[60:56] == _st_cmd_que_io_deq_bits_rs2[60:56]) & (~_ld_cmd_que_io_deq_valid | _ex_cmd_que_io_deq_bits_rs2[60:56] != _ld_cmd_que_io_deq_bits_rs2[60:56]))	// @[ReservationStation.scala:52:26, :53:26, :54:26, :155:59, :156:59, :157:59, :215:{40,65,83,103}, :216:{10,35,53}]
        ex_state <= ~(_ex_cmd_que_io_deq_bits_rs2[63:61] == 3'h1 & _st_resv_que_io_deq_valid | is_cfg_cmd & _ld_cfg_resv_que_io_deq_valid & _ex_cmd_que_io_deq_bits_rs2[60:56] == _ld_cfg_resv_que_io_deq_bits | ~is_cfg_cmd & _ld_dat_resv_que_io_deq_valid & _ex_cmd_que_io_deq_bits_rs2[60:56] == _ld_dat_resv_que_io_deq_bits);	// @[ReservationStation.scala:54:26, :56:31, :57:31, :58:27, :153:25, :156:59, :159:55, :171:66, :212:54, :217:{25,49,78}, :218:20, :219:{64,82}, :220:{12,56,74,108}, :221:20, :223:20]
      if (st_state)	// @[ReservationStation.scala:154:25]
        st_state <= ~(st_state & io_st_req_ready & _st_resv_que_io_enq_ready) & st_state;	// @[ReservationStation.scala:58:27, :154:25, :234:19, :244:56, :245:18]
      else	// @[ReservationStation.scala:154:25]
        st_state <= _st_cmd_que_io_deq_valid & (~_ex_resv_que_io_deq_valid | {1'h0, _st_cmd_que_io_deq_bits_rs2[60:56]} != _ex_resv_que_io_deq_bits) & (~_ld_cmd_que_io_deq_valid | _st_cmd_que_io_deq_bits_rs2[60:56] != _ld_cmd_que_io_deq_bits_rs2[60:56]) & (~_ex_cmd_que_io_deq_valid | _st_cmd_que_io_deq_bits_rs2[60:56] != _ex_cmd_que_io_deq_bits_rs2[60:56]) | st_state;	// @[ReservationStation.scala:52:26, :53:26, :54:26, :59:27, :70:27, :154:25, :155:59, :156:59, :157:59, :236:{40,66,84,113}, :237:{15,40,58}, :238:{15,40,58,79}, :239:20]
      if (ld_state & _GEN_0)	// @[ReservationStation.scala:152:25, :161:36, :166:19, :205:49, :206:18]
        last_ld_cmd_task_id <= _ld_cmd_que_io_deq_bits_rs2[60:56];	// @[ReservationStation.scala:52:26, :155:59, :161:36]
    end
    if (_T & _cmd_que_io_deq_valid & (isFlushCmd | _T_14))	// @[ReservationStation.scala:49:23, :69:27, :72:19, :80:17, :82:22, :83:26, :85:18, :89:{111,140}, :91:18]
      req_rd <= _cmd_que_io_deq_bits_inst_rd;	// @[ReservationStation.scala:49:23, :72:19]
  end // always @(posedge)
  Queue_68 cmd_que (	// @[ReservationStation.scala:49:23]
    .clock                      (clock),
    .reset                      (reset),
    .io_enq_valid               (io_cmd_valid),
    .io_enq_bits_inst_funct     (io_cmd_bits_inst_funct),
    .io_enq_bits_inst_rs2       (io_cmd_bits_inst_rs2),
    .io_enq_bits_inst_rs1       (io_cmd_bits_inst_rs1),
    .io_enq_bits_inst_xd        (io_cmd_bits_inst_xd),
    .io_enq_bits_inst_xs1       (io_cmd_bits_inst_xs1),
    .io_enq_bits_inst_xs2       (io_cmd_bits_inst_xs2),
    .io_enq_bits_inst_rd        (io_cmd_bits_inst_rd),
    .io_enq_bits_inst_opcode    (io_cmd_bits_inst_opcode),
    .io_enq_bits_rs1            (io_cmd_bits_rs1),
    .io_enq_bits_rs2            (io_cmd_bits_rs2),
    .io_enq_bits_status_debug   (io_cmd_bits_status_debug),
    .io_enq_bits_status_cease   (io_cmd_bits_status_cease),
    .io_enq_bits_status_wfi     (io_cmd_bits_status_wfi),
    .io_enq_bits_status_isa     (io_cmd_bits_status_isa),
    .io_enq_bits_status_dprv    (io_cmd_bits_status_dprv),
    .io_enq_bits_status_dv      (io_cmd_bits_status_dv),
    .io_enq_bits_status_prv     (io_cmd_bits_status_prv),
    .io_enq_bits_status_v       (io_cmd_bits_status_v),
    .io_enq_bits_status_sd      (io_cmd_bits_status_sd),
    .io_enq_bits_status_zero2   (io_cmd_bits_status_zero2),
    .io_enq_bits_status_mpv     (io_cmd_bits_status_mpv),
    .io_enq_bits_status_gva     (io_cmd_bits_status_gva),
    .io_enq_bits_status_mbe     (io_cmd_bits_status_mbe),
    .io_enq_bits_status_sbe     (io_cmd_bits_status_sbe),
    .io_enq_bits_status_sxl     (io_cmd_bits_status_sxl),
    .io_enq_bits_status_uxl     (io_cmd_bits_status_uxl),
    .io_enq_bits_status_sd_rv32 (io_cmd_bits_status_sd_rv32),
    .io_enq_bits_status_zero1   (io_cmd_bits_status_zero1),
    .io_enq_bits_status_tsr     (io_cmd_bits_status_tsr),
    .io_enq_bits_status_tw      (io_cmd_bits_status_tw),
    .io_enq_bits_status_tvm     (io_cmd_bits_status_tvm),
    .io_enq_bits_status_mxr     (io_cmd_bits_status_mxr),
    .io_enq_bits_status_sum     (io_cmd_bits_status_sum),
    .io_enq_bits_status_mprv    (io_cmd_bits_status_mprv),
    .io_enq_bits_status_xs      (io_cmd_bits_status_xs),
    .io_enq_bits_status_fs      (io_cmd_bits_status_fs),
    .io_enq_bits_status_mpp     (io_cmd_bits_status_mpp),
    .io_enq_bits_status_vs      (io_cmd_bits_status_vs),
    .io_enq_bits_status_spp     (io_cmd_bits_status_spp),
    .io_enq_bits_status_mpie    (io_cmd_bits_status_mpie),
    .io_enq_bits_status_ube     (io_cmd_bits_status_ube),
    .io_enq_bits_status_spie    (io_cmd_bits_status_spie),
    .io_enq_bits_status_upie    (io_cmd_bits_status_upie),
    .io_enq_bits_status_mie     (io_cmd_bits_status_mie),
    .io_enq_bits_status_hie     (io_cmd_bits_status_hie),
    .io_enq_bits_status_sie     (io_cmd_bits_status_sie),
    .io_enq_bits_status_uie     (io_cmd_bits_status_uie),
    .io_deq_ready               (cmd_ready),	// @[ReservationStation.scala:74:26]
    .io_enq_ready               (_cmd_que_io_enq_ready),
    .io_deq_valid               (_cmd_que_io_deq_valid),
    .io_deq_bits_inst_funct     (_cmd_que_io_deq_bits_inst_funct),
    .io_deq_bits_inst_rs2       (_cmd_que_io_deq_bits_inst_rs2),
    .io_deq_bits_inst_rs1       (_cmd_que_io_deq_bits_inst_rs1),
    .io_deq_bits_inst_xd        (_cmd_que_io_deq_bits_inst_xd),
    .io_deq_bits_inst_xs1       (_cmd_que_io_deq_bits_inst_xs1),
    .io_deq_bits_inst_xs2       (_cmd_que_io_deq_bits_inst_xs2),
    .io_deq_bits_inst_rd        (_cmd_que_io_deq_bits_inst_rd),
    .io_deq_bits_inst_opcode    (_cmd_que_io_deq_bits_inst_opcode),
    .io_deq_bits_rs1            (_cmd_que_io_deq_bits_rs1),
    .io_deq_bits_rs2            (_cmd_que_io_deq_bits_rs2),
    .io_deq_bits_status_debug   (_cmd_que_io_deq_bits_status_debug),
    .io_deq_bits_status_cease   (_cmd_que_io_deq_bits_status_cease),
    .io_deq_bits_status_wfi     (_cmd_que_io_deq_bits_status_wfi),
    .io_deq_bits_status_isa     (_cmd_que_io_deq_bits_status_isa),
    .io_deq_bits_status_dprv    (_cmd_que_io_deq_bits_status_dprv),
    .io_deq_bits_status_dv      (_cmd_que_io_deq_bits_status_dv),
    .io_deq_bits_status_prv     (_cmd_que_io_deq_bits_status_prv),
    .io_deq_bits_status_v       (_cmd_que_io_deq_bits_status_v),
    .io_deq_bits_status_sd      (_cmd_que_io_deq_bits_status_sd),
    .io_deq_bits_status_zero2   (_cmd_que_io_deq_bits_status_zero2),
    .io_deq_bits_status_mpv     (_cmd_que_io_deq_bits_status_mpv),
    .io_deq_bits_status_gva     (_cmd_que_io_deq_bits_status_gva),
    .io_deq_bits_status_mbe     (_cmd_que_io_deq_bits_status_mbe),
    .io_deq_bits_status_sbe     (_cmd_que_io_deq_bits_status_sbe),
    .io_deq_bits_status_sxl     (_cmd_que_io_deq_bits_status_sxl),
    .io_deq_bits_status_uxl     (_cmd_que_io_deq_bits_status_uxl),
    .io_deq_bits_status_sd_rv32 (_cmd_que_io_deq_bits_status_sd_rv32),
    .io_deq_bits_status_zero1   (_cmd_que_io_deq_bits_status_zero1),
    .io_deq_bits_status_tsr     (_cmd_que_io_deq_bits_status_tsr),
    .io_deq_bits_status_tw      (_cmd_que_io_deq_bits_status_tw),
    .io_deq_bits_status_tvm     (_cmd_que_io_deq_bits_status_tvm),
    .io_deq_bits_status_mxr     (_cmd_que_io_deq_bits_status_mxr),
    .io_deq_bits_status_sum     (_cmd_que_io_deq_bits_status_sum),
    .io_deq_bits_status_mprv    (_cmd_que_io_deq_bits_status_mprv),
    .io_deq_bits_status_xs      (_cmd_que_io_deq_bits_status_xs),
    .io_deq_bits_status_fs      (_cmd_que_io_deq_bits_status_fs),
    .io_deq_bits_status_mpp     (_cmd_que_io_deq_bits_status_mpp),
    .io_deq_bits_status_vs      (_cmd_que_io_deq_bits_status_vs),
    .io_deq_bits_status_spp     (_cmd_que_io_deq_bits_status_spp),
    .io_deq_bits_status_mpie    (_cmd_que_io_deq_bits_status_mpie),
    .io_deq_bits_status_ube     (_cmd_que_io_deq_bits_status_ube),
    .io_deq_bits_status_spie    (_cmd_que_io_deq_bits_status_spie),
    .io_deq_bits_status_upie    (_cmd_que_io_deq_bits_status_upie),
    .io_deq_bits_status_mie     (_cmd_que_io_deq_bits_status_mie),
    .io_deq_bits_status_hie     (_cmd_que_io_deq_bits_status_hie),
    .io_deq_bits_status_sie     (_cmd_que_io_deq_bits_status_sie),
    .io_deq_bits_status_uie     (_cmd_que_io_deq_bits_status_uie)
  );
  Queue_69 ld_cmd_que (	// @[ReservationStation.scala:52:26]
    .clock                      (clock),
    .reset                      (reset),
    .io_enq_valid               (_st_cmd_que_io_enq_valid_T & isLoadCmd),	// @[Decoupled.scala:51:35, ReservationStation.scala:65:26, :144:39]
    .io_enq_bits_inst_funct     (_cmd_que_io_deq_bits_inst_funct),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_inst_rs2       (_cmd_que_io_deq_bits_inst_rs2),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_inst_rs1       (_cmd_que_io_deq_bits_inst_rs1),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_inst_xd        (_cmd_que_io_deq_bits_inst_xd),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_inst_xs1       (_cmd_que_io_deq_bits_inst_xs1),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_inst_xs2       (_cmd_que_io_deq_bits_inst_xs2),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_inst_rd        (_cmd_que_io_deq_bits_inst_rd),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_inst_opcode    (_cmd_que_io_deq_bits_inst_opcode),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_rs1            (_cmd_que_io_deq_bits_rs1),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_rs2            (_cmd_que_io_deq_bits_rs2),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_debug   (_cmd_que_io_deq_bits_status_debug),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_cease   (_cmd_que_io_deq_bits_status_cease),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_wfi     (_cmd_que_io_deq_bits_status_wfi),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_isa     (_cmd_que_io_deq_bits_status_isa),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_dprv    (_cmd_que_io_deq_bits_status_dprv),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_dv      (_cmd_que_io_deq_bits_status_dv),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_prv     (_cmd_que_io_deq_bits_status_prv),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_v       (_cmd_que_io_deq_bits_status_v),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_sd      (_cmd_que_io_deq_bits_status_sd),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_zero2   (_cmd_que_io_deq_bits_status_zero2),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_mpv     (_cmd_que_io_deq_bits_status_mpv),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_gva     (_cmd_que_io_deq_bits_status_gva),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_mbe     (_cmd_que_io_deq_bits_status_mbe),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_sbe     (_cmd_que_io_deq_bits_status_sbe),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_sxl     (_cmd_que_io_deq_bits_status_sxl),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_uxl     (_cmd_que_io_deq_bits_status_uxl),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_sd_rv32 (_cmd_que_io_deq_bits_status_sd_rv32),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_zero1   (_cmd_que_io_deq_bits_status_zero1),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_tsr     (_cmd_que_io_deq_bits_status_tsr),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_tw      (_cmd_que_io_deq_bits_status_tw),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_tvm     (_cmd_que_io_deq_bits_status_tvm),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_mxr     (_cmd_que_io_deq_bits_status_mxr),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_sum     (_cmd_que_io_deq_bits_status_sum),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_mprv    (_cmd_que_io_deq_bits_status_mprv),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_xs      (_cmd_que_io_deq_bits_status_xs),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_fs      (_cmd_que_io_deq_bits_status_fs),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_mpp     (_cmd_que_io_deq_bits_status_mpp),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_vs      (_cmd_que_io_deq_bits_status_vs),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_spp     (_cmd_que_io_deq_bits_status_spp),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_mpie    (_cmd_que_io_deq_bits_status_mpie),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_ube     (_cmd_que_io_deq_bits_status_ube),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_spie    (_cmd_que_io_deq_bits_status_spie),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_upie    (_cmd_que_io_deq_bits_status_upie),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_mie     (_cmd_que_io_deq_bits_status_mie),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_hie     (_cmd_que_io_deq_bits_status_hie),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_sie     (_cmd_que_io_deq_bits_status_sie),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_uie     (_cmd_que_io_deq_bits_status_uie),	// @[ReservationStation.scala:49:23]
    .io_deq_ready               (ld_state & io_ld_req_ready & ld_resv_que_ready),	// @[ReservationStation.scala:152:25, :164:72, :250:72]
    .io_enq_ready               (_ld_cmd_que_io_enq_ready),
    .io_deq_valid               (_ld_cmd_que_io_deq_valid),
    .io_deq_bits_rs1            (io_ld_req_bits_cmd_rs1),
    .io_deq_bits_rs2            (_ld_cmd_que_io_deq_bits_rs2),
    .io_deq_bits_status_prv     (io_ld_req_bits_cmd_status_prv)
  );
  Queue_69 st_cmd_que (	// @[ReservationStation.scala:53:26]
    .clock                      (clock),
    .reset                      (reset),
    .io_enq_valid               (_st_cmd_que_io_enq_valid_T & isStoreCmd),	// @[Decoupled.scala:51:35, ReservationStation.scala:68:27, :148:39]
    .io_enq_bits_inst_funct     (_cmd_que_io_deq_bits_inst_funct),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_inst_rs2       (_cmd_que_io_deq_bits_inst_rs2),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_inst_rs1       (_cmd_que_io_deq_bits_inst_rs1),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_inst_xd        (_cmd_que_io_deq_bits_inst_xd),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_inst_xs1       (_cmd_que_io_deq_bits_inst_xs1),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_inst_xs2       (_cmd_que_io_deq_bits_inst_xs2),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_inst_rd        (_cmd_que_io_deq_bits_inst_rd),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_inst_opcode    (_cmd_que_io_deq_bits_inst_opcode),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_rs1            (_cmd_que_io_deq_bits_rs1),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_rs2            (_cmd_que_io_deq_bits_rs2),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_debug   (_cmd_que_io_deq_bits_status_debug),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_cease   (_cmd_que_io_deq_bits_status_cease),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_wfi     (_cmd_que_io_deq_bits_status_wfi),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_isa     (_cmd_que_io_deq_bits_status_isa),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_dprv    (_cmd_que_io_deq_bits_status_dprv),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_dv      (_cmd_que_io_deq_bits_status_dv),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_prv     (_cmd_que_io_deq_bits_status_prv),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_v       (_cmd_que_io_deq_bits_status_v),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_sd      (_cmd_que_io_deq_bits_status_sd),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_zero2   (_cmd_que_io_deq_bits_status_zero2),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_mpv     (_cmd_que_io_deq_bits_status_mpv),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_gva     (_cmd_que_io_deq_bits_status_gva),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_mbe     (_cmd_que_io_deq_bits_status_mbe),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_sbe     (_cmd_que_io_deq_bits_status_sbe),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_sxl     (_cmd_que_io_deq_bits_status_sxl),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_uxl     (_cmd_que_io_deq_bits_status_uxl),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_sd_rv32 (_cmd_que_io_deq_bits_status_sd_rv32),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_zero1   (_cmd_que_io_deq_bits_status_zero1),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_tsr     (_cmd_que_io_deq_bits_status_tsr),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_tw      (_cmd_que_io_deq_bits_status_tw),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_tvm     (_cmd_que_io_deq_bits_status_tvm),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_mxr     (_cmd_que_io_deq_bits_status_mxr),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_sum     (_cmd_que_io_deq_bits_status_sum),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_mprv    (_cmd_que_io_deq_bits_status_mprv),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_xs      (_cmd_que_io_deq_bits_status_xs),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_fs      (_cmd_que_io_deq_bits_status_fs),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_mpp     (_cmd_que_io_deq_bits_status_mpp),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_vs      (_cmd_que_io_deq_bits_status_vs),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_spp     (_cmd_que_io_deq_bits_status_spp),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_mpie    (_cmd_que_io_deq_bits_status_mpie),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_ube     (_cmd_que_io_deq_bits_status_ube),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_spie    (_cmd_que_io_deq_bits_status_spie),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_upie    (_cmd_que_io_deq_bits_status_upie),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_mie     (_cmd_que_io_deq_bits_status_mie),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_hie     (_cmd_que_io_deq_bits_status_hie),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_sie     (_cmd_que_io_deq_bits_status_sie),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_uie     (_cmd_que_io_deq_bits_status_uie),	// @[ReservationStation.scala:49:23]
    .io_deq_ready               (st_state & io_st_req_ready & _st_resv_que_io_enq_ready),	// @[ReservationStation.scala:58:27, :154:25, :272:72]
    .io_enq_ready               (_st_cmd_que_io_enq_ready),
    .io_deq_valid               (_st_cmd_que_io_deq_valid),
    .io_deq_bits_rs1            (io_st_req_bits_cmd_rs1),
    .io_deq_bits_rs2            (_st_cmd_que_io_deq_bits_rs2),
    .io_deq_bits_status_prv     (io_st_req_bits_cmd_status_prv)
  );
  Queue_68 ex_cmd_que (	// @[ReservationStation.scala:54:26]
    .clock                      (clock),
    .reset                      (reset),
    .io_enq_valid               (_st_cmd_que_io_enq_valid_T & (isCfgCmd | isExeCmd)),	// @[Decoupled.scala:51:35, ReservationStation.scala:66:25, :67:25, :146:{39,52}]
    .io_enq_bits_inst_funct     (_cmd_que_io_deq_bits_inst_funct),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_inst_rs2       (_cmd_que_io_deq_bits_inst_rs2),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_inst_rs1       (_cmd_que_io_deq_bits_inst_rs1),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_inst_xd        (_cmd_que_io_deq_bits_inst_xd),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_inst_xs1       (_cmd_que_io_deq_bits_inst_xs1),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_inst_xs2       (_cmd_que_io_deq_bits_inst_xs2),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_inst_rd        (_cmd_que_io_deq_bits_inst_rd),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_inst_opcode    (_cmd_que_io_deq_bits_inst_opcode),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_rs1            (_cmd_que_io_deq_bits_rs1),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_rs2            (_cmd_que_io_deq_bits_rs2),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_debug   (_cmd_que_io_deq_bits_status_debug),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_cease   (_cmd_que_io_deq_bits_status_cease),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_wfi     (_cmd_que_io_deq_bits_status_wfi),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_isa     (_cmd_que_io_deq_bits_status_isa),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_dprv    (_cmd_que_io_deq_bits_status_dprv),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_dv      (_cmd_que_io_deq_bits_status_dv),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_prv     (_cmd_que_io_deq_bits_status_prv),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_v       (_cmd_que_io_deq_bits_status_v),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_sd      (_cmd_que_io_deq_bits_status_sd),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_zero2   (_cmd_que_io_deq_bits_status_zero2),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_mpv     (_cmd_que_io_deq_bits_status_mpv),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_gva     (_cmd_que_io_deq_bits_status_gva),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_mbe     (_cmd_que_io_deq_bits_status_mbe),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_sbe     (_cmd_que_io_deq_bits_status_sbe),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_sxl     (_cmd_que_io_deq_bits_status_sxl),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_uxl     (_cmd_que_io_deq_bits_status_uxl),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_sd_rv32 (_cmd_que_io_deq_bits_status_sd_rv32),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_zero1   (_cmd_que_io_deq_bits_status_zero1),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_tsr     (_cmd_que_io_deq_bits_status_tsr),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_tw      (_cmd_que_io_deq_bits_status_tw),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_tvm     (_cmd_que_io_deq_bits_status_tvm),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_mxr     (_cmd_que_io_deq_bits_status_mxr),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_sum     (_cmd_que_io_deq_bits_status_sum),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_mprv    (_cmd_que_io_deq_bits_status_mprv),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_xs      (_cmd_que_io_deq_bits_status_xs),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_fs      (_cmd_que_io_deq_bits_status_fs),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_mpp     (_cmd_que_io_deq_bits_status_mpp),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_vs      (_cmd_que_io_deq_bits_status_vs),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_spp     (_cmd_que_io_deq_bits_status_spp),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_mpie    (_cmd_que_io_deq_bits_status_mpie),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_ube     (_cmd_que_io_deq_bits_status_ube),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_spie    (_cmd_que_io_deq_bits_status_spie),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_upie    (_cmd_que_io_deq_bits_status_upie),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_mie     (_cmd_que_io_deq_bits_status_mie),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_hie     (_cmd_que_io_deq_bits_status_hie),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_sie     (_cmd_que_io_deq_bits_status_sie),	// @[ReservationStation.scala:49:23]
    .io_enq_bits_status_uie     (_cmd_que_io_deq_bits_status_uie),	// @[ReservationStation.scala:49:23]
    .io_deq_ready               (ex_state & io_ex_req_ready & _ex_resv_que_io_enq_ready),	// @[ReservationStation.scala:59:27, :153:25, :263:72]
    .io_enq_ready               (_ex_cmd_que_io_enq_ready),
    .io_deq_valid               (_ex_cmd_que_io_deq_valid),
    .io_deq_bits_inst_funct     (_ex_cmd_que_io_deq_bits_inst_funct),
    .io_deq_bits_inst_rs2       (_ex_cmd_que_io_deq_bits_inst_rs2),
    .io_deq_bits_inst_rs1       (_ex_cmd_que_io_deq_bits_inst_rs1),
    .io_deq_bits_inst_xd        (_ex_cmd_que_io_deq_bits_inst_xd),
    .io_deq_bits_inst_xs1       (_ex_cmd_que_io_deq_bits_inst_xs1),
    .io_deq_bits_inst_xs2       (_ex_cmd_que_io_deq_bits_inst_xs2),
    .io_deq_bits_inst_rd        (_ex_cmd_que_io_deq_bits_inst_rd),
    .io_deq_bits_inst_opcode    (_ex_cmd_que_io_deq_bits_inst_opcode),
    .io_deq_bits_rs1            (io_ex_req_bits_cmd_rs1),
    .io_deq_bits_rs2            (_ex_cmd_que_io_deq_bits_rs2),
    .io_deq_bits_status_debug   (_ex_cmd_que_io_deq_bits_status_debug),
    .io_deq_bits_status_cease   (_ex_cmd_que_io_deq_bits_status_cease),
    .io_deq_bits_status_wfi     (_ex_cmd_que_io_deq_bits_status_wfi),
    .io_deq_bits_status_isa     (_ex_cmd_que_io_deq_bits_status_isa),
    .io_deq_bits_status_dprv    (_ex_cmd_que_io_deq_bits_status_dprv),
    .io_deq_bits_status_dv      (_ex_cmd_que_io_deq_bits_status_dv),
    .io_deq_bits_status_prv     (_ex_cmd_que_io_deq_bits_status_prv),
    .io_deq_bits_status_v       (_ex_cmd_que_io_deq_bits_status_v),
    .io_deq_bits_status_sd      (_ex_cmd_que_io_deq_bits_status_sd),
    .io_deq_bits_status_zero2   (_ex_cmd_que_io_deq_bits_status_zero2),
    .io_deq_bits_status_mpv     (_ex_cmd_que_io_deq_bits_status_mpv),
    .io_deq_bits_status_gva     (_ex_cmd_que_io_deq_bits_status_gva),
    .io_deq_bits_status_mbe     (_ex_cmd_que_io_deq_bits_status_mbe),
    .io_deq_bits_status_sbe     (_ex_cmd_que_io_deq_bits_status_sbe),
    .io_deq_bits_status_sxl     (_ex_cmd_que_io_deq_bits_status_sxl),
    .io_deq_bits_status_uxl     (_ex_cmd_que_io_deq_bits_status_uxl),
    .io_deq_bits_status_sd_rv32 (_ex_cmd_que_io_deq_bits_status_sd_rv32),
    .io_deq_bits_status_zero1   (_ex_cmd_que_io_deq_bits_status_zero1),
    .io_deq_bits_status_tsr     (_ex_cmd_que_io_deq_bits_status_tsr),
    .io_deq_bits_status_tw      (_ex_cmd_que_io_deq_bits_status_tw),
    .io_deq_bits_status_tvm     (_ex_cmd_que_io_deq_bits_status_tvm),
    .io_deq_bits_status_mxr     (_ex_cmd_que_io_deq_bits_status_mxr),
    .io_deq_bits_status_sum     (_ex_cmd_que_io_deq_bits_status_sum),
    .io_deq_bits_status_mprv    (_ex_cmd_que_io_deq_bits_status_mprv),
    .io_deq_bits_status_xs      (_ex_cmd_que_io_deq_bits_status_xs),
    .io_deq_bits_status_fs      (_ex_cmd_que_io_deq_bits_status_fs),
    .io_deq_bits_status_mpp     (_ex_cmd_que_io_deq_bits_status_mpp),
    .io_deq_bits_status_vs      (_ex_cmd_que_io_deq_bits_status_vs),
    .io_deq_bits_status_spp     (_ex_cmd_que_io_deq_bits_status_spp),
    .io_deq_bits_status_mpie    (_ex_cmd_que_io_deq_bits_status_mpie),
    .io_deq_bits_status_ube     (_ex_cmd_que_io_deq_bits_status_ube),
    .io_deq_bits_status_spie    (_ex_cmd_que_io_deq_bits_status_spie),
    .io_deq_bits_status_upie    (_ex_cmd_que_io_deq_bits_status_upie),
    .io_deq_bits_status_mie     (_ex_cmd_que_io_deq_bits_status_mie),
    .io_deq_bits_status_hie     (_ex_cmd_que_io_deq_bits_status_hie),
    .io_deq_bits_status_sie     (_ex_cmd_que_io_deq_bits_status_sie),
    .io_deq_bits_status_uie     (_ex_cmd_que_io_deq_bits_status_uie)
  );
  Queue_72 ld_dat_resv_que (	// @[ReservationStation.scala:56:31]
    .clock        (clock),
    .reset        (reset),
    .io_enq_valid (ld_state & io_ld_req_ready & ~(_ld_cmd_que_io_deq_bits_rs2[55])),	// @[ReservationStation.scala:52:26, :152:25, :160:54, :164:28, :251:77]
    .io_enq_bits  (_ld_cmd_que_io_deq_bits_rs2[60:56]),	// @[ReservationStation.scala:52:26, :155:59]
    .io_deq_ready (io_ld_resp_valid & ~(io_ld_resp_bits_id[5])),	// @[ReservationStation.scala:259:{51,55,74}]
    .io_enq_ready (_ld_dat_resv_que_io_enq_ready),
    .io_deq_valid (_ld_dat_resv_que_io_deq_valid),
    .io_deq_bits  (_ld_dat_resv_que_io_deq_bits)
  );
  Queue_73 ld_cfg_resv_que (	// @[ReservationStation.scala:57:31]
    .clock        (clock),
    .reset        (reset),
    .io_enq_valid (ld_state & io_ld_req_ready & _ld_cmd_que_io_deq_bits_rs2[55]),	// @[ReservationStation.scala:52:26, :152:25, :160:54, :253:77]
    .io_enq_bits  (_ld_cmd_que_io_deq_bits_rs2[60:56]),	// @[ReservationStation.scala:52:26, :155:59]
    .io_deq_ready (io_ld_resp_valid & io_ld_resp_bits_id[5]),	// @[ReservationStation.scala:259:74, :260:51]
    .io_enq_ready (_ld_cfg_resv_que_io_enq_ready),
    .io_deq_valid (_ld_cfg_resv_que_io_deq_valid),
    .io_deq_bits  (_ld_cfg_resv_que_io_deq_bits)
  );
  Queue_72 st_resv_que (	// @[ReservationStation.scala:58:27]
    .clock        (clock),
    .reset        (reset),
    .io_enq_valid (st_state & io_st_req_ready),	// @[ReservationStation.scala:154:25, :273:54]
    .io_enq_bits  (_st_cmd_que_io_deq_bits_rs2[60:56]),	// @[ReservationStation.scala:53:26, :157:59]
    .io_deq_ready (io_st_resp_valid),
    .io_enq_ready (_st_resv_que_io_enq_ready),
    .io_deq_valid (_st_resv_que_io_deq_valid),
    .io_deq_bits  (_st_resv_que_io_deq_bits)
  );
  Queue_75 ex_resv_que (	// @[ReservationStation.scala:59:27]
    .clock        (clock),
    .reset        (reset),
    .io_enq_valid (ex_state & io_ex_req_ready),	// @[ReservationStation.scala:153:25, :264:54]
    .io_enq_bits  ({1'h0, _ex_cmd_que_io_deq_bits_rs2[60:56]}),	// @[ReservationStation.scala:54:26, :70:27, :156:59, :265:27]
    .io_deq_ready (io_ex_resp_valid),
    .io_enq_ready (_ex_resv_que_io_enq_ready),
    .io_deq_valid (_ex_resv_que_io_deq_valid),
    .io_deq_bits  (_ex_resv_que_io_deq_bits)
  );
  assign io_cmd_ready = _cmd_que_io_enq_ready;	// @[ReservationStation.scala:49:23]
  assign io_resp_valid = (&state) | state == 2'h2 & req_xd;	// @[ReservationStation.scala:62:22, :68:27, :73:23, :139:{27,40,50,62}]
  assign io_resp_bits_rd = req_rd;	// @[ReservationStation.scala:72:19]
  assign io_ld_req_valid = ld_state & ld_resv_que_ready;	// @[ReservationStation.scala:152:25, :164:72, :255:45]
  assign io_ld_req_bits_cmd_rs2 = _ld_cmd_que_io_deq_bits_rs2;	// @[ReservationStation.scala:52:26]
  assign io_ld_req_bits_id = {2'h0, _ld_cmd_que_io_deq_bits_rs2[55], _ld_cmd_que_io_deq_bits_rs2[60:56]};	// @[ReservationStation.scala:52:26, :62:22, :155:59, :160:54, :257:21]
  assign io_st_req_valid = st_state & _st_resv_que_io_enq_ready;	// @[ReservationStation.scala:58:27, :154:25, :275:45]
  assign io_st_req_bits_cmd_rs2 = _st_cmd_que_io_deq_bits_rs2;	// @[ReservationStation.scala:53:26]
  assign io_st_req_bits_id = {3'h0, _st_cmd_que_io_deq_bits_rs2[60:56]};	// @[ReservationStation.scala:53:26, :157:59, :277:21]
  assign io_ex_req_valid = ex_state & _ex_resv_que_io_enq_ready;	// @[ReservationStation.scala:59:27, :153:25, :266:45]
  assign io_ex_req_bits_cmd_inst_funct = _ex_cmd_que_io_deq_bits_inst_funct;	// @[ReservationStation.scala:54:26]
  assign io_ex_req_bits_cmd_rs2 = _ex_cmd_que_io_deq_bits_rs2;	// @[ReservationStation.scala:54:26]
  assign io_busy = ~_cmd_que_io_enq_ready;	// @[ReservationStation.scala:49:23, :78:14]
  assign io_flush = flush;	// @[ReservationStation.scala:71:22]
endmodule

