// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module SharedDelayPipe(
  input         clock,
                reset,
                io_en,
  input  [3:0]  io_config,
  input  [31:0] io_in_0,
                io_in_1,
  output [31:0] io_out_0,
                io_out_1
);

  reg [31:0] regs_0;	// @[DelayPipe.scala:80:25]
  reg [31:0] regs_1;	// @[DelayPipe.scala:80:25]
  reg [31:0] regs_2;	// @[DelayPipe.scala:80:25]
  reg [31:0] regs_3;	// @[DelayPipe.scala:80:25]
  reg [1:0]  wptr_0;	// @[DelayPipe.scala:81:25]
  reg [1:0]  wptr_1;	// @[DelayPipe.scala:81:25]
  reg [1:0]  rptr_0;	// @[DelayPipe.scala:82:25]
  reg [1:0]  rptr_1;	// @[DelayPipe.scala:82:25]
  always @(posedge clock) begin
    if (reset) begin
      regs_0 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
      regs_1 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
      regs_2 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
      regs_3 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
      wptr_0 <= 2'h0;	// @[DelayPipe.scala:81:{25,33}]
      wptr_1 <= 2'h0;	// @[DelayPipe.scala:81:{25,33}]
      rptr_0 <= 2'h0;	// @[DelayPipe.scala:81:33, :82:25]
      rptr_1 <= 2'h0;	// @[DelayPipe.scala:81:33, :82:25]
    end
    else begin
      if (io_en) begin
        if (wptr_1 == 2'h0)	// @[DelayPipe.scala:81:{25,33}, :127:51]
          regs_0 <= io_in_1;	// @[DelayPipe.scala:80:25]
        else if (wptr_0 == 2'h0)	// @[DelayPipe.scala:81:{25,33}, :127:51]
          regs_0 <= io_in_0;	// @[DelayPipe.scala:80:25]
        if (wptr_1 == 2'h1)	// @[DelayPipe.scala:81:25, :127:51]
          regs_1 <= io_in_1;	// @[DelayPipe.scala:80:25]
        else if (wptr_0 == 2'h1)	// @[DelayPipe.scala:81:25, :127:51]
          regs_1 <= io_in_0;	// @[DelayPipe.scala:80:25]
        if (wptr_1 == 2'h2)	// @[DelayPipe.scala:81:25, :127:51]
          regs_2 <= io_in_1;	// @[DelayPipe.scala:80:25]
        else if (wptr_0 == 2'h2)	// @[DelayPipe.scala:81:25, :127:51]
          regs_2 <= io_in_0;	// @[DelayPipe.scala:80:25]
        if (&wptr_1)	// @[DelayPipe.scala:81:25, :127:51]
          regs_3 <= io_in_1;	// @[DelayPipe.scala:80:25]
        else if (&wptr_0)	// @[DelayPipe.scala:81:25, :127:51]
          regs_3 <= io_in_0;	// @[DelayPipe.scala:80:25]
        if (&wptr_1)	// @[DelayPipe.scala:81:25, :101:13]
          wptr_1 <= 2'h0;	// @[DelayPipe.scala:81:{25,33}]
        else	// @[DelayPipe.scala:101:13]
          wptr_1 <= wptr_1 + 2'h1;	// @[DelayPipe.scala:81:25, :101:37, :127:51]
        if (&rptr_0)	// @[DelayPipe.scala:82:25, :101:13]
          rptr_0 <= 2'h0;	// @[DelayPipe.scala:81:33, :82:25]
        else	// @[DelayPipe.scala:101:13]
          rptr_0 <= rptr_0 + 2'h1;	// @[DelayPipe.scala:82:25, :101:37, :127:51]
        if (&rptr_1)	// @[DelayPipe.scala:82:25, :101:13]
          rptr_1 <= 2'h0;	// @[DelayPipe.scala:81:33, :82:25]
        else	// @[DelayPipe.scala:101:13]
          rptr_1 <= rptr_1 + 2'h1;	// @[DelayPipe.scala:82:25, :101:37, :127:51]
      end
      else begin
        regs_0 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
        regs_1 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
        regs_2 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
        regs_3 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
        wptr_1 <= io_config[3:2] + 2'h1;	// @[DelayPipe.scala:81:25, :87:24, :93:25, :127:51]
        rptr_0 <= wptr_0 - io_config[1:0];	// @[DelayPipe.scala:81:25, :82:25, :87:24, :104:19]
        rptr_1 <= wptr_1 - io_config[3:2];	// @[DelayPipe.scala:81:25, :82:25, :87:24, :104:19]
      end
      if (~io_en | (&wptr_0))	// @[DelayPipe.scala:81:25, :101:13, :112:18, :114:15, :118:15]
        wptr_0 <= 2'h0;	// @[DelayPipe.scala:81:{25,33}]
      else	// @[DelayPipe.scala:112:18, :114:15, :118:15]
        wptr_0 <= wptr_0 + 2'h1;	// @[DelayPipe.scala:81:25, :101:37, :127:51]
    end
  end // always @(posedge)
  assign io_out_0 = io_en ? (io_config[1:0] == 2'h0 ? io_in_0 : (rptr_0 == 2'h0 ? regs_0 : 32'h0) | (rptr_0 == 2'h1 ? regs_1 : 32'h0) | (rptr_0 == 2'h2 ? regs_2 : 32'h0) | ((&rptr_0) ? regs_3 : 32'h0)) : 32'h0;	// @[DelayPipe.scala:80:{25,33}, :81:33, :82:25, :87:24, :127:51, :136:{10,19}, :137:16, :138:{21,32,40}]
  assign io_out_1 = io_en ? (io_config[3:2] == 2'h0 ? io_in_1 : (rptr_1 == 2'h0 ? regs_0 : 32'h0) | (rptr_1 == 2'h1 ? regs_1 : 32'h0) | (rptr_1 == 2'h2 ? regs_2 : 32'h0) | ((&rptr_1) ? regs_3 : 32'h0)) : 32'h0;	// @[DelayPipe.scala:80:{25,33}, :81:33, :82:25, :87:24, :127:51, :136:{10,19}, :137:16, :138:{21,32,40}]
endmodule

