// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module SharedDelayPipe_24(
  input         clock,
                reset,
                io_en,
  input  [9:0]  io_config,
  input  [31:0] io_in_0,
                io_in_1,
  output [31:0] io_out_0,
                io_out_1
);

  reg  [31:0] regs_0;	// @[DelayPipe.scala:80:25]
  reg  [31:0] regs_1;	// @[DelayPipe.scala:80:25]
  reg  [31:0] regs_2;	// @[DelayPipe.scala:80:25]
  reg  [31:0] regs_3;	// @[DelayPipe.scala:80:25]
  reg  [31:0] regs_4;	// @[DelayPipe.scala:80:25]
  reg  [31:0] regs_5;	// @[DelayPipe.scala:80:25]
  reg  [31:0] regs_6;	// @[DelayPipe.scala:80:25]
  reg  [31:0] regs_7;	// @[DelayPipe.scala:80:25]
  reg  [31:0] regs_8;	// @[DelayPipe.scala:80:25]
  reg  [31:0] regs_9;	// @[DelayPipe.scala:80:25]
  reg  [31:0] regs_10;	// @[DelayPipe.scala:80:25]
  reg  [31:0] regs_11;	// @[DelayPipe.scala:80:25]
  reg  [31:0] regs_12;	// @[DelayPipe.scala:80:25]
  reg  [31:0] regs_13;	// @[DelayPipe.scala:80:25]
  reg  [31:0] regs_14;	// @[DelayPipe.scala:80:25]
  reg  [31:0] regs_15;	// @[DelayPipe.scala:80:25]
  reg  [31:0] regs_16;	// @[DelayPipe.scala:80:25]
  reg  [31:0] regs_17;	// @[DelayPipe.scala:80:25]
  reg  [4:0]  wptr_0;	// @[DelayPipe.scala:81:25]
  reg  [4:0]  wptr_1;	// @[DelayPipe.scala:81:25]
  reg  [4:0]  rptr_0;	// @[DelayPipe.scala:82:25]
  reg  [4:0]  rptr_1;	// @[DelayPipe.scala:82:25]
  wire        _T = wptr_0 < 5'h12;	// @[DelayPipe.scala:81:25, :103:62, :127:22]
  wire        _T_1 = wptr_1 < 5'h12;	// @[DelayPipe.scala:81:25, :103:62, :127:22]
  wire [5:0]  _rptr_0_diff_T_1 = {1'h0, wptr_0} - {1'h0, io_config[4:0]};	// @[DelayPipe.scala:81:25, :87:24, :104:19, :105:14]
  wire [5:0]  _rptr_1_diff_T_1 = {1'h0, wptr_1} - {1'h0, io_config[9:5]};	// @[DelayPipe.scala:81:25, :87:24, :104:19, :105:14]
  always @(posedge clock) begin
    if (reset) begin
      regs_0 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
      regs_1 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
      regs_2 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
      regs_3 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
      regs_4 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
      regs_5 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
      regs_6 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
      regs_7 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
      regs_8 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
      regs_9 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
      regs_10 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
      regs_11 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
      regs_12 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
      regs_13 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
      regs_14 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
      regs_15 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
      regs_16 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
      regs_17 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
      wptr_0 <= 5'h0;	// @[DelayPipe.scala:81:{25,33}]
      wptr_1 <= 5'h0;	// @[DelayPipe.scala:81:{25,33}]
      rptr_0 <= 5'h0;	// @[DelayPipe.scala:81:33, :82:25]
      rptr_1 <= 5'h0;	// @[DelayPipe.scala:81:33, :82:25]
    end
    else begin
      if (io_en) begin
        if (_T_1 & wptr_1 == 5'h0)	// @[DelayPipe.scala:81:{25,33}, :127:{22,34,51}]
          regs_0 <= io_in_1;	// @[DelayPipe.scala:80:25]
        else if (_T & wptr_0 == 5'h0)	// @[DelayPipe.scala:80:25, :81:{25,33}, :127:{22,34,51}]
          regs_0 <= io_in_0;	// @[DelayPipe.scala:80:25]
        if (_T_1 & wptr_1 == 5'h1)	// @[DelayPipe.scala:81:25, :127:{22,34,51}]
          regs_1 <= io_in_1;	// @[DelayPipe.scala:80:25]
        else if (_T & wptr_0 == 5'h1)	// @[DelayPipe.scala:80:25, :81:25, :127:{22,34,51}]
          regs_1 <= io_in_0;	// @[DelayPipe.scala:80:25]
        if (_T_1 & wptr_1 == 5'h2)	// @[DelayPipe.scala:81:25, :127:{22,34,51}]
          regs_2 <= io_in_1;	// @[DelayPipe.scala:80:25]
        else if (_T & wptr_0 == 5'h2)	// @[DelayPipe.scala:80:25, :81:25, :127:{22,34,51}]
          regs_2 <= io_in_0;	// @[DelayPipe.scala:80:25]
        if (_T_1 & wptr_1 == 5'h3)	// @[DelayPipe.scala:81:25, :127:{22,34,51}]
          regs_3 <= io_in_1;	// @[DelayPipe.scala:80:25]
        else if (_T & wptr_0 == 5'h3)	// @[DelayPipe.scala:80:25, :81:25, :127:{22,34,51}]
          regs_3 <= io_in_0;	// @[DelayPipe.scala:80:25]
        if (_T_1 & wptr_1 == 5'h4)	// @[DelayPipe.scala:81:25, :127:{22,34,51}]
          regs_4 <= io_in_1;	// @[DelayPipe.scala:80:25]
        else if (_T & wptr_0 == 5'h4)	// @[DelayPipe.scala:80:25, :81:25, :127:{22,34,51}]
          regs_4 <= io_in_0;	// @[DelayPipe.scala:80:25]
        if (_T_1 & wptr_1 == 5'h5)	// @[DelayPipe.scala:81:25, :127:{22,34,51}]
          regs_5 <= io_in_1;	// @[DelayPipe.scala:80:25]
        else if (_T & wptr_0 == 5'h5)	// @[DelayPipe.scala:80:25, :81:25, :127:{22,34,51}]
          regs_5 <= io_in_0;	// @[DelayPipe.scala:80:25]
        if (_T_1 & wptr_1 == 5'h6)	// @[DelayPipe.scala:81:25, :127:{22,34,51}]
          regs_6 <= io_in_1;	// @[DelayPipe.scala:80:25]
        else if (_T & wptr_0 == 5'h6)	// @[DelayPipe.scala:80:25, :81:25, :127:{22,34,51}]
          regs_6 <= io_in_0;	// @[DelayPipe.scala:80:25]
        if (_T_1 & wptr_1 == 5'h7)	// @[DelayPipe.scala:81:25, :127:{22,34,51}]
          regs_7 <= io_in_1;	// @[DelayPipe.scala:80:25]
        else if (_T & wptr_0 == 5'h7)	// @[DelayPipe.scala:80:25, :81:25, :127:{22,34,51}]
          regs_7 <= io_in_0;	// @[DelayPipe.scala:80:25]
        if (_T_1 & wptr_1 == 5'h8)	// @[DelayPipe.scala:81:25, :127:{22,34,51}]
          regs_8 <= io_in_1;	// @[DelayPipe.scala:80:25]
        else if (_T & wptr_0 == 5'h8)	// @[DelayPipe.scala:80:25, :81:25, :127:{22,34,51}]
          regs_8 <= io_in_0;	// @[DelayPipe.scala:80:25]
        if (_T_1 & wptr_1 == 5'h9)	// @[DelayPipe.scala:81:25, :127:{22,34,51}]
          regs_9 <= io_in_1;	// @[DelayPipe.scala:80:25]
        else if (_T & wptr_0 == 5'h9)	// @[DelayPipe.scala:80:25, :81:25, :127:{22,34,51}]
          regs_9 <= io_in_0;	// @[DelayPipe.scala:80:25]
        if (_T_1 & wptr_1 == 5'hA)	// @[DelayPipe.scala:81:25, :127:{22,34,51}]
          regs_10 <= io_in_1;	// @[DelayPipe.scala:80:25]
        else if (_T & wptr_0 == 5'hA)	// @[DelayPipe.scala:80:25, :81:25, :127:{22,34,51}]
          regs_10 <= io_in_0;	// @[DelayPipe.scala:80:25]
        if (_T_1 & wptr_1 == 5'hB)	// @[DelayPipe.scala:81:25, :127:{22,34,51}]
          regs_11 <= io_in_1;	// @[DelayPipe.scala:80:25]
        else if (_T & wptr_0 == 5'hB)	// @[DelayPipe.scala:80:25, :81:25, :127:{22,34,51}]
          regs_11 <= io_in_0;	// @[DelayPipe.scala:80:25]
        if (_T_1 & wptr_1 == 5'hC)	// @[DelayPipe.scala:81:25, :127:{22,34,51}]
          regs_12 <= io_in_1;	// @[DelayPipe.scala:80:25]
        else if (_T & wptr_0 == 5'hC)	// @[DelayPipe.scala:80:25, :81:25, :127:{22,34,51}]
          regs_12 <= io_in_0;	// @[DelayPipe.scala:80:25]
        if (_T_1 & wptr_1 == 5'hD)	// @[DelayPipe.scala:81:25, :127:{22,34,51}]
          regs_13 <= io_in_1;	// @[DelayPipe.scala:80:25]
        else if (_T & wptr_0 == 5'hD)	// @[DelayPipe.scala:80:25, :81:25, :127:{22,34,51}]
          regs_13 <= io_in_0;	// @[DelayPipe.scala:80:25]
        if (_T_1 & wptr_1 == 5'hE)	// @[DelayPipe.scala:81:25, :127:{22,34,51}]
          regs_14 <= io_in_1;	// @[DelayPipe.scala:80:25]
        else if (_T & wptr_0 == 5'hE)	// @[DelayPipe.scala:80:25, :81:25, :127:{22,34,51}]
          regs_14 <= io_in_0;	// @[DelayPipe.scala:80:25]
        if (_T_1 & wptr_1 == 5'hF)	// @[DelayPipe.scala:81:25, :127:{22,34,51}]
          regs_15 <= io_in_1;	// @[DelayPipe.scala:80:25]
        else if (_T & wptr_0 == 5'hF)	// @[DelayPipe.scala:80:25, :81:25, :127:{22,34,51}]
          regs_15 <= io_in_0;	// @[DelayPipe.scala:80:25]
        if (_T_1 & wptr_1 == 5'h10)	// @[DelayPipe.scala:81:25, :127:{22,34,51}]
          regs_16 <= io_in_1;	// @[DelayPipe.scala:80:25]
        else if (_T & wptr_0 == 5'h10)	// @[DelayPipe.scala:80:25, :81:25, :127:{22,34,51}]
          regs_16 <= io_in_0;	// @[DelayPipe.scala:80:25]
        if (_T_1 & wptr_1 == 5'h11)	// @[DelayPipe.scala:81:25, :101:13, :127:{22,34,51}]
          regs_17 <= io_in_1;	// @[DelayPipe.scala:80:25]
        else if (_T & wptr_0 == 5'h11)	// @[DelayPipe.scala:80:25, :81:25, :101:13, :127:{22,34,51}]
          regs_17 <= io_in_0;	// @[DelayPipe.scala:80:25]
        if (wptr_1 == 5'h11)	// @[DelayPipe.scala:81:25, :101:13]
          wptr_1 <= 5'h0;	// @[DelayPipe.scala:81:{25,33}]
        else	// @[DelayPipe.scala:101:13]
          wptr_1 <= wptr_1 + 5'h1;	// @[DelayPipe.scala:81:25, :101:37, :127:51]
        if (rptr_0 == 5'h11)	// @[DelayPipe.scala:82:25, :101:13]
          rptr_0 <= 5'h0;	// @[DelayPipe.scala:81:33, :82:25]
        else	// @[DelayPipe.scala:101:13]
          rptr_0 <= rptr_0 + 5'h1;	// @[DelayPipe.scala:82:25, :101:37, :127:51]
        if (rptr_1 == 5'h11)	// @[DelayPipe.scala:82:25, :101:13]
          rptr_1 <= 5'h0;	// @[DelayPipe.scala:81:33, :82:25]
        else	// @[DelayPipe.scala:101:13]
          rptr_1 <= rptr_1 + 5'h1;	// @[DelayPipe.scala:82:25, :101:37, :127:51]
      end
      else begin
        regs_0 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
        regs_1 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
        regs_2 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
        regs_3 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
        regs_4 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
        regs_5 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
        regs_6 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
        regs_7 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
        regs_8 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
        regs_9 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
        regs_10 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
        regs_11 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
        regs_12 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
        regs_13 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
        regs_14 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
        regs_15 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
        regs_16 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
        regs_17 <= 32'h0;	// @[DelayPipe.scala:80:{25,33}]
        wptr_1 <= io_config[9:5] + 5'h1;	// @[DelayPipe.scala:81:25, :87:24, :93:25, :127:51]
        rptr_0 <= $signed(_rptr_0_diff_T_1) > -6'sh1 ? _rptr_0_diff_T_1[4:0] : _rptr_0_diff_T_1[4:0] - 5'hE;	// @[DelayPipe.scala:82:25, :104:19, :105:{8,14,39}]
        rptr_1 <= $signed(_rptr_1_diff_T_1) > -6'sh1 ? _rptr_1_diff_T_1[4:0] : _rptr_1_diff_T_1[4:0] - 5'hE;	// @[DelayPipe.scala:82:25, :104:19, :105:{8,14,39}]
      end
      if (~io_en | wptr_0 == 5'h11)	// @[DelayPipe.scala:81:25, :101:13, :112:18, :114:15, :118:15]
        wptr_0 <= 5'h0;	// @[DelayPipe.scala:81:{25,33}]
      else	// @[DelayPipe.scala:112:18, :114:15, :118:15]
        wptr_0 <= wptr_0 + 5'h1;	// @[DelayPipe.scala:81:25, :101:37, :127:51]
    end
  end // always @(posedge)
  assign io_out_0 = io_en ? (io_config[4:0] == 5'h0 ? io_in_0 : (rptr_0 == 5'h0 ? regs_0 : 32'h0) | (rptr_0 == 5'h1 ? regs_1 : 32'h0) | (rptr_0 == 5'h2 ? regs_2 : 32'h0) | (rptr_0 == 5'h3 ? regs_3 : 32'h0) | (rptr_0 == 5'h4 ? regs_4 : 32'h0) | (rptr_0 == 5'h5 ? regs_5 : 32'h0) | (rptr_0 == 5'h6 ? regs_6 : 32'h0) | (rptr_0 == 5'h7 ? regs_7 : 32'h0) | (rptr_0 == 5'h8 ? regs_8 : 32'h0) | (rptr_0 == 5'h9 ? regs_9 : 32'h0) | (rptr_0 == 5'hA ? regs_10 : 32'h0) | (rptr_0 == 5'hB ? regs_11 : 32'h0) | (rptr_0 == 5'hC ? regs_12 : 32'h0) | (rptr_0 == 5'hD ? regs_13 : 32'h0) | (rptr_0 == 5'hE ? regs_14 : 32'h0) | (rptr_0 == 5'hF ? regs_15 : 32'h0) | (rptr_0 == 5'h10 ? regs_16 : 32'h0) | (rptr_0 == 5'h11 ? regs_17 : 32'h0)) : 32'h0;	// @[DelayPipe.scala:80:{25,33}, :81:33, :82:25, :87:24, :101:13, :127:51, :136:{10,19}, :137:16, :138:{21,32,40}]
  assign io_out_1 = io_en ? (io_config[9:5] == 5'h0 ? io_in_1 : (rptr_1 == 5'h0 ? regs_0 : 32'h0) | (rptr_1 == 5'h1 ? regs_1 : 32'h0) | (rptr_1 == 5'h2 ? regs_2 : 32'h0) | (rptr_1 == 5'h3 ? regs_3 : 32'h0) | (rptr_1 == 5'h4 ? regs_4 : 32'h0) | (rptr_1 == 5'h5 ? regs_5 : 32'h0) | (rptr_1 == 5'h6 ? regs_6 : 32'h0) | (rptr_1 == 5'h7 ? regs_7 : 32'h0) | (rptr_1 == 5'h8 ? regs_8 : 32'h0) | (rptr_1 == 5'h9 ? regs_9 : 32'h0) | (rptr_1 == 5'hA ? regs_10 : 32'h0) | (rptr_1 == 5'hB ? regs_11 : 32'h0) | (rptr_1 == 5'hC ? regs_12 : 32'h0) | (rptr_1 == 5'hD ? regs_13 : 32'h0) | (rptr_1 == 5'hE ? regs_14 : 32'h0) | (rptr_1 == 5'hF ? regs_15 : 32'h0) | (rptr_1 == 5'h10 ? regs_16 : 32'h0) | (rptr_1 == 5'h11 ? regs_17 : 32'h0)) : 32'h0;	// @[DelayPipe.scala:80:{25,33}, :81:33, :82:25, :87:24, :101:13, :127:51, :136:{10,19}, :137:16, :138:{21,32,40}]
endmodule

