// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module CLZ(
  input  [24:0] io_in,
  output [4:0]  io_out
);

  assign io_out = io_in[24] ? 5'h0 : io_in[23] ? 5'h1 : io_in[22] ? 5'h2 : io_in[21] ? 5'h3 : io_in[20] ? 5'h4 : io_in[19] ? 5'h5 : io_in[18] ? 5'h6 : io_in[17] ? 5'h7 : io_in[16] ? 5'h8 : io_in[15] ? 5'h9 : io_in[14] ? 5'hA : io_in[13] ? 5'hB : io_in[12] ? 5'hC : io_in[11] ? 5'hD : io_in[10] ? 5'hE : io_in[9] ? 5'hF : io_in[8] ? 5'h10 : io_in[7] ? 5'h11 : io_in[6] ? 5'h12 : io_in[5] ? 5'h13 : io_in[4] ? 5'h14 : io_in[3] ? 5'h15 : io_in[2] ? 5'h16 : io_in[1] ? 5'h17 : 5'h18;	// @[CLZ.scala:16:35, Mux.scala:47:70]
endmodule

