// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module ConfigMem_20(
  input           clock,
                  reset,
                  io_cfg_en,
  input  [5:0]    io_cfg_addr,
  input  [31:0]   io_cfg_data,
  output [1560:0] io_out_0
);

  reg [1560:0] regs_0;	// @[ConfigMem.scala:27:21]
  always @(posedge clock) begin
    if (reset)
      regs_0 <= 1561'h0;	// @[ConfigMem.scala:27:{21,29}]
    else if (io_cfg_en & io_cfg_addr == 6'h30)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {io_cfg_data[24:0], regs_0[1535:0]};	// @[ConfigMem.scala:27:21, :43:{19,46}]
    else if (io_cfg_en & io_cfg_addr == 6'h2F)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:1536], io_cfg_data, regs_0[1503:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h2E)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:1504], io_cfg_data, regs_0[1471:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h2D)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:1472], io_cfg_data, regs_0[1439:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h2C)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:1440], io_cfg_data, regs_0[1407:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h2B)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:1408], io_cfg_data, regs_0[1375:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h2A)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:1376], io_cfg_data, regs_0[1343:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h29)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:1344], io_cfg_data, regs_0[1311:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h28)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:1312], io_cfg_data, regs_0[1279:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h27)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:1280], io_cfg_data, regs_0[1247:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h26)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:1248], io_cfg_data, regs_0[1215:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h25)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:1216], io_cfg_data, regs_0[1183:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h24)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:1184], io_cfg_data, regs_0[1151:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h23)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:1152], io_cfg_data, regs_0[1119:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h22)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:1120], io_cfg_data, regs_0[1087:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h21)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:1088], io_cfg_data, regs_0[1055:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h20)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:1056], io_cfg_data, regs_0[1023:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h1F)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:1024], io_cfg_data, regs_0[991:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h1E)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:992], io_cfg_data, regs_0[959:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h1D)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:960], io_cfg_data, regs_0[927:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h1C)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:928], io_cfg_data, regs_0[895:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h1B)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:896], io_cfg_data, regs_0[863:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h1A)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:864], io_cfg_data, regs_0[831:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h19)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:832], io_cfg_data, regs_0[799:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h18)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:800], io_cfg_data, regs_0[767:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h17)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:768], io_cfg_data, regs_0[735:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h16)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:736], io_cfg_data, regs_0[703:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h15)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:704], io_cfg_data, regs_0[671:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h14)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:672], io_cfg_data, regs_0[639:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h13)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:640], io_cfg_data, regs_0[607:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h12)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:608], io_cfg_data, regs_0[575:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h11)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:576], io_cfg_data, regs_0[543:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h10)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:544], io_cfg_data, regs_0[511:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'hF)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:512], io_cfg_data, regs_0[479:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'hE)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:480], io_cfg_data, regs_0[447:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'hD)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:448], io_cfg_data, regs_0[415:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'hC)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:416], io_cfg_data, regs_0[383:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'hB)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:384], io_cfg_data, regs_0[351:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'hA)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:352], io_cfg_data, regs_0[319:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h9)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:320], io_cfg_data, regs_0[287:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h8)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:288], io_cfg_data, regs_0[255:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h7)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:256], io_cfg_data, regs_0[223:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h6)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:224], io_cfg_data, regs_0[191:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h5)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:192], io_cfg_data, regs_0[159:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h4)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:160], io_cfg_data, regs_0[127:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h3)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:128], io_cfg_data, regs_0[95:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h2)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:96], io_cfg_data, regs_0[63:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h1)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:64], io_cfg_data, regs_0[31:0]};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :45:{33,87}]
    else if (io_cfg_en & io_cfg_addr == 6'h0)	// @[ConfigMem.scala:39:{22,38}]
      regs_0 <= {regs_0[1560:32], io_cfg_data};	// @[Cat.scala:33:92, ConfigMem.scala:27:21, :41:33]
  end // always @(posedge)
  assign io_out_0 = regs_0;	// @[ConfigMem.scala:27:21]
endmodule

