// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module CtrlReg(
  input         clock,
                reset,
                io_start,
  input  [2:0]  io_mode,
  input  [78:0] io_config,
  input  [31:0] io_in_0,
                io_in_1,
  output [31:0] io_out_0,
                io_out_1
);

  reg  [31:0] valueReg;	// @[DMR.scala:42:25]
  reg  [31:0] valueRegAcc;	// @[DMR.scala:43:28]
  reg  [1:0]  state;	// @[DMR.scala:85:22]
  reg  [12:0] wiCnt;	// @[DMR.scala:86:22]
  reg  [5:0]  latCnt;	// @[DMR.scala:87:23]
  reg  [12:0] cycleCnt;	// @[DMR.scala:88:25]
  reg  [12:0] repeatCnt;	// @[DMR.scala:89:26]
  reg         realen_REG;	// @[DMR.scala:201:22]
  wire [5:0]  _T_7 = latCnt + 6'h1;	// @[DMR.scala:87:23, :104:19]
  wire [12:0] _wiEnd_T_1 = wiCnt + 13'h1;	// @[DMR.scala:86:22, :90:21]
  wire        wiEnd = _wiEnd_T_1 >= io_config[44:32];	// @[DMR.scala:59:21, :90:{21,26}]
  wire [12:0] _cycleCntEnd_T_1 = cycleCnt + 13'h1;	// @[DMR.scala:88:25, :90:21, :91:30]
  wire        cycleCntEnd = _cycleCntEnd_T_1 >= io_config[63:51];	// @[DMR.scala:67:25, :91:{30,35}]
  wire [12:0] _repeatCntEnd_T_1 = repeatCnt + 13'h1;	// @[DMR.scala:89:26, :90:21, :92:32]
  wire        launch = state == 2'h2;	// @[DMR.scala:85:22, :98:15, :116:23]
  wire        _initAcc_T_5 = io_mode != 3'h3;	// @[DMR.scala:205:110]
  wire        _initAcc_T_8 = cycleCnt == 13'h0;	// @[DMR.scala:86:22, :88:25, :205:134]
  wire        initSel = io_mode == 3'h5;	// @[DMR.scala:197:25]
  wire        en = io_mode == 3'h1 | initSel;	// @[DMR.scala:197:25, :198:{21,58}]
  wire        realen = io_config[78] ? realen_REG : en;	// @[DMR.scala:79:26, :198:58, :200:16, :201:{12,22}, :203:12]
  always @(posedge clock) begin
    if (reset) begin
      valueReg <= 32'h0;	// @[DMR.scala:42:25]
      valueRegAcc <= 32'h0;	// @[DMR.scala:42:25, :43:28]
      state <= 2'h0;	// @[DMR.scala:85:22]
      wiCnt <= 13'h0;	// @[DMR.scala:86:22]
      latCnt <= 6'h0;	// @[DMR.scala:87:23]
      cycleCnt <= 13'h0;	// @[DMR.scala:86:22, :88:25]
      repeatCnt <= 13'h0;	// @[DMR.scala:86:22, :89:26]
    end
    else begin
      if (io_mode == 3'h0)	// @[DMR.scala:219:16]
        valueReg <= io_in_0;	// @[DMR.scala:42:25]
      else if (launch & ~(|wiCnt)) begin	// @[DMR.scala:86:22, :116:23, :221:{21,30}]
        if (_initAcc_T_5 & (_initAcc_T_8 & (io_config[77] | io_mode > 3'h4) | _initAcc_T_8 & ~(io_config[77]) & ~en)) begin	// @[DMR.scala:75:28, :198:58, :205:{110,120,134,142,156,167,176,200,211,214}]
          if (io_mode == 3'h6 | initSel)	// @[DMR.scala:196:59, :197:25, :223:21, :224:18, :225:26, :226:18, :228:18]
            valueReg <= io_in_1;	// @[DMR.scala:42:25]
          else	// @[DMR.scala:223:21, :224:18, :225:26, :226:18, :228:18]
            valueReg <= io_config[31:0];	// @[DMR.scala:42:25, :55:26]
        end
        else if (realen)	// @[DMR.scala:200:16, :201:12, :203:12]
          valueReg <= io_in_0;	// @[DMR.scala:42:25]
      end
      if (state == 2'h0) begin	// @[DMR.scala:85:22, :94:16]
        valueRegAcc <= io_config[31:0];	// @[DMR.scala:43:28, :55:26]
        if (io_start & io_config[50:45] == 6'h0)	// @[DMR.scala:63:26, :87:23, :97:{21,32}]
          state <= 2'h2;	// @[DMR.scala:85:22, :98:15]
        else if (io_start & (|(io_config[50:45])))	// @[DMR.scala:63:26, :99:{27,38}]
          state <= 2'h1;	// @[DMR.scala:85:22, :100:15]
        wiCnt <= 13'h0;	// @[DMR.scala:86:22]
        latCnt <= 6'h0;	// @[DMR.scala:87:23]
        cycleCnt <= 13'h0;	// @[DMR.scala:86:22, :88:25]
        repeatCnt <= 13'h0;	// @[DMR.scala:86:22, :89:26]
      end
      else begin	// @[DMR.scala:94:16]
        if (launch & ~(|wiCnt)) begin	// @[DMR.scala:86:22, :116:23, :221:30, :248:{21,30}]
          if (_initAcc_T_5 & io_mode != 3'h6 & (_initAcc_T_8 & io_config[77] | cycleCntEnd & ~(io_config[77])))	// @[DMR.scala:75:28, :91:35, :196:59, :205:{110,134,200}, :244:{113,122,144,158,174}]
            valueRegAcc <= io_config[31:0];	// @[DMR.scala:43:28, :55:26]
          else if (realen)	// @[DMR.scala:200:16, :201:12, :203:12]
            valueRegAcc <= io_in_0;	// @[DMR.scala:43:28]
        end
        if (state == 2'h1) begin	// @[DMR.scala:85:22, :94:16, :100:15]
          if (_T_7 >= io_config[50:45])	// @[DMR.scala:63:26, :104:{19,25}]
            state <= 2'h2;	// @[DMR.scala:85:22, :98:15]
          latCnt <= _T_7;	// @[DMR.scala:87:23, :104:19]
        end
        else if (state == 2'h2 & _repeatCntEnd_T_1 >= io_config[76:64] & cycleCntEnd & wiEnd)	// @[DMR.scala:71:26, :85:22, :90:26, :91:35, :92:{32,37}, :94:16, :98:15, :110:49, :111:15]
          state <= 2'h0;	// @[DMR.scala:85:22]
        if (launch) begin	// @[DMR.scala:116:23]
          if (wiEnd)	// @[DMR.scala:90:26]
            wiCnt <= 13'h0;	// @[DMR.scala:86:22]
          else	// @[DMR.scala:90:26]
            wiCnt <= _wiEnd_T_1;	// @[DMR.scala:86:22, :90:21]
        end
        if (launch & wiEnd) begin	// @[DMR.scala:90:26, :116:23, :125:21]
          if (cycleCntEnd)	// @[DMR.scala:91:35]
            cycleCnt <= 13'h0;	// @[DMR.scala:86:22, :88:25]
          else	// @[DMR.scala:91:35]
            cycleCnt <= _cycleCntEnd_T_1;	// @[DMR.scala:88:25, :91:30]
        end
        if (launch & wiEnd & cycleCntEnd)	// @[DMR.scala:90:26, :91:35, :116:23, :131:30]
          repeatCnt <= _repeatCntEnd_T_1;	// @[DMR.scala:89:26, :92:32]
      end
    end
    realen_REG <= en;	// @[DMR.scala:198:58, :201:22]
  end // always @(posedge)
  assign io_out_0 = valueReg;	// @[DMR.scala:42:25]
  assign io_out_1 = valueRegAcc;	// @[DMR.scala:43:28]
endmodule

