// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module FarPath(
  input         io_in_a_sign,
  input  [7:0]  io_in_a_exp,
  input  [23:0] io_in_a_sig,
                io_in_b_sig,
  input  [7:0]  io_in_expDiff,
  input         io_in_effSub,
  output        io_out_result_sign,
  output [23:0] io_out_sig_a,
  output [27:0] io_out_sig_b,
  output [7:0]  io_out_exp_a_vec_0,
                io_out_exp_a_vec_1,
                io_out_exp_a_vec_2
);

  wire [25:0] _shiftRightJam_io_out;	// @[ShiftRightJam.scala:27:31]
  wire        _shiftRightJam_io_sticky;	// @[ShiftRightJam.scala:27:31]
  ShiftRightJam shiftRightJam (	// @[ShiftRightJam.scala:27:31]
    .io_in     ({io_in_b_sig, 2'h0}),	// @[Cat.scala:33:92]
    .io_shamt  (io_in_expDiff),
    .io_out    (_shiftRightJam_io_out),
    .io_sticky (_shiftRightJam_io_sticky)
  );
  assign io_out_result_sign = io_in_a_sign;
  assign io_out_sig_a = io_in_a_sig;
  assign io_out_sig_b = (io_in_effSub ? {1'h1, ~_shiftRightJam_io_out, ~_shiftRightJam_io_sticky} : {1'h0, _shiftRightJam_io_out, _shiftRightJam_io_sticky}) + {27'h0, io_in_effSub};	// @[Cat.scala:33:92, FADD.scala:35:{27,37,86}, ShiftRightJam.scala:27:31]
  assign io_out_exp_a_vec_0 = io_in_a_exp + 8'h1;	// @[FADD.scala:45:28]
  assign io_out_exp_a_vec_1 = io_in_a_exp;
  assign io_out_exp_a_vec_2 = io_in_a_exp - 8'h1;	// @[FADD.scala:46:29]
endmodule

