// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module FCMA_ADD_s2(
  input         io_in_far_path_out_sign,
                io_in_near_path_out_sign,
  input  [7:0]  io_in_near_path_out_exp,
  input         io_in_special_case_valid,
                io_in_special_case_bits_nan,
                io_in_special_case_bits_inf_sign,
                io_in_small_add,
                io_in_far_path_mul_of,
  input  [23:0] io_in_far_sig_a,
  input  [27:0] io_in_far_sig_b,
  input  [7:0]  io_in_far_exp_a_vec_0,
                io_in_far_exp_a_vec_1,
                io_in_far_exp_a_vec_2,
  input         io_in_near_path_sig_is_zero,
                io_in_near_path_lza_error,
                io_in_near_path_int_bit,
  input  [24:0] io_in_near_path_sig_raw,
  input  [4:0]  io_in_near_path_lzc,
  input         io_in_sel_far_path,
  output [31:0] io_result
);

  wire [7:0]  near_path_res_exp;	// @[FADD.scala:433:27]
  wire [22:0] _near_path_rounder_io_out;	// @[RoundingUnit.scala:45:25]
  wire        _near_path_rounder_io_cout;	// @[RoundingUnit.scala:45:25]
  wire [22:0] _far_path_rounder_io_out;	// @[RoundingUnit.scala:45:25]
  wire        _far_path_rounder_io_cout;	// @[RoundingUnit.scala:45:25]
  wire [27:0] _GEN = {1'h0, io_in_far_sig_a, 3'h0} + io_in_far_sig_b;	// @[FADD.scala:366:37, :464:68]
  wire        keep = _GEN[27:26] == 2'h1;	// @[FADD.scala:366:37, :369:{31,35}]
  wire        cancellation = _GEN[27:26] == 2'h0;	// @[Cat.scala:33:92, FADD.scala:366:37, :369:31, :370:43]
  wire [26:0] _far_path_res_sig_WIRE = (_GEN[27] ? {_GEN[27:2], |(_GEN[1:0])} : 27'h0) | (keep | io_in_small_add ? _GEN[26:0] : 27'h0) | (cancellation & ~io_in_small_add ? {_GEN[25:0], 1'h0} : 27'h0);	// @[FADD.scala:366:37, :368:31, :369:35, :370:43, :373:{20,47,50}, :375:{24,36,56,68}, :376:44, :377:{24,44}, :464:68, Mux.scala:27:73]
  wire [7:0]  _far_path_res_exp_WIRE = (_GEN[27] ? io_in_far_exp_a_vec_0 : 8'h0) | (keep ? io_in_far_exp_a_vec_1 : 8'h0) | (cancellation ? io_in_far_exp_a_vec_2 : 8'h0);	// @[FADD.scala:366:37, :368:31, :369:35, :370:43, Mux.scala:27:73]
  assign near_path_res_exp = io_in_near_path_int_bit ? io_in_near_path_out_exp - {3'h0, io_in_near_path_lzc} - {7'h0, io_in_near_path_lza_error} : 8'h0;	// @[FADD.scala:401:55, :431:40, :432:23, :433:27, Mux.scala:27:73]
  wire [55:0] _sig_s1_T = {31'h0, io_in_near_path_sig_raw} << io_in_near_path_lzc;	// @[FADD.scala:435:41]
  wire [24:0] sig_s2 = io_in_near_path_lza_error ? {_sig_s1_T[23:0], 1'h0} : _sig_s1_T[24:0];	// @[Cat.scala:33:92, FADD.scala:435:{41,48}, :436:{19,62}, :464:68]
  wire [7:0]  near_path_exp_rounded = {7'h0, _near_path_rounder_io_cout} + near_path_res_exp;	// @[FADD.scala:401:55, :433:27, :460:57, RoundingUnit.scala:45:25]
  TininessRounder far_path_tininess_rounder (	// @[FADD.scala:389:41]
    .io_in_sign (io_in_far_path_out_sign),
    .io_in_sig  (_far_path_res_sig_WIRE)	// @[Mux.scala:27:73]
  );
  RoundingUnit far_path_rounder (	// @[RoundingUnit.scala:45:25]
    .io_in       (_far_path_res_sig_WIRE[25:3]),	// @[FADD.scala:395:27, Mux.scala:27:73, RoundingUnit.scala:46:33]
    .io_roundIn  (_far_path_res_sig_WIRE[2]),	// @[FADD.scala:395:27, Mux.scala:27:73, RoundingUnit.scala:47:{38,50}]
    .io_stickyIn (|(_far_path_res_sig_WIRE[1:0])),	// @[FADD.scala:395:27, Mux.scala:27:73, RoundingUnit.scala:48:{39,51}]
    .io_signIn   (io_in_far_path_out_sign),
    .io_rm       (3'h0),
    .io_out      (_far_path_rounder_io_out),
    .io_cout     (_far_path_rounder_io_cout)
  );
  TininessRounder near_path_tininess_rounder (	// @[FADD.scala:448:42]
    .io_in_sign (io_in_near_path_out_sign),
    .io_in_sig  ({sig_s2, 2'h0})	// @[Cat.scala:33:92, FADD.scala:436:19]
  );
  RoundingUnit near_path_rounder (	// @[RoundingUnit.scala:45:25]
    .io_in       (sig_s2[23:1]),	// @[FADD.scala:436:19, :454:28, RoundingUnit.scala:46:33]
    .io_roundIn  (sig_s2[0]),	// @[FADD.scala:436:19, :454:28, RoundingUnit.scala:47:{38,50}]
    .io_stickyIn (1'h0),	// @[FADD.scala:464:68]
    .io_signIn   (io_in_near_path_out_sign),
    .io_rm       (3'h0),
    .io_out      (_near_path_rounder_io_out),
    .io_cout     (_near_path_rounder_io_cout)
  );
  assign io_result = io_in_special_case_valid ? (io_in_special_case_bits_nan ? 32'h7FC00000 : {io_in_special_case_bits_inf_sign, 31'h7F800000}) : io_in_sel_far_path & ((&_far_path_res_exp_WIRE) | _far_path_rounder_io_cout & _far_path_res_exp_WIRE == 8'hFE | io_in_far_path_mul_of) | ~io_in_sel_far_path & (&near_path_exp_rounded) ? {io_in_sel_far_path ? io_in_far_path_out_sign : io_in_near_path_out_sign, 31'h7F800000} : io_in_sel_far_path ? {io_in_far_path_out_sign, {7'h0, _far_path_rounder_io_cout} + _far_path_res_exp_WIRE, _far_path_rounder_io_out} : {io_in_near_path_out_sign & ~(near_path_res_exp == 8'h0 & io_in_near_path_sig_is_zero), near_path_exp_rounded, _near_path_rounder_io_out};	// @[Cat.scala:33:92, FADD.scala:349:32, :401:55, :409:18, :410:58, :411:18, :414:57, :427:{41,49}, :433:27, :460:57, :464:{21,24}, :469:44, :475:{18,33,36,50}, :477:8, :498:19, :501:8, :504:10, Mux.scala:27:73, RoundingUnit.scala:45:25]
endmodule

