// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module FPMult(
  input         clock,
  input  [31:0] io_a,
                io_b,
  output [31:0] io_res
);

  wire [22:0] _rounder_io_out;	// @[FPMult.scala:48:25]
  reg         sign_reg;	// @[FPMult.scala:34:31]
  reg  [7:0]  exponent_reg;	// @[FPMult.scala:35:31]
  reg  [47:0] mantissa_reg;	// @[FPMult.scala:36:31]
  reg         zero_reg;	// @[FPMult.scala:37:31]
  always @(posedge clock) begin
    sign_reg <= io_a[31] ^ io_b[31];	// @[FPMult.scala:29:39, :34:31, FloatWrapper.scala:13:12]
    exponent_reg <= io_a[30:23] + io_b[30:23];	// @[FPMult.scala:30:43, :35:31, FloatWrapper.scala:14:12]
    mantissa_reg <= {24'h0, |(io_a[30:23]), io_a[22:0]} * {24'h0, |(io_b[30:23]), io_b[22:0]};	// @[FPMult.scala:31:43, :36:31, :52:23, FloatWrapper.scala:14:12, :16:{29,62}]
    zero_reg <= io_a[30:0] == 31'h0 | io_b[30:0] == 31'h0;	// @[FPMult.scala:32:39, :37:31, FloatWrapper.scala:17:{12,20}]
  end // always @(posedge)
  MantissaRounder rounder (	// @[FPMult.scala:48:25]
    .io_in  (zero_reg ? 24'h0 : mantissa_reg[47] ? mantissa_reg[46:23] : mantissa_reg[45:22]),	// @[FPMult.scala:36:31, :37:31, :50:20, :52:23, :53:{28,52}, :55:{23,38}, :58:{23,38}]
    .io_out (_rounder_io_out)
  );
  assign io_res = {sign_reg, zero_reg ? 8'h0 : mantissa_reg[47] ? exponent_reg - 8'h7E : exponent_reg - 8'h7F, _rounder_io_out};	// @[Cat.scala:33:92, FPMult.scala:34:31, :35:31, :36:31, :37:31, :48:25, :50:20, :51:25, :53:{28,52}, :54:{25,41}, :57:{25,41}]
endmodule

