// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module FPToInt_s1(
  input  [31:0] io_a,
  output        io_to_s2_raw_a_sign,
  output [23:0] io_to_s2_raw_a_sig,
  output        io_to_s2_sel_lpath,
                io_to_s2_exp_of,
                io_to_s2_iv_sel_max,
                io_to_s2_lpath_of,
  output [5:0]  io_to_s2_lpath_shamt,
  output [7:0]  io_to_s2_rpath_shamt
);

  wire [7:0] raw_a_exp = io_a[30:23] | {7'h0, ~(|(io_a[30:23]))};	// @[package.scala:34:28, :62:18, :85:{27,29}]
  wire       _lpath_may_of_T = raw_a_exp == 8'h9E;	// @[FPToInt.scala:47:36, :63:50, package.scala:85:27]
  assign io_to_s2_raw_a_sign = io_a[31];	// @[package.scala:61:19]
  assign io_to_s2_raw_a_sig = {|(io_a[30:23]), io_a[22:0]};	// @[Cat.scala:33:92, package.scala:34:28, :62:18, :63:18]
  assign io_to_s2_sel_lpath = raw_a_exp > 8'h95;	// @[FPToInt.scala:82:29, package.scala:85:27]
  assign io_to_s2_exp_of = raw_a_exp > 8'h9E;	// @[FPToInt.scala:47:36, :48:26, package.scala:85:27]
  assign io_to_s2_iv_sel_max = (&(io_a[30:23])) & (|(io_a[22:0])) | ~(io_a[31]);	// @[FPToInt.scala:54:{41,44}, package.scala:35:27, :36:28, :46:40, :61:19, :62:18, :63:18]
  assign io_to_s2_lpath_of = _lpath_may_of_T & ~(io_a[31]) | _lpath_may_of_T & io_a[31] & (|(io_a[22:0]));	// @[FPToInt.scala:54:44, :63:50, :64:35, :65:{49,70}, :66:31, package.scala:61:19, :63:18]
  assign io_to_s2_lpath_shamt = raw_a_exp[5:0] - 6'h16;	// @[FPToInt.scala:61:31, package.scala:85:27]
  assign io_to_s2_rpath_shamt = 8'h96 - raw_a_exp;	// @[FPToInt.scala:61:31, :75:70, package.scala:85:27]
endmodule

