// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module GIB_27(
  input         clock,
                reset,
                io_cfg_en,
  input  [13:0] io_cfg_addr,
  input  [31:0] io_cfg_data,
                io_opinNW_0,
                io_opinSW_0,
                io_itrackW_0,
                io_itrackN_0,
                io_itrackS_0,
  output [31:0] io_ipinNW_0,
                io_ipinNW_1,
                io_ipinSW_0,
                io_ipinSW_1,
                io_otrackW_0,
                io_otrackN_0,
                io_otrackS_0
);

  wire [31:0] _mux_3_io_out;	// @[Interconnect.scala:503:25]
  wire [31:0] _mux_2_io_out;	// @[Interconnect.scala:503:25]
  wire [31:0] _mux_1_io_out;	// @[Interconnect.scala:503:25]
  wire [5:0]  _cfg_io_out_0;	// @[Interconnect.scala:493:21]
  reg  [31:0] io_otrackW_0_REG;	// @[Interconnect.scala:507:55]
  reg  [31:0] io_otrackN_0_REG;	// @[Interconnect.scala:507:55]
  reg  [31:0] io_otrackS_0_REG;	// @[Interconnect.scala:507:55]
  always @(posedge clock) begin
    io_otrackW_0_REG <= _mux_1_io_out;	// @[Interconnect.scala:503:25, :507:55]
    io_otrackN_0_REG <= _mux_2_io_out;	// @[Interconnect.scala:503:25, :507:55]
    io_otrackS_0_REG <= _mux_3_io_out;	// @[Interconnect.scala:503:25, :507:55]
  end // always @(posedge)
  ConfigMem_55 cfg (	// @[Interconnect.scala:493:21]
    .clock       (clock),
    .reset       (reset),
    .io_cfg_en   (io_cfg_en & io_cfg_addr[13:6] == 8'h4D),	// @[Interconnect.scala:494:{32,50,65}]
    .io_cfg_data (io_cfg_data),
    .io_out_0    (_cfg_io_out_0)
  );
  Muxn mux (	// @[Interconnect.scala:503:25]
    .io_config (_cfg_io_out_0[0]),	// @[Interconnect.scala:493:21, :513:39]
    .io_in_0   (io_opinSW_0),
    .io_in_1   (io_itrackS_0),
    .io_out    (io_ipinNW_1)
  );
  Muxn mux_1 (	// @[Interconnect.scala:503:25]
    .io_config (_cfg_io_out_0[1]),	// @[Interconnect.scala:493:21, :513:39]
    .io_in_0   (io_itrackN_0),
    .io_in_1   (io_itrackS_0),
    .io_out    (_mux_1_io_out)
  );
  Muxn_215 mux_2 (	// @[Interconnect.scala:503:25]
    .io_config (_cfg_io_out_0[3:2]),	// @[Interconnect.scala:493:21, :513:39]
    .io_in_0   (io_opinSW_0),
    .io_in_1   (io_itrackW_0),
    .io_in_2   (io_itrackS_0),
    .io_out    (_mux_2_io_out)
  );
  Muxn_215 mux_3 (	// @[Interconnect.scala:503:25]
    .io_config (_cfg_io_out_0[5:4]),	// @[Interconnect.scala:493:21, :513:39]
    .io_in_0   (io_opinNW_0),
    .io_in_1   (io_itrackW_0),
    .io_in_2   (io_itrackN_0),
    .io_out    (_mux_3_io_out)
  );
  assign io_ipinNW_0 = io_itrackS_0;
  assign io_ipinSW_0 = io_itrackN_0;
  assign io_ipinSW_1 = io_itrackN_0;
  assign io_otrackW_0 = io_otrackW_0_REG;	// @[Interconnect.scala:507:55]
  assign io_otrackN_0 = io_otrackN_0_REG;	// @[Interconnect.scala:507:55]
  assign io_otrackS_0 = io_otrackS_0_REG;	// @[Interconnect.scala:507:55]
endmodule

