// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module IntToFP_prenorm(
  input  [63:0] io_in_int,
  output [62:0] io_out_norm_int,
  output [5:0]  io_out_lzc,
  output        io_out_is_zero,
                io_out_sign
);

  wire [5:0]   _neg_lzc_clz_io_out;	// @[CLZ.scala:21:21]
  wire [5:0]   _pos_lzc_clz_io_out;	// @[CLZ.scala:21:21]
  wire [63:0]  _lza_io_f;	// @[IntToFP.scala:37:19]
  wire [63:0]  in_sext = {{32{io_in_int[31]}}, io_in_int[31:0]};	// @[Bitwise.scala:77:12, Cat.scala:33:92, IntToFP.scala:32:55, :33:41]
  wire [63:0]  in_abs = io_in_int[31] ? ~in_sext + 64'h1 : in_sext;	// @[Cat.scala:33:92, IntToFP.scala:32:55, :35:{19,30,46}]
  wire [5:0]   lzc = io_in_int[31] ? _neg_lzc_clz_io_out : _pos_lzc_clz_io_out;	// @[CLZ.scala:21:21, IntToFP.scala:32:55, :44:16]
  wire         lzc_error =
    io_in_int[31]
    & (in_abs
       & {_lza_io_f[63],
          _lza_io_f[62] & ~(_lza_io_f[63]),
          _lza_io_f[61] & _lza_io_f[63:62] == 2'h0,
          _lza_io_f[60] & _lza_io_f[63:61] == 3'h0,
          _lza_io_f[59] & _lza_io_f[63:60] == 4'h0,
          _lza_io_f[58] & _lza_io_f[63:59] == 5'h0,
          _lza_io_f[57] & _lza_io_f[63:58] == 6'h0,
          _lza_io_f[56] & _lza_io_f[63:57] == 7'h0,
          _lza_io_f[55] & _lza_io_f[63:56] == 8'h0,
          _lza_io_f[54] & _lza_io_f[63:55] == 9'h0,
          _lza_io_f[53] & _lza_io_f[63:54] == 10'h0,
          _lza_io_f[52] & _lza_io_f[63:53] == 11'h0,
          _lza_io_f[51] & _lza_io_f[63:52] == 12'h0,
          _lza_io_f[50] & _lza_io_f[63:51] == 13'h0,
          _lza_io_f[49] & _lza_io_f[63:50] == 14'h0,
          _lza_io_f[48] & _lza_io_f[63:49] == 15'h0,
          _lza_io_f[47] & _lza_io_f[63:48] == 16'h0,
          _lza_io_f[46] & _lza_io_f[63:47] == 17'h0,
          _lza_io_f[45] & _lza_io_f[63:46] == 18'h0,
          _lza_io_f[44] & _lza_io_f[63:45] == 19'h0,
          _lza_io_f[43] & _lza_io_f[63:44] == 20'h0,
          _lza_io_f[42] & _lza_io_f[63:43] == 21'h0,
          _lza_io_f[41] & _lza_io_f[63:42] == 22'h0,
          _lza_io_f[40] & _lza_io_f[63:41] == 23'h0,
          _lza_io_f[39] & _lza_io_f[63:40] == 24'h0,
          _lza_io_f[38] & _lza_io_f[63:39] == 25'h0,
          _lza_io_f[37] & _lza_io_f[63:38] == 26'h0,
          _lza_io_f[36] & _lza_io_f[63:37] == 27'h0,
          _lza_io_f[35] & _lza_io_f[63:36] == 28'h0,
          _lza_io_f[34] & _lza_io_f[63:35] == 29'h0,
          _lza_io_f[33] & _lza_io_f[63:34] == 30'h0,
          _lza_io_f[32] & _lza_io_f[63:33] == 31'h0,
          _lza_io_f[31] & _lza_io_f[63:32] == 32'h0,
          _lza_io_f[30] & _lza_io_f[63:31] == 33'h0,
          _lza_io_f[29] & _lza_io_f[63:30] == 34'h0,
          _lza_io_f[28] & _lza_io_f[63:29] == 35'h0,
          _lza_io_f[27] & _lza_io_f[63:28] == 36'h0,
          _lza_io_f[26] & _lza_io_f[63:27] == 37'h0,
          _lza_io_f[25] & _lza_io_f[63:26] == 38'h0,
          _lza_io_f[24] & _lza_io_f[63:25] == 39'h0,
          _lza_io_f[23] & _lza_io_f[63:24] == 40'h0,
          _lza_io_f[22] & _lza_io_f[63:23] == 41'h0,
          _lza_io_f[21] & _lza_io_f[63:22] == 42'h0,
          _lza_io_f[20] & _lza_io_f[63:21] == 43'h0,
          _lza_io_f[19] & _lza_io_f[63:20] == 44'h0,
          _lza_io_f[18] & _lza_io_f[63:19] == 45'h0,
          _lza_io_f[17] & _lza_io_f[63:18] == 46'h0,
          _lza_io_f[16] & _lza_io_f[63:17] == 47'h0,
          _lza_io_f[15] & _lza_io_f[63:16] == 48'h0,
          _lza_io_f[14] & _lza_io_f[63:15] == 49'h0,
          _lza_io_f[13] & _lza_io_f[63:14] == 50'h0,
          _lza_io_f[12] & _lza_io_f[63:13] == 51'h0,
          _lza_io_f[11] & _lza_io_f[63:12] == 52'h0,
          _lza_io_f[10] & _lza_io_f[63:11] == 53'h0,
          _lza_io_f[9] & _lza_io_f[63:10] == 54'h0,
          _lza_io_f[8] & _lza_io_f[63:9] == 55'h0,
          _lza_io_f[7] & _lza_io_f[63:8] == 56'h0,
          _lza_io_f[6] & _lza_io_f[63:7] == 57'h0,
          _lza_io_f[5] & _lza_io_f[63:6] == 58'h0,
          _lza_io_f[4] & _lza_io_f[63:5] == 59'h0,
          _lza_io_f[3] & _lza_io_f[63:4] == 60'h0,
          _lza_io_f[2] & _lza_io_f[63:3] == 61'h0,
          _lza_io_f[1] & _lza_io_f[63:2] == 62'h0,
          _lza_io_f[63:1] == 63'h0}) == 64'h0;	// @[Bitwise.scala:77:12, Cat.scala:33:92, IntToFP.scala:32:55, :35:{19,46}, :37:19, :48:28, :49:{29,41}, :50:{28,32,35,44,56}, :53:{22,41,53}]
  wire [126:0] _in_shift_s1_T = {63'h0, in_abs} << lzc;	// @[IntToFP.scala:35:19, :44:16, :49:41, :55:29]
  LZA_2 lza (	// @[IntToFP.scala:37:19]
    .io_b (~in_sext),	// @[Cat.scala:33:92, IntToFP.scala:35:30]
    .io_f (_lza_io_f)
  );
  CLZ_3 pos_lzc_clz (	// @[CLZ.scala:21:21]
    .io_in  (io_in_int),
    .io_out (_pos_lzc_clz_io_out)
  );
  CLZ_3 neg_lzc_clz (	// @[CLZ.scala:21:21]
    .io_in  (_lza_io_f),	// @[IntToFP.scala:37:19]
    .io_out (_neg_lzc_clz_io_out)
  );
  assign io_out_norm_int = lzc_error ? {_in_shift_s1_T[61:0], 1'h0} : _in_shift_s1_T[62:0];	// @[Cat.scala:33:92, IntToFP.scala:53:22, :55:{29,36}, :56:{20,52}]
  assign io_out_lzc = lzc + {5'h0, lzc_error};	// @[IntToFP.scala:44:16, :50:56, :53:22, :59:21]
  assign io_out_is_zero = io_in_int == 64'h0;	// @[IntToFP.scala:35:46, :60:24]
  assign io_out_sign = io_in_int[31];	// @[IntToFP.scala:32:55]
endmodule

