// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module LZA(
  input  [24:0] io_a,
                io_b,
  output [24:0] io_f
);

  assign io_f = {io_a[24] ^ io_b[24] ^ ~(~(io_a[23]) & ~(io_b[23])), io_a[23] ^ io_b[23] ^ ~(~(io_a[22]) & ~(io_b[22])), io_a[22] ^ io_b[22] ^ ~(~(io_a[21]) & ~(io_b[21])), io_a[21] ^ io_b[21] ^ ~(~(io_a[20]) & ~(io_b[20])), io_a[20] ^ io_b[20] ^ ~(~(io_a[19]) & ~(io_b[19])), io_a[19] ^ io_b[19] ^ ~(~(io_a[18]) & ~(io_b[18])), io_a[18] ^ io_b[18] ^ ~(~(io_a[17]) & ~(io_b[17])), io_a[17] ^ io_b[17] ^ ~(~(io_a[16]) & ~(io_b[16])), io_a[16] ^ io_b[16] ^ ~(~(io_a[15]) & ~(io_b[15])), io_a[15] ^ io_b[15] ^ ~(~(io_a[14]) & ~(io_b[14])), io_a[14] ^ io_b[14] ^ ~(~(io_a[13]) & ~(io_b[13])), io_a[13] ^ io_b[13] ^ ~(~(io_a[12]) & ~(io_b[12])), io_a[12] ^ io_b[12] ^ ~(~(io_a[11]) & ~(io_b[11])), io_a[11] ^ io_b[11] ^ ~(~(io_a[10]) & ~(io_b[10])), io_a[10] ^ io_b[10] ^ ~(~(io_a[9]) & ~(io_b[9])), io_a[9] ^ io_b[9] ^ ~(~(io_a[8]) & ~(io_b[8])), io_a[8] ^ io_b[8] ^ ~(~(io_a[7]) & ~(io_b[7])), io_a[7] ^ io_b[7] ^ ~(~(io_a[6]) & ~(io_b[6])), io_a[6] ^ io_b[6] ^ ~(~(io_a[5]) & ~(io_b[5])), io_a[5] ^ io_b[5] ^ ~(~(io_a[4]) & ~(io_b[4])), io_a[4] ^ io_b[4] ^ ~(~(io_a[3]) & ~(io_b[3])), io_a[3] ^ io_b[3] ^ ~(~(io_a[2]) & ~(io_b[2])), io_a[2] ^ io_b[2] ^ ~(~(io_a[1]) & ~(io_b[1])), io_a[1] ^ io_b[1] ^ ~(~(io_a[0]) & ~(io_b[0])), 1'h0};	// @[Cat.scala:33:92, LZA.scala:18:{14,21}, :19:{14,21,24}, :23:20]
endmodule

