// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module RecFNToRecFN(
  input  [64:0] io_in,
  input  [2:0]  io_roundingMode,
  output [32:0] io_out,
  output [4:0]  io_exceptionFlags
);

  wire rawIn_isNaN = (&(io_in[63:62])) & io_in[61];	// @[rawFloatFromRecFN.scala:50:21, :52:{29,54}, :55:{33,41}]
  RoundAnyRawFNToRecFN_3 roundAnyRawFNToRecFN (	// @[RecFNToRecFN.scala:72:19]
    .io_invalidExc     (rawIn_isNaN & ~(io_in[51])),	// @[common.scala:82:{46,49,56}, rawFloatFromRecFN.scala:55:33]
    .io_in_isNaN       (rawIn_isNaN),	// @[rawFloatFromRecFN.scala:55:33]
    .io_in_isInf       ((&(io_in[63:62])) & ~(io_in[61])),	// @[rawFloatFromRecFN.scala:50:21, :52:{29,54}, :55:41, :56:{33,36}]
    .io_in_isZero      (~(|(io_in[63:61]))),	// @[rawFloatFromRecFN.scala:50:21, :51:{29,54}]
    .io_in_sign        (io_in[64]),	// @[rawFloatFromRecFN.scala:58:25]
    .io_in_sExp        ({1'h0, io_in[63:52]}),	// @[rawFloatFromRecFN.scala:50:21, :51:54, :59:27]
    .io_in_sig         ({1'h0, |(io_in[63:61]), io_in[51:0]}),	// @[Cat.scala:33:92, rawFloatFromRecFN.scala:50:21, :51:{29,54}, :60:51]
    .io_roundingMode   (io_roundingMode),
    .io_out            (io_out),
    .io_exceptionFlags (io_exceptionFlags)
  );
endmodule

