// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module TLXbar(
  input          clock,
                 reset,
                 auto_in_3_a_valid,
  input  [2:0]   auto_in_3_a_bits_opcode,
                 auto_in_3_a_bits_param,
  input  [3:0]   auto_in_3_a_bits_size,
  input  [1:0]   auto_in_3_a_bits_source,
  input  [31:0]  auto_in_3_a_bits_address,
  input  [15:0]  auto_in_3_a_bits_mask,
  input  [127:0] auto_in_3_a_bits_data,
  input          auto_in_3_a_bits_corrupt,
                 auto_in_3_b_ready,
                 auto_in_3_c_valid,
  input  [2:0]   auto_in_3_c_bits_opcode,
                 auto_in_3_c_bits_param,
  input  [3:0]   auto_in_3_c_bits_size,
  input  [1:0]   auto_in_3_c_bits_source,
  input  [31:0]  auto_in_3_c_bits_address,
  input  [127:0] auto_in_3_c_bits_data,
  input          auto_in_3_c_bits_corrupt,
                 auto_in_3_d_ready,
                 auto_in_3_e_valid,
  input  [3:0]   auto_in_3_e_bits_sink,
  input          auto_in_2_a_valid,
  input  [2:0]   auto_in_2_a_bits_opcode,
                 auto_in_2_a_bits_param,
  input  [3:0]   auto_in_2_a_bits_size,
  input  [2:0]   auto_in_2_a_bits_source,
  input  [31:0]  auto_in_2_a_bits_address,
  input  [15:0]  auto_in_2_a_bits_mask,
  input  [127:0] auto_in_2_a_bits_data,
  input          auto_in_2_a_bits_corrupt,
                 auto_in_2_d_ready,
                 auto_in_1_a_valid,
  input  [2:0]   auto_in_1_a_bits_opcode,
                 auto_in_1_a_bits_param,
  input  [3:0]   auto_in_1_a_bits_size,
  input  [2:0]   auto_in_1_a_bits_source,
  input  [31:0]  auto_in_1_a_bits_address,
  input  [15:0]  auto_in_1_a_bits_mask,
  input  [127:0] auto_in_1_a_bits_data,
  input          auto_in_1_a_bits_corrupt,
                 auto_in_1_d_ready,
                 auto_in_0_a_valid,
  input  [2:0]   auto_in_0_a_bits_opcode,
                 auto_in_0_a_bits_param,
  input  [3:0]   auto_in_0_a_bits_size,
                 auto_in_0_a_bits_source,
  input  [31:0]  auto_in_0_a_bits_address,
  input  [15:0]  auto_in_0_a_bits_mask,
  input  [127:0] auto_in_0_a_bits_data,
  input          auto_in_0_a_bits_corrupt,
                 auto_in_0_d_ready,
                 auto_out_1_a_ready,
                 auto_out_1_b_valid,
  input  [1:0]   auto_out_1_b_bits_param,
  input  [31:0]  auto_out_1_b_bits_address,
  input          auto_out_1_c_ready,
                 auto_out_1_d_valid,
  input  [2:0]   auto_out_1_d_bits_opcode,
  input  [1:0]   auto_out_1_d_bits_param,
  input  [2:0]   auto_out_1_d_bits_size,
  input  [5:0]   auto_out_1_d_bits_source,
  input  [3:0]   auto_out_1_d_bits_sink,
  input          auto_out_1_d_bits_denied,
  input  [127:0] auto_out_1_d_bits_data,
  input          auto_out_1_d_bits_corrupt,
                 auto_out_0_a_ready,
                 auto_out_0_d_valid,
  input  [2:0]   auto_out_0_d_bits_opcode,
  input  [1:0]   auto_out_0_d_bits_param,
  input  [3:0]   auto_out_0_d_bits_size,
  input  [5:0]   auto_out_0_d_bits_source,
  input          auto_out_0_d_bits_sink,
                 auto_out_0_d_bits_denied,
  input  [127:0] auto_out_0_d_bits_data,
  input          auto_out_0_d_bits_corrupt,
  output         auto_in_3_a_ready,
                 auto_in_3_b_valid,
  output [1:0]   auto_in_3_b_bits_param,
  output [31:0]  auto_in_3_b_bits_address,
  output         auto_in_3_c_ready,
                 auto_in_3_d_valid,
  output [2:0]   auto_in_3_d_bits_opcode,
  output [1:0]   auto_in_3_d_bits_param,
  output [3:0]   auto_in_3_d_bits_size,
  output [1:0]   auto_in_3_d_bits_source,
  output [3:0]   auto_in_3_d_bits_sink,
  output         auto_in_3_d_bits_denied,
  output [127:0] auto_in_3_d_bits_data,
  output         auto_in_3_d_bits_corrupt,
                 auto_in_2_a_ready,
                 auto_in_2_d_valid,
  output [2:0]   auto_in_2_d_bits_opcode,
  output [1:0]   auto_in_2_d_bits_param,
  output [3:0]   auto_in_2_d_bits_size,
  output [2:0]   auto_in_2_d_bits_source,
  output [3:0]   auto_in_2_d_bits_sink,
  output         auto_in_2_d_bits_denied,
  output [127:0] auto_in_2_d_bits_data,
  output         auto_in_2_d_bits_corrupt,
                 auto_in_1_a_ready,
                 auto_in_1_d_valid,
  output [2:0]   auto_in_1_d_bits_opcode,
  output [1:0]   auto_in_1_d_bits_param,
  output [3:0]   auto_in_1_d_bits_size,
  output [2:0]   auto_in_1_d_bits_source,
  output [3:0]   auto_in_1_d_bits_sink,
  output         auto_in_1_d_bits_denied,
  output [127:0] auto_in_1_d_bits_data,
  output         auto_in_1_d_bits_corrupt,
                 auto_in_0_a_ready,
                 auto_in_0_d_valid,
  output [2:0]   auto_in_0_d_bits_opcode,
  output [1:0]   auto_in_0_d_bits_param,
  output [3:0]   auto_in_0_d_bits_size,
                 auto_in_0_d_bits_source,
                 auto_in_0_d_bits_sink,
  output         auto_in_0_d_bits_denied,
  output [127:0] auto_in_0_d_bits_data,
  output         auto_in_0_d_bits_corrupt,
                 auto_out_1_a_valid,
  output [2:0]   auto_out_1_a_bits_opcode,
                 auto_out_1_a_bits_param,
                 auto_out_1_a_bits_size,
  output [5:0]   auto_out_1_a_bits_source,
  output [31:0]  auto_out_1_a_bits_address,
  output [15:0]  auto_out_1_a_bits_mask,
  output [127:0] auto_out_1_a_bits_data,
  output         auto_out_1_a_bits_corrupt,
                 auto_out_1_b_ready,
                 auto_out_1_c_valid,
  output [2:0]   auto_out_1_c_bits_opcode,
                 auto_out_1_c_bits_param,
                 auto_out_1_c_bits_size,
  output [5:0]   auto_out_1_c_bits_source,
  output [31:0]  auto_out_1_c_bits_address,
  output [127:0] auto_out_1_c_bits_data,
  output         auto_out_1_c_bits_corrupt,
                 auto_out_1_d_ready,
                 auto_out_1_e_valid,
  output [3:0]   auto_out_1_e_bits_sink,
  output         auto_out_0_a_valid,
  output [2:0]   auto_out_0_a_bits_opcode,
                 auto_out_0_a_bits_param,
  output [3:0]   auto_out_0_a_bits_size,
  output [5:0]   auto_out_0_a_bits_source,
  output [30:0]  auto_out_0_a_bits_address,
  output [15:0]  auto_out_0_a_bits_mask,
  output [127:0] auto_out_0_a_bits_data,
  output         auto_out_0_a_bits_corrupt,
                 auto_out_0_d_ready
);

  wire        allowed_5_1;	// @[Arbiter.scala:122:24]
  wire        allowed_5_0;	// @[Arbiter.scala:122:24]
  wire        allowed_4_1;	// @[Arbiter.scala:122:24]
  wire        allowed_4_0;	// @[Arbiter.scala:122:24]
  wire        allowed_3_1;	// @[Arbiter.scala:122:24]
  wire        allowed_3_0;	// @[Arbiter.scala:122:24]
  wire        allowed_2_1;	// @[Arbiter.scala:122:24]
  wire        allowed_2_0;	// @[Arbiter.scala:122:24]
  wire        allowed_1_3;	// @[Arbiter.scala:122:24]
  wire        allowed_1_2;	// @[Arbiter.scala:122:24]
  wire        allowed_1_1;	// @[Arbiter.scala:122:24]
  wire        allowed_1_0;	// @[Arbiter.scala:122:24]
  wire        allowed_3;	// @[Arbiter.scala:122:24]
  wire        allowed_2;	// @[Arbiter.scala:122:24]
  wire        allowed_1;	// @[Arbiter.scala:122:24]
  wire        allowed_0;	// @[Arbiter.scala:122:24]
  wire [5:0]  portsAOI_filtered_1_bits_source = {2'h0, auto_in_0_a_bits_source};	// @[Bundles.scala:259:74, Xbar.scala:240:29]
  wire [5:0]  portsAOI_filtered_1_1_bits_source = {3'h3, auto_in_1_a_bits_source};	// @[Parameters.scala:54:32, Xbar.scala:240:29]
  wire [5:0]  portsAOI_filtered_2_1_bits_source = {3'h2, auto_in_2_a_bits_source};	// @[Parameters.scala:54:32, Xbar.scala:240:29]
  wire [5:0]  portsAOI_filtered_3_1_bits_source = {4'h8, auto_in_3_a_bits_source};	// @[Parameters.scala:54:32, Xbar.scala:240:55]
  wire [3:0]  out_25_bits_sink = {3'h0, auto_out_0_d_bits_sink};	// @[Bundles.scala:259:74, Xbar.scala:326:28]
  wire [3:0]  out_26_bits_size = {1'h0, auto_out_1_d_bits_size};	// @[BundleMap.scala:247:19]
  wire        requestDOI_0_0 = auto_out_0_d_bits_source[5:4] == 2'h0;	// @[Bundles.scala:259:74, Parameters.scala:54:{10,32}]
  wire        requestDOI_0_1 = auto_out_0_d_bits_source[5:3] == 3'h3;	// @[Parameters.scala:54:{10,32}]
  wire        requestDOI_0_2 = auto_out_0_d_bits_source[5:3] == 3'h2;	// @[Parameters.scala:54:{10,32}]
  wire        requestDOI_0_3 = auto_out_0_d_bits_source[5:2] == 4'h8;	// @[Parameters.scala:54:{10,32}]
  wire        requestDOI_1_0 = auto_out_1_d_bits_source[5:4] == 2'h0;	// @[Bundles.scala:259:74, Parameters.scala:54:{10,32}]
  wire        requestDOI_1_1 = auto_out_1_d_bits_source[5:3] == 3'h3;	// @[Parameters.scala:54:{10,32}]
  wire        requestDOI_1_2 = auto_out_1_d_bits_source[5:3] == 3'h2;	// @[Parameters.scala:54:{10,32}]
  wire        requestDOI_1_3 = auto_out_1_d_bits_source[5:2] == 4'h8;	// @[Parameters.scala:54:{10,32}]
  wire        portsAOI_filtered_0_earlyValid = auto_in_0_a_valid & ~(auto_in_0_a_bits_address[31]);	// @[Parameters.scala:137:{45,65}, Xbar.scala:431:50]
  wire        portsAOI_filtered_1_earlyValid = auto_in_0_a_valid & auto_in_0_a_bits_address[31];	// @[Parameters.scala:137:45, Xbar.scala:431:50]
  wire        _portsAOI_in_0_a_ready_WIRE = ~(auto_in_0_a_bits_address[31]) & auto_out_0_a_ready & allowed_0 | auto_in_0_a_bits_address[31] & auto_out_1_a_ready & allowed_1_0;	// @[Arbiter.scala:122:24, Mux.scala:27:73, Parameters.scala:137:{45,65}]
  wire        portsAOI_filtered_1_0_earlyValid = auto_in_1_a_valid & ~(auto_in_1_a_bits_address[31]);	// @[Parameters.scala:137:{45,65}, Xbar.scala:431:50]
  wire        portsAOI_filtered_1_1_earlyValid = auto_in_1_a_valid & auto_in_1_a_bits_address[31];	// @[Parameters.scala:137:45, Xbar.scala:431:50]
  wire        _portsAOI_in_1_a_ready_WIRE = ~(auto_in_1_a_bits_address[31]) & auto_out_0_a_ready & allowed_1 | auto_in_1_a_bits_address[31] & auto_out_1_a_ready & allowed_1_1;	// @[Arbiter.scala:122:24, Mux.scala:27:73, Parameters.scala:137:{45,65}]
  wire        portsAOI_filtered_2_0_earlyValid = auto_in_2_a_valid & ~(auto_in_2_a_bits_address[31]);	// @[Parameters.scala:137:{45,65}, Xbar.scala:431:50]
  wire        portsAOI_filtered_2_1_earlyValid = auto_in_2_a_valid & auto_in_2_a_bits_address[31];	// @[Parameters.scala:137:45, Xbar.scala:431:50]
  wire        _portsAOI_in_2_a_ready_WIRE = ~(auto_in_2_a_bits_address[31]) & auto_out_0_a_ready & allowed_2 | auto_in_2_a_bits_address[31] & auto_out_1_a_ready & allowed_1_2;	// @[Arbiter.scala:122:24, Mux.scala:27:73, Parameters.scala:137:{45,65}]
  wire        portsAOI_filtered_3_0_earlyValid = auto_in_3_a_valid & ~(auto_in_3_a_bits_address[31]);	// @[Parameters.scala:137:{45,65}, Xbar.scala:431:50]
  wire        portsAOI_filtered_3_1_earlyValid = auto_in_3_a_valid & auto_in_3_a_bits_address[31];	// @[Parameters.scala:137:45, Xbar.scala:431:50]
  wire        _portsAOI_in_3_a_ready_WIRE = ~(auto_in_3_a_bits_address[31]) & auto_out_0_a_ready & allowed_3 | auto_in_3_a_bits_address[31] & auto_out_1_a_ready & allowed_1_3;	// @[Arbiter.scala:122:24, Mux.scala:27:73, Parameters.scala:137:{45,65}]
  wire        out_12_earlyValid = auto_out_0_d_valid & requestDOI_0_0;	// @[Parameters.scala:54:32, Xbar.scala:182:40]
  wire        out_16_earlyValid = auto_out_0_d_valid & requestDOI_0_1;	// @[Parameters.scala:54:32, Xbar.scala:182:40]
  wire        out_20_earlyValid = auto_out_0_d_valid & requestDOI_0_2;	// @[Parameters.scala:54:32, Xbar.scala:182:40]
  wire        out_25_earlyValid = auto_out_0_d_valid & requestDOI_0_3;	// @[Parameters.scala:54:32, Xbar.scala:182:40]
  wire        out_13_earlyValid = auto_out_1_d_valid & requestDOI_1_0;	// @[Parameters.scala:54:32, Xbar.scala:182:40]
  wire        out_17_earlyValid = auto_out_1_d_valid & requestDOI_1_1;	// @[Parameters.scala:54:32, Xbar.scala:182:40]
  wire        out_21_earlyValid = auto_out_1_d_valid & requestDOI_1_2;	// @[Parameters.scala:54:32, Xbar.scala:182:40]
  wire        out_26_earlyValid = auto_out_1_d_valid & requestDOI_1_3;	// @[Parameters.scala:54:32, Xbar.scala:182:40]
  reg  [7:0]  beatsLeft;	// @[Arbiter.scala:88:30]
  wire        idle = beatsLeft == 8'h0;	// @[Arbiter.scala:88:30, :89:28, Edges.scala:221:14]
  wire [3:0]  readys_valid = {portsAOI_filtered_3_0_earlyValid, portsAOI_filtered_2_0_earlyValid, portsAOI_filtered_1_0_earlyValid, portsAOI_filtered_0_earlyValid};	// @[Cat.scala:33:92, Xbar.scala:431:50]
  reg  [3:0]  readys_mask;	// @[Arbiter.scala:24:23]
  wire [3:0]  _readys_filter_T_1 = readys_valid & ~readys_mask;	// @[Arbiter.scala:24:23, :25:{28,30}, Cat.scala:33:92]
  wire [2:0]  _GEN = _readys_filter_T_1[2:0] | _readys_filter_T_1[3:1];	// @[Arbiter.scala:25:28, package.scala:254:43]
  wire        _GEN_0 = portsAOI_filtered_3_0_earlyValid | _readys_filter_T_1[0];	// @[Arbiter.scala:25:28, Xbar.scala:431:50, package.scala:254:43]
  wire [3:0]  readys_readys = ~({readys_mask[3], _readys_filter_T_1[3] | readys_mask[2], _GEN[2] | readys_mask[1], _GEN[1] | _readys_filter_T_1[3] | readys_mask[0]} & {_GEN[0] | _GEN[2], _GEN_0 | _GEN[1], portsAOI_filtered_2_0_earlyValid | portsAOI_filtered_3_0_earlyValid | _GEN[0], portsAOI_filtered_1_0_earlyValid | portsAOI_filtered_2_0_earlyValid | _GEN_0});	// @[Arbiter.scala:24:23, :25:28, :26:58, :27:{18,29,39,48}, Xbar.scala:431:50, package.scala:254:43]
  wire        earlyWinner_0 = readys_readys[0] & portsAOI_filtered_0_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :98:79, Xbar.scala:431:50]
  wire        earlyWinner_1 = readys_readys[1] & portsAOI_filtered_1_0_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :98:79, Xbar.scala:431:50]
  wire        earlyWinner_2 = readys_readys[2] & portsAOI_filtered_2_0_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :98:79, Xbar.scala:431:50]
  wire        earlyWinner_3 = readys_readys[3] & portsAOI_filtered_3_0_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :98:79, Xbar.scala:431:50]
  wire        _out_0_a_earlyValid_T = portsAOI_filtered_0_earlyValid | portsAOI_filtered_1_0_earlyValid;	// @[Arbiter.scala:108:36, Xbar.scala:431:50]
  reg         state_0;	// @[Arbiter.scala:117:26]
  reg         state_1;	// @[Arbiter.scala:117:26]
  reg         state_2;	// @[Arbiter.scala:117:26]
  reg         state_3;	// @[Arbiter.scala:117:26]
  wire        muxStateEarly_0 = idle ? earlyWinner_0 : state_0;	// @[Arbiter.scala:89:28, :98:79, :117:26, :118:30]
  wire        muxStateEarly_1 = idle ? earlyWinner_1 : state_1;	// @[Arbiter.scala:89:28, :98:79, :117:26, :118:30]
  wire        muxStateEarly_2 = idle ? earlyWinner_2 : state_2;	// @[Arbiter.scala:89:28, :98:79, :117:26, :118:30]
  wire        muxStateEarly_3 = idle ? earlyWinner_3 : state_3;	// @[Arbiter.scala:89:28, :98:79, :117:26, :118:30]
  assign allowed_0 = idle ? readys_readys[0] : state_0;	// @[Arbiter.scala:27:18, :89:28, :96:86, :117:26, :122:24]
  assign allowed_1 = idle ? readys_readys[1] : state_1;	// @[Arbiter.scala:27:18, :89:28, :96:86, :117:26, :122:24]
  assign allowed_2 = idle ? readys_readys[2] : state_2;	// @[Arbiter.scala:27:18, :89:28, :96:86, :117:26, :122:24]
  assign allowed_3 = idle ? readys_readys[3] : state_3;	// @[Arbiter.scala:27:18, :89:28, :96:86, :117:26, :122:24]
  wire        x1_out_1_valid = idle ? _out_0_a_earlyValid_T | portsAOI_filtered_2_0_earlyValid | portsAOI_filtered_3_0_earlyValid : state_0 & portsAOI_filtered_0_earlyValid | state_1 & portsAOI_filtered_1_0_earlyValid | state_2 & portsAOI_filtered_2_0_earlyValid | state_3 & portsAOI_filtered_3_0_earlyValid;	// @[Arbiter.scala:89:28, :108:36, :117:26, :126:{29,56}, Mux.scala:27:73, Xbar.scala:431:50]
  reg  [7:0]  beatsLeft_1;	// @[Arbiter.scala:88:30]
  wire        idle_1 = beatsLeft_1 == 8'h0;	// @[Arbiter.scala:88:30, :89:28, Edges.scala:221:14]
  wire [3:0]  readys_valid_1 = {portsAOI_filtered_3_1_earlyValid, portsAOI_filtered_2_1_earlyValid, portsAOI_filtered_1_1_earlyValid, portsAOI_filtered_1_earlyValid};	// @[Cat.scala:33:92, Xbar.scala:431:50]
  reg  [3:0]  readys_mask_1;	// @[Arbiter.scala:24:23]
  wire [3:0]  _readys_filter_T_3 = readys_valid_1 & ~readys_mask_1;	// @[Arbiter.scala:24:23, :25:{28,30}, Cat.scala:33:92]
  wire [2:0]  _GEN_1 = _readys_filter_T_3[2:0] | _readys_filter_T_3[3:1];	// @[Arbiter.scala:25:28, package.scala:254:43]
  wire        _GEN_2 = portsAOI_filtered_3_1_earlyValid | _readys_filter_T_3[0];	// @[Arbiter.scala:25:28, Xbar.scala:431:50, package.scala:254:43]
  wire [3:0]  readys_readys_1 = ~({readys_mask_1[3], _readys_filter_T_3[3] | readys_mask_1[2], _GEN_1[2] | readys_mask_1[1], _GEN_1[1] | _readys_filter_T_3[3] | readys_mask_1[0]} & {_GEN_1[0] | _GEN_1[2], _GEN_2 | _GEN_1[1], portsAOI_filtered_2_1_earlyValid | portsAOI_filtered_3_1_earlyValid | _GEN_1[0], portsAOI_filtered_1_1_earlyValid | portsAOI_filtered_2_1_earlyValid | _GEN_2});	// @[Arbiter.scala:24:23, :25:28, :26:58, :27:{18,29,39,48}, Xbar.scala:431:50, package.scala:254:43]
  wire        earlyWinner_1_0 = readys_readys_1[0] & portsAOI_filtered_1_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :98:79, Xbar.scala:431:50]
  wire        earlyWinner_1_1 = readys_readys_1[1] & portsAOI_filtered_1_1_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :98:79, Xbar.scala:431:50]
  wire        earlyWinner_1_2 = readys_readys_1[2] & portsAOI_filtered_2_1_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :98:79, Xbar.scala:431:50]
  wire        earlyWinner_1_3 = readys_readys_1[3] & portsAOI_filtered_3_1_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :98:79, Xbar.scala:431:50]
  wire        _out_1_a_earlyValid_T = portsAOI_filtered_1_earlyValid | portsAOI_filtered_1_1_earlyValid;	// @[Arbiter.scala:108:36, Xbar.scala:431:50]
  reg         state_1_0;	// @[Arbiter.scala:117:26]
  reg         state_1_1;	// @[Arbiter.scala:117:26]
  reg         state_1_2;	// @[Arbiter.scala:117:26]
  reg         state_1_3;	// @[Arbiter.scala:117:26]
  wire        muxStateEarly_1_0 = idle_1 ? earlyWinner_1_0 : state_1_0;	// @[Arbiter.scala:89:28, :98:79, :117:26, :118:30]
  wire        muxStateEarly_1_1 = idle_1 ? earlyWinner_1_1 : state_1_1;	// @[Arbiter.scala:89:28, :98:79, :117:26, :118:30]
  wire        muxStateEarly_1_2 = idle_1 ? earlyWinner_1_2 : state_1_2;	// @[Arbiter.scala:89:28, :98:79, :117:26, :118:30]
  wire        muxStateEarly_1_3 = idle_1 ? earlyWinner_1_3 : state_1_3;	// @[Arbiter.scala:89:28, :98:79, :117:26, :118:30]
  assign allowed_1_0 = idle_1 ? readys_readys_1[0] : state_1_0;	// @[Arbiter.scala:27:18, :89:28, :96:86, :117:26, :122:24]
  assign allowed_1_1 = idle_1 ? readys_readys_1[1] : state_1_1;	// @[Arbiter.scala:27:18, :89:28, :96:86, :117:26, :122:24]
  assign allowed_1_2 = idle_1 ? readys_readys_1[2] : state_1_2;	// @[Arbiter.scala:27:18, :89:28, :96:86, :117:26, :122:24]
  assign allowed_1_3 = idle_1 ? readys_readys_1[3] : state_1_3;	// @[Arbiter.scala:27:18, :89:28, :96:86, :117:26, :122:24]
  wire        bundleOut_1_out_1_valid = idle_1 ? _out_1_a_earlyValid_T | portsAOI_filtered_2_1_earlyValid | portsAOI_filtered_3_1_earlyValid : state_1_0 & portsAOI_filtered_1_earlyValid | state_1_1 & portsAOI_filtered_1_1_earlyValid | state_1_2 & portsAOI_filtered_2_1_earlyValid | state_1_3 & portsAOI_filtered_3_1_earlyValid;	// @[Arbiter.scala:89:28, :108:36, :117:26, :126:{29,56}, Mux.scala:27:73, Xbar.scala:431:50]
  reg  [7:0]  beatsLeft_2;	// @[Arbiter.scala:88:30]
  wire        idle_2 = beatsLeft_2 == 8'h0;	// @[Arbiter.scala:88:30, :89:28, Edges.scala:221:14]
  wire [1:0]  readys_valid_2 = {out_13_earlyValid, out_12_earlyValid};	// @[Cat.scala:33:92, Xbar.scala:182:40]
  reg  [1:0]  readys_mask_2;	// @[Arbiter.scala:24:23]
  wire [1:0]  _readys_filter_T_5 = readys_valid_2 & ~readys_mask_2;	// @[Arbiter.scala:24:23, :25:{28,30}, Cat.scala:33:92]
  wire [1:0]  readys_readys_2 = ~({readys_mask_2[1], _readys_filter_T_5[1] | readys_mask_2[0]} & {|_readys_filter_T_5, out_13_earlyValid | _readys_filter_T_5[0]});	// @[Arbiter.scala:24:23, :25:28, :26:58, :27:{18,29,39,48}, Xbar.scala:182:40, package.scala:254:43]
  wire        earlyWinner_2_0 = readys_readys_2[0] & out_12_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :98:79, Xbar.scala:182:40]
  wire        earlyWinner_2_1 = readys_readys_2[1] & out_13_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :98:79, Xbar.scala:182:40]
  wire        _sink_ACancel_earlyValid_T = out_12_earlyValid | out_13_earlyValid;	// @[Arbiter.scala:108:36, Xbar.scala:182:40]
  reg         state_2_0;	// @[Arbiter.scala:117:26]
  reg         state_2_1;	// @[Arbiter.scala:117:26]
  wire        muxStateEarly_2_0 = idle_2 ? earlyWinner_2_0 : state_2_0;	// @[Arbiter.scala:89:28, :98:79, :117:26, :118:30]
  wire        muxStateEarly_2_1 = idle_2 ? earlyWinner_2_1 : state_2_1;	// @[Arbiter.scala:89:28, :98:79, :117:26, :118:30]
  assign allowed_2_0 = idle_2 ? readys_readys_2[0] : state_2_0;	// @[Arbiter.scala:27:18, :89:28, :96:86, :117:26, :122:24]
  assign allowed_2_1 = idle_2 ? readys_readys_2[1] : state_2_1;	// @[Arbiter.scala:27:18, :89:28, :96:86, :117:26, :122:24]
  wire        out_14_valid = idle_2 ? _sink_ACancel_earlyValid_T : state_2_0 & out_12_earlyValid | state_2_1 & out_13_earlyValid;	// @[Arbiter.scala:89:28, :108:36, :117:26, :126:29, Mux.scala:27:73, Xbar.scala:182:40]
  wire        out_14_bits_corrupt = muxStateEarly_2_0 & auto_out_0_d_bits_corrupt | muxStateEarly_2_1 & auto_out_1_d_bits_corrupt;	// @[Arbiter.scala:118:30, Mux.scala:27:73]
  wire        out_14_bits_denied = muxStateEarly_2_0 & auto_out_0_d_bits_denied | muxStateEarly_2_1 & auto_out_1_d_bits_denied;	// @[Arbiter.scala:118:30, Mux.scala:27:73]
  wire [3:0]  out_14_bits_sink = (muxStateEarly_2_0 ? out_25_bits_sink : 4'h0) | (muxStateEarly_2_1 ? auto_out_1_d_bits_sink : 4'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73, Xbar.scala:326:28]
  wire [3:0]  out_d_bits_source = (muxStateEarly_2_0 ? auto_out_0_d_bits_source[3:0] : 4'h0) | (muxStateEarly_2_1 ? auto_out_1_d_bits_source[3:0] : 4'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  wire [3:0]  out_14_bits_size = (muxStateEarly_2_0 ? auto_out_0_d_bits_size : 4'h0) | (muxStateEarly_2_1 ? out_26_bits_size : 4'h0);	// @[Arbiter.scala:118:30, BundleMap.scala:247:19, Bundles.scala:259:74, Mux.scala:27:73]
  wire [1:0]  out_14_bits_param = (muxStateEarly_2_0 ? auto_out_0_d_bits_param : 2'h0) | (muxStateEarly_2_1 ? auto_out_1_d_bits_param : 2'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  wire [2:0]  out_14_bits_opcode = (muxStateEarly_2_0 ? auto_out_0_d_bits_opcode : 3'h0) | (muxStateEarly_2_1 ? auto_out_1_d_bits_opcode : 3'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  reg  [7:0]  beatsLeft_3;	// @[Arbiter.scala:88:30]
  wire        idle_3 = beatsLeft_3 == 8'h0;	// @[Arbiter.scala:88:30, :89:28, Edges.scala:221:14]
  wire [1:0]  readys_valid_3 = {out_17_earlyValid, out_16_earlyValid};	// @[Cat.scala:33:92, Xbar.scala:182:40]
  reg  [1:0]  readys_mask_3;	// @[Arbiter.scala:24:23]
  wire [1:0]  _readys_filter_T_7 = readys_valid_3 & ~readys_mask_3;	// @[Arbiter.scala:24:23, :25:{28,30}, Cat.scala:33:92]
  wire [1:0]  readys_readys_3 = ~({readys_mask_3[1], _readys_filter_T_7[1] | readys_mask_3[0]} & {|_readys_filter_T_7, out_17_earlyValid | _readys_filter_T_7[0]});	// @[Arbiter.scala:24:23, :25:28, :26:58, :27:{18,29,39,48}, Xbar.scala:182:40, package.scala:254:43]
  wire        earlyWinner_3_0 = readys_readys_3[0] & out_16_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :98:79, Xbar.scala:182:40]
  wire        earlyWinner_3_1 = readys_readys_3[1] & out_17_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :98:79, Xbar.scala:182:40]
  wire        _sink_ACancel_earlyValid_T_5 = out_16_earlyValid | out_17_earlyValid;	// @[Arbiter.scala:108:36, Xbar.scala:182:40]
  reg         state_3_0;	// @[Arbiter.scala:117:26]
  reg         state_3_1;	// @[Arbiter.scala:117:26]
  wire        muxStateEarly_3_0 = idle_3 ? earlyWinner_3_0 : state_3_0;	// @[Arbiter.scala:89:28, :98:79, :117:26, :118:30]
  wire        muxStateEarly_3_1 = idle_3 ? earlyWinner_3_1 : state_3_1;	// @[Arbiter.scala:89:28, :98:79, :117:26, :118:30]
  assign allowed_3_0 = idle_3 ? readys_readys_3[0] : state_3_0;	// @[Arbiter.scala:27:18, :89:28, :96:86, :117:26, :122:24]
  assign allowed_3_1 = idle_3 ? readys_readys_3[1] : state_3_1;	// @[Arbiter.scala:27:18, :89:28, :96:86, :117:26, :122:24]
  wire        out_18_valid = idle_3 ? _sink_ACancel_earlyValid_T_5 : state_3_0 & out_16_earlyValid | state_3_1 & out_17_earlyValid;	// @[Arbiter.scala:89:28, :108:36, :117:26, :126:29, Mux.scala:27:73, Xbar.scala:182:40]
  wire        out_18_bits_corrupt = muxStateEarly_3_0 & auto_out_0_d_bits_corrupt | muxStateEarly_3_1 & auto_out_1_d_bits_corrupt;	// @[Arbiter.scala:118:30, Mux.scala:27:73]
  wire        out_18_bits_denied = muxStateEarly_3_0 & auto_out_0_d_bits_denied | muxStateEarly_3_1 & auto_out_1_d_bits_denied;	// @[Arbiter.scala:118:30, Mux.scala:27:73]
  wire [3:0]  out_18_bits_sink = (muxStateEarly_3_0 ? out_25_bits_sink : 4'h0) | (muxStateEarly_3_1 ? auto_out_1_d_bits_sink : 4'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73, Xbar.scala:326:28]
  wire [2:0]  out_1_d_bits_source = (muxStateEarly_3_0 ? auto_out_0_d_bits_source[2:0] : 3'h0) | (muxStateEarly_3_1 ? auto_out_1_d_bits_source[2:0] : 3'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  wire [3:0]  out_18_bits_size = (muxStateEarly_3_0 ? auto_out_0_d_bits_size : 4'h0) | (muxStateEarly_3_1 ? out_26_bits_size : 4'h0);	// @[Arbiter.scala:118:30, BundleMap.scala:247:19, Bundles.scala:259:74, Mux.scala:27:73]
  wire [1:0]  out_18_bits_param = (muxStateEarly_3_0 ? auto_out_0_d_bits_param : 2'h0) | (muxStateEarly_3_1 ? auto_out_1_d_bits_param : 2'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  wire [2:0]  out_18_bits_opcode = (muxStateEarly_3_0 ? auto_out_0_d_bits_opcode : 3'h0) | (muxStateEarly_3_1 ? auto_out_1_d_bits_opcode : 3'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  reg  [7:0]  beatsLeft_4;	// @[Arbiter.scala:88:30]
  wire        idle_4 = beatsLeft_4 == 8'h0;	// @[Arbiter.scala:88:30, :89:28, Edges.scala:221:14]
  wire [1:0]  readys_valid_4 = {out_21_earlyValid, out_20_earlyValid};	// @[Cat.scala:33:92, Xbar.scala:182:40]
  reg  [1:0]  readys_mask_4;	// @[Arbiter.scala:24:23]
  wire [1:0]  _readys_filter_T_9 = readys_valid_4 & ~readys_mask_4;	// @[Arbiter.scala:24:23, :25:{28,30}, Cat.scala:33:92]
  wire [1:0]  readys_readys_4 = ~({readys_mask_4[1], _readys_filter_T_9[1] | readys_mask_4[0]} & {|_readys_filter_T_9, out_21_earlyValid | _readys_filter_T_9[0]});	// @[Arbiter.scala:24:23, :25:28, :26:58, :27:{18,29,39,48}, Xbar.scala:182:40, package.scala:254:43]
  wire        earlyWinner_4_0 = readys_readys_4[0] & out_20_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :98:79, Xbar.scala:182:40]
  wire        earlyWinner_4_1 = readys_readys_4[1] & out_21_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :98:79, Xbar.scala:182:40]
  wire        _sink_ACancel_earlyValid_T_10 = out_20_earlyValid | out_21_earlyValid;	// @[Arbiter.scala:108:36, Xbar.scala:182:40]
  reg         state_4_0;	// @[Arbiter.scala:117:26]
  reg         state_4_1;	// @[Arbiter.scala:117:26]
  wire        muxStateEarly_4_0 = idle_4 ? earlyWinner_4_0 : state_4_0;	// @[Arbiter.scala:89:28, :98:79, :117:26, :118:30]
  wire        muxStateEarly_4_1 = idle_4 ? earlyWinner_4_1 : state_4_1;	// @[Arbiter.scala:89:28, :98:79, :117:26, :118:30]
  assign allowed_4_0 = idle_4 ? readys_readys_4[0] : state_4_0;	// @[Arbiter.scala:27:18, :89:28, :96:86, :117:26, :122:24]
  assign allowed_4_1 = idle_4 ? readys_readys_4[1] : state_4_1;	// @[Arbiter.scala:27:18, :89:28, :96:86, :117:26, :122:24]
  wire        out_22_valid = idle_4 ? _sink_ACancel_earlyValid_T_10 : state_4_0 & out_20_earlyValid | state_4_1 & out_21_earlyValid;	// @[Arbiter.scala:89:28, :108:36, :117:26, :126:29, Mux.scala:27:73, Xbar.scala:182:40]
  wire        out_22_bits_corrupt = muxStateEarly_4_0 & auto_out_0_d_bits_corrupt | muxStateEarly_4_1 & auto_out_1_d_bits_corrupt;	// @[Arbiter.scala:118:30, Mux.scala:27:73]
  wire        out_22_bits_denied = muxStateEarly_4_0 & auto_out_0_d_bits_denied | muxStateEarly_4_1 & auto_out_1_d_bits_denied;	// @[Arbiter.scala:118:30, Mux.scala:27:73]
  wire [3:0]  out_22_bits_sink = (muxStateEarly_4_0 ? out_25_bits_sink : 4'h0) | (muxStateEarly_4_1 ? auto_out_1_d_bits_sink : 4'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73, Xbar.scala:326:28]
  wire [2:0]  out_2_d_bits_source = (muxStateEarly_4_0 ? auto_out_0_d_bits_source[2:0] : 3'h0) | (muxStateEarly_4_1 ? auto_out_1_d_bits_source[2:0] : 3'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  wire [3:0]  out_22_bits_size = (muxStateEarly_4_0 ? auto_out_0_d_bits_size : 4'h0) | (muxStateEarly_4_1 ? out_26_bits_size : 4'h0);	// @[Arbiter.scala:118:30, BundleMap.scala:247:19, Bundles.scala:259:74, Mux.scala:27:73]
  wire [1:0]  out_22_bits_param = (muxStateEarly_4_0 ? auto_out_0_d_bits_param : 2'h0) | (muxStateEarly_4_1 ? auto_out_1_d_bits_param : 2'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  wire [2:0]  out_22_bits_opcode = (muxStateEarly_4_0 ? auto_out_0_d_bits_opcode : 3'h0) | (muxStateEarly_4_1 ? auto_out_1_d_bits_opcode : 3'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  reg  [7:0]  beatsLeft_5;	// @[Arbiter.scala:88:30]
  wire        idle_5 = beatsLeft_5 == 8'h0;	// @[Arbiter.scala:88:30, :89:28, Edges.scala:221:14]
  wire [1:0]  readys_valid_5 = {out_26_earlyValid, out_25_earlyValid};	// @[Cat.scala:33:92, Xbar.scala:182:40]
  reg  [1:0]  readys_mask_5;	// @[Arbiter.scala:24:23]
  wire [1:0]  _readys_filter_T_11 = readys_valid_5 & ~readys_mask_5;	// @[Arbiter.scala:24:23, :25:{28,30}, Cat.scala:33:92]
  wire [1:0]  readys_readys_5 = ~({readys_mask_5[1], _readys_filter_T_11[1] | readys_mask_5[0]} & {|_readys_filter_T_11, out_26_earlyValid | _readys_filter_T_11[0]});	// @[Arbiter.scala:24:23, :25:28, :26:58, :27:{18,29,39,48}, Xbar.scala:182:40, package.scala:254:43]
  wire        earlyWinner_5_0 = readys_readys_5[0] & out_25_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :98:79, Xbar.scala:182:40]
  wire        earlyWinner_5_1 = readys_readys_5[1] & out_26_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :98:79, Xbar.scala:182:40]
  wire        _sink_ACancel_earlyValid_T_15 = out_25_earlyValid | out_26_earlyValid;	// @[Arbiter.scala:108:36, Xbar.scala:182:40]
  `ifndef SYNTHESIS	// @[Arbiter.scala:106:13]
    wire prefixOR_2 = earlyWinner_0 | earlyWinner_1;	// @[Arbiter.scala:98:79, :105:53]
    wire _T_34 = portsAOI_filtered_0_earlyValid | portsAOI_filtered_1_0_earlyValid;	// @[Arbiter.scala:109:36, Xbar.scala:431:50]
    wire prefixOR_2_1 = earlyWinner_1_0 | earlyWinner_1_1;	// @[Arbiter.scala:98:79, :105:53]
    wire _T_130 = portsAOI_filtered_1_earlyValid | portsAOI_filtered_1_1_earlyValid;	// @[Arbiter.scala:109:36, Xbar.scala:431:50]
    always @(posedge clock) begin	// @[Arbiter.scala:106:13]
      if (~reset & ~((~earlyWinner_0 | ~earlyWinner_1) & (~prefixOR_2 | ~earlyWinner_2) & (~(prefixOR_2 | earlyWinner_2) | ~earlyWinner_3))) begin	// @[Arbiter.scala:98:79, :105:53, :106:{13,61,64,67,82}]
        if (`ASSERT_VERBOSE_COND_)	// @[Arbiter.scala:106:13]
          $error("Assertion failed\n    at Arbiter.scala:106 assert((prefixOR zip earlyWinner) map { case (p,w) => !p || !w } reduce {_ && _})\n");	// @[Arbiter.scala:106:13]
        if (`STOP_COND_)	// @[Arbiter.scala:106:13]
          $fatal;	// @[Arbiter.scala:106:13]
      end
      if (~reset & ~(~(_out_0_a_earlyValid_T | portsAOI_filtered_2_0_earlyValid | portsAOI_filtered_3_0_earlyValid) | earlyWinner_0 | earlyWinner_1 | earlyWinner_2 | earlyWinner_3)) begin	// @[Arbiter.scala:98:79, :108:{14,15,36,41}, Xbar.scala:431:50]
        if (`ASSERT_VERBOSE_COND_)	// @[Arbiter.scala:108:14]
          $error("Assertion failed\n    at Arbiter.scala:108 assert (!earlyValids.reduce(_||_) || earlyWinner.reduce(_||_))\n");	// @[Arbiter.scala:108:14]
        if (`STOP_COND_)	// @[Arbiter.scala:108:14]
          $fatal;	// @[Arbiter.scala:108:14]
      end
      if (~reset & ~(~(_T_34 | portsAOI_filtered_2_0_earlyValid | portsAOI_filtered_3_0_earlyValid) | _T_34 | portsAOI_filtered_2_0_earlyValid | portsAOI_filtered_3_0_earlyValid)) begin	// @[Arbiter.scala:109:{14,15,36,41}, Xbar.scala:431:50]
        if (`ASSERT_VERBOSE_COND_)	// @[Arbiter.scala:109:14]
          $error("Assertion failed\n    at Arbiter.scala:109 assert (!validQuals .reduce(_||_) || validQuals .reduce(_||_))\n");	// @[Arbiter.scala:109:14]
        if (`STOP_COND_)	// @[Arbiter.scala:109:14]
          $fatal;	// @[Arbiter.scala:109:14]
      end
      if (~reset & ~((~earlyWinner_1_0 | ~earlyWinner_1_1) & (~prefixOR_2_1 | ~earlyWinner_1_2) & (~(prefixOR_2_1 | earlyWinner_1_2) | ~earlyWinner_1_3))) begin	// @[Arbiter.scala:98:79, :105:53, :106:{13,61,64,67,82}]
        if (`ASSERT_VERBOSE_COND_)	// @[Arbiter.scala:106:13]
          $error("Assertion failed\n    at Arbiter.scala:106 assert((prefixOR zip earlyWinner) map { case (p,w) => !p || !w } reduce {_ && _})\n");	// @[Arbiter.scala:106:13]
        if (`STOP_COND_)	// @[Arbiter.scala:106:13]
          $fatal;	// @[Arbiter.scala:106:13]
      end
      if (~reset & ~(~(_out_1_a_earlyValid_T | portsAOI_filtered_2_1_earlyValid | portsAOI_filtered_3_1_earlyValid) | earlyWinner_1_0 | earlyWinner_1_1 | earlyWinner_1_2 | earlyWinner_1_3)) begin	// @[Arbiter.scala:98:79, :108:{14,15,36,41}, Xbar.scala:431:50]
        if (`ASSERT_VERBOSE_COND_)	// @[Arbiter.scala:108:14]
          $error("Assertion failed\n    at Arbiter.scala:108 assert (!earlyValids.reduce(_||_) || earlyWinner.reduce(_||_))\n");	// @[Arbiter.scala:108:14]
        if (`STOP_COND_)	// @[Arbiter.scala:108:14]
          $fatal;	// @[Arbiter.scala:108:14]
      end
      if (~reset & ~(~(_T_130 | portsAOI_filtered_2_1_earlyValid | portsAOI_filtered_3_1_earlyValid) | _T_130 | portsAOI_filtered_2_1_earlyValid | portsAOI_filtered_3_1_earlyValid)) begin	// @[Arbiter.scala:109:{14,15,36,41}, Xbar.scala:431:50]
        if (`ASSERT_VERBOSE_COND_)	// @[Arbiter.scala:109:14]
          $error("Assertion failed\n    at Arbiter.scala:109 assert (!validQuals .reduce(_||_) || validQuals .reduce(_||_))\n");	// @[Arbiter.scala:109:14]
        if (`STOP_COND_)	// @[Arbiter.scala:109:14]
          $fatal;	// @[Arbiter.scala:109:14]
      end
      if (~reset & ~(~earlyWinner_2_0 | ~earlyWinner_2_1)) begin	// @[Arbiter.scala:98:79, :106:{13,61,64,67}]
        if (`ASSERT_VERBOSE_COND_)	// @[Arbiter.scala:106:13]
          $error("Assertion failed\n    at Arbiter.scala:106 assert((prefixOR zip earlyWinner) map { case (p,w) => !p || !w } reduce {_ && _})\n");	// @[Arbiter.scala:106:13]
        if (`STOP_COND_)	// @[Arbiter.scala:106:13]
          $fatal;	// @[Arbiter.scala:106:13]
      end
      if (~reset & ~(~_sink_ACancel_earlyValid_T | earlyWinner_2_0 | earlyWinner_2_1)) begin	// @[Arbiter.scala:98:79, :108:{14,15,36,41}]
        if (`ASSERT_VERBOSE_COND_)	// @[Arbiter.scala:108:14]
          $error("Assertion failed\n    at Arbiter.scala:108 assert (!earlyValids.reduce(_||_) || earlyWinner.reduce(_||_))\n");	// @[Arbiter.scala:108:14]
        if (`STOP_COND_)	// @[Arbiter.scala:108:14]
          $fatal;	// @[Arbiter.scala:108:14]
      end
      if (~reset & ~(~earlyWinner_3_0 | ~earlyWinner_3_1)) begin	// @[Arbiter.scala:98:79, :106:{13,61,64,67}]
        if (`ASSERT_VERBOSE_COND_)	// @[Arbiter.scala:106:13]
          $error("Assertion failed\n    at Arbiter.scala:106 assert((prefixOR zip earlyWinner) map { case (p,w) => !p || !w } reduce {_ && _})\n");	// @[Arbiter.scala:106:13]
        if (`STOP_COND_)	// @[Arbiter.scala:106:13]
          $fatal;	// @[Arbiter.scala:106:13]
      end
      if (~reset & ~(~_sink_ACancel_earlyValid_T_5 | earlyWinner_3_0 | earlyWinner_3_1)) begin	// @[Arbiter.scala:98:79, :108:{14,15,36,41}]
        if (`ASSERT_VERBOSE_COND_)	// @[Arbiter.scala:108:14]
          $error("Assertion failed\n    at Arbiter.scala:108 assert (!earlyValids.reduce(_||_) || earlyWinner.reduce(_||_))\n");	// @[Arbiter.scala:108:14]
        if (`STOP_COND_)	// @[Arbiter.scala:108:14]
          $fatal;	// @[Arbiter.scala:108:14]
      end
      if (~reset & ~(~earlyWinner_4_0 | ~earlyWinner_4_1)) begin	// @[Arbiter.scala:98:79, :106:{13,61,64,67}]
        if (`ASSERT_VERBOSE_COND_)	// @[Arbiter.scala:106:13]
          $error("Assertion failed\n    at Arbiter.scala:106 assert((prefixOR zip earlyWinner) map { case (p,w) => !p || !w } reduce {_ && _})\n");	// @[Arbiter.scala:106:13]
        if (`STOP_COND_)	// @[Arbiter.scala:106:13]
          $fatal;	// @[Arbiter.scala:106:13]
      end
      if (~reset & ~(~_sink_ACancel_earlyValid_T_10 | earlyWinner_4_0 | earlyWinner_4_1)) begin	// @[Arbiter.scala:98:79, :108:{14,15,36,41}]
        if (`ASSERT_VERBOSE_COND_)	// @[Arbiter.scala:108:14]
          $error("Assertion failed\n    at Arbiter.scala:108 assert (!earlyValids.reduce(_||_) || earlyWinner.reduce(_||_))\n");	// @[Arbiter.scala:108:14]
        if (`STOP_COND_)	// @[Arbiter.scala:108:14]
          $fatal;	// @[Arbiter.scala:108:14]
      end
      if (~reset & ~(~earlyWinner_5_0 | ~earlyWinner_5_1)) begin	// @[Arbiter.scala:98:79, :106:{13,61,64,67}]
        if (`ASSERT_VERBOSE_COND_)	// @[Arbiter.scala:106:13]
          $error("Assertion failed\n    at Arbiter.scala:106 assert((prefixOR zip earlyWinner) map { case (p,w) => !p || !w } reduce {_ && _})\n");	// @[Arbiter.scala:106:13]
        if (`STOP_COND_)	// @[Arbiter.scala:106:13]
          $fatal;	// @[Arbiter.scala:106:13]
      end
      if (~reset & ~(~_sink_ACancel_earlyValid_T_15 | earlyWinner_5_0 | earlyWinner_5_1)) begin	// @[Arbiter.scala:98:79, :108:{14,15,36,41}]
        if (`ASSERT_VERBOSE_COND_)	// @[Arbiter.scala:108:14]
          $error("Assertion failed\n    at Arbiter.scala:108 assert (!earlyValids.reduce(_||_) || earlyWinner.reduce(_||_))\n");	// @[Arbiter.scala:108:14]
        if (`STOP_COND_)	// @[Arbiter.scala:108:14]
          $fatal;	// @[Arbiter.scala:108:14]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  reg         state_5_0;	// @[Arbiter.scala:117:26]
  reg         state_5_1;	// @[Arbiter.scala:117:26]
  wire        muxStateEarly_5_0 = idle_5 ? earlyWinner_5_0 : state_5_0;	// @[Arbiter.scala:89:28, :98:79, :117:26, :118:30]
  wire        muxStateEarly_5_1 = idle_5 ? earlyWinner_5_1 : state_5_1;	// @[Arbiter.scala:89:28, :98:79, :117:26, :118:30]
  assign allowed_5_0 = idle_5 ? readys_readys_5[0] : state_5_0;	// @[Arbiter.scala:27:18, :89:28, :96:86, :117:26, :122:24]
  assign allowed_5_1 = idle_5 ? readys_readys_5[1] : state_5_1;	// @[Arbiter.scala:27:18, :89:28, :96:86, :117:26, :122:24]
  wire        out_27_valid = idle_5 ? _sink_ACancel_earlyValid_T_15 : state_5_0 & out_25_earlyValid | state_5_1 & out_26_earlyValid;	// @[Arbiter.scala:89:28, :108:36, :117:26, :126:29, Mux.scala:27:73, Xbar.scala:182:40]
  wire        out_27_bits_corrupt = muxStateEarly_5_0 & auto_out_0_d_bits_corrupt | muxStateEarly_5_1 & auto_out_1_d_bits_corrupt;	// @[Arbiter.scala:118:30, Mux.scala:27:73]
  wire        out_27_bits_denied = muxStateEarly_5_0 & auto_out_0_d_bits_denied | muxStateEarly_5_1 & auto_out_1_d_bits_denied;	// @[Arbiter.scala:118:30, Mux.scala:27:73]
  wire [3:0]  out_27_bits_sink = (muxStateEarly_5_0 ? out_25_bits_sink : 4'h0) | (muxStateEarly_5_1 ? auto_out_1_d_bits_sink : 4'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73, Xbar.scala:326:28]
  wire [1:0]  out_3_d_bits_source = (muxStateEarly_5_0 ? auto_out_0_d_bits_source[1:0] : 2'h0) | (muxStateEarly_5_1 ? auto_out_1_d_bits_source[1:0] : 2'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  wire [3:0]  out_27_bits_size = (muxStateEarly_5_0 ? auto_out_0_d_bits_size : 4'h0) | (muxStateEarly_5_1 ? out_26_bits_size : 4'h0);	// @[Arbiter.scala:118:30, BundleMap.scala:247:19, Bundles.scala:259:74, Mux.scala:27:73]
  wire [1:0]  out_27_bits_param = (muxStateEarly_5_0 ? auto_out_0_d_bits_param : 2'h0) | (muxStateEarly_5_1 ? auto_out_1_d_bits_param : 2'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  wire [2:0]  out_27_bits_opcode = (muxStateEarly_5_0 ? auto_out_0_d_bits_opcode : 3'h0) | (muxStateEarly_5_1 ? auto_out_1_d_bits_opcode : 3'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  wire [3:0]  _readys_mask_T = readys_readys & readys_valid;	// @[Arbiter.scala:27:18, :29:29, Cat.scala:33:92]
  wire [3:0]  _readys_mask_T_3 = _readys_mask_T | {_readys_mask_T[2:0], 1'h0};	// @[Arbiter.scala:29:29, package.scala:245:{43,53}]
  wire [3:0]  _readys_mask_T_8 = readys_readys_1 & readys_valid_1;	// @[Arbiter.scala:27:18, :29:29, Cat.scala:33:92]
  wire [3:0]  _readys_mask_T_11 = _readys_mask_T_8 | {_readys_mask_T_8[2:0], 1'h0};	// @[Arbiter.scala:29:29, package.scala:245:{43,53}]
  wire [1:0]  _readys_mask_T_16 = readys_readys_2 & readys_valid_2;	// @[Arbiter.scala:27:18, :29:29, Cat.scala:33:92]
  wire [1:0]  _readys_mask_T_21 = readys_readys_3 & readys_valid_3;	// @[Arbiter.scala:27:18, :29:29, Cat.scala:33:92]
  wire [1:0]  _readys_mask_T_26 = readys_readys_4 & readys_valid_4;	// @[Arbiter.scala:27:18, :29:29, Cat.scala:33:92]
  wire [1:0]  _readys_mask_T_31 = readys_readys_5 & readys_valid_5;	// @[Arbiter.scala:27:18, :29:29, Cat.scala:33:92]
  wire [26:0] _beatsAI_decode_T_1 = 27'hFFF << auto_in_0_a_bits_size;	// @[package.scala:235:71]
  wire [26:0] _beatsAI_decode_T_5 = 27'hFFF << auto_in_1_a_bits_size;	// @[package.scala:235:71]
  wire [26:0] _beatsAI_decode_T_9 = 27'hFFF << auto_in_2_a_bits_size;	// @[package.scala:235:71]
  wire [26:0] _beatsAI_decode_T_13 = 27'hFFF << auto_in_3_a_bits_size;	// @[package.scala:235:71]
  wire [26:0] _beatsDO_decode_T_1 = 27'hFFF << auto_out_0_d_bits_size;	// @[package.scala:235:71]
  wire [20:0] _beatsDO_decode_T_5 = 21'h3F << auto_out_1_d_bits_size;	// @[package.scala:235:71]
  wire        latch = idle & auto_out_0_a_ready;	// @[Arbiter.scala:89:28, :90:24]
  wire        winnerQual_0 = readys_readys[0] & portsAOI_filtered_0_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :99:79, Xbar.scala:431:50]
  wire        winnerQual_1 = readys_readys[1] & portsAOI_filtered_1_0_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :99:79, Xbar.scala:431:50]
  wire        winnerQual_2 = readys_readys[2] & portsAOI_filtered_2_0_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :99:79, Xbar.scala:431:50]
  wire        winnerQual_3 = readys_readys[3] & portsAOI_filtered_3_0_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :99:79, Xbar.scala:431:50]
  wire        latch_1 = idle_1 & auto_out_1_a_ready;	// @[Arbiter.scala:89:28, :90:24]
  wire        winnerQual_1_0 = readys_readys_1[0] & portsAOI_filtered_1_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :99:79, Xbar.scala:431:50]
  wire        winnerQual_1_1 = readys_readys_1[1] & portsAOI_filtered_1_1_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :99:79, Xbar.scala:431:50]
  wire        winnerQual_1_2 = readys_readys_1[2] & portsAOI_filtered_2_1_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :99:79, Xbar.scala:431:50]
  wire        winnerQual_1_3 = readys_readys_1[3] & portsAOI_filtered_3_1_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :99:79, Xbar.scala:431:50]
  wire        latch_2 = idle_2 & auto_in_0_d_ready;	// @[Arbiter.scala:89:28, :90:24]
  wire        winnerQual_2_0 = readys_readys_2[0] & out_12_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :99:79, Xbar.scala:182:40]
  wire        winnerQual_2_1 = readys_readys_2[1] & out_13_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :99:79, Xbar.scala:182:40]
  wire        latch_3 = idle_3 & auto_in_1_d_ready;	// @[Arbiter.scala:89:28, :90:24]
  wire        winnerQual_3_0 = readys_readys_3[0] & out_16_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :99:79, Xbar.scala:182:40]
  wire        winnerQual_3_1 = readys_readys_3[1] & out_17_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :99:79, Xbar.scala:182:40]
  wire        latch_4 = idle_4 & auto_in_2_d_ready;	// @[Arbiter.scala:89:28, :90:24]
  wire        winnerQual_4_0 = readys_readys_4[0] & out_20_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :99:79, Xbar.scala:182:40]
  wire        winnerQual_4_1 = readys_readys_4[1] & out_21_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :99:79, Xbar.scala:182:40]
  wire        latch_5 = idle_5 & auto_in_3_d_ready;	// @[Arbiter.scala:89:28, :90:24]
  wire        winnerQual_5_0 = readys_readys_5[0] & out_25_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :99:79, Xbar.scala:182:40]
  wire        winnerQual_5_1 = readys_readys_5[1] & out_26_earlyValid;	// @[Arbiter.scala:27:18, :96:86, :99:79, Xbar.scala:182:40]
  always @(posedge clock) begin
    if (reset) begin
      beatsLeft <= 8'h0;	// @[Arbiter.scala:88:30, Edges.scala:221:14]
      readys_mask <= 4'hF;	// @[Arbiter.scala:24:23, Parameters.scala:57:20]
      state_0 <= 1'h0;	// @[Arbiter.scala:117:26]
      state_1 <= 1'h0;	// @[Arbiter.scala:117:26]
      state_2 <= 1'h0;	// @[Arbiter.scala:117:26]
      state_3 <= 1'h0;	// @[Arbiter.scala:117:26]
      beatsLeft_1 <= 8'h0;	// @[Arbiter.scala:88:30, Edges.scala:221:14]
      readys_mask_1 <= 4'hF;	// @[Arbiter.scala:24:23, Parameters.scala:57:20]
      state_1_0 <= 1'h0;	// @[Arbiter.scala:117:26]
      state_1_1 <= 1'h0;	// @[Arbiter.scala:117:26]
      state_1_2 <= 1'h0;	// @[Arbiter.scala:117:26]
      state_1_3 <= 1'h0;	// @[Arbiter.scala:117:26]
      beatsLeft_2 <= 8'h0;	// @[Arbiter.scala:88:30, Edges.scala:221:14]
      readys_mask_2 <= 2'h3;	// @[Arbiter.scala:24:23, Parameters.scala:54:32]
      state_2_0 <= 1'h0;	// @[Arbiter.scala:117:26]
      state_2_1 <= 1'h0;	// @[Arbiter.scala:117:26]
      beatsLeft_3 <= 8'h0;	// @[Arbiter.scala:88:30, Edges.scala:221:14]
      readys_mask_3 <= 2'h3;	// @[Arbiter.scala:24:23, Parameters.scala:54:32]
      state_3_0 <= 1'h0;	// @[Arbiter.scala:117:26]
      state_3_1 <= 1'h0;	// @[Arbiter.scala:117:26]
      beatsLeft_4 <= 8'h0;	// @[Arbiter.scala:88:30, Edges.scala:221:14]
      readys_mask_4 <= 2'h3;	// @[Arbiter.scala:24:23, Parameters.scala:54:32]
      state_4_0 <= 1'h0;	// @[Arbiter.scala:117:26]
      state_4_1 <= 1'h0;	// @[Arbiter.scala:117:26]
      beatsLeft_5 <= 8'h0;	// @[Arbiter.scala:88:30, Edges.scala:221:14]
      readys_mask_5 <= 2'h3;	// @[Arbiter.scala:24:23, Parameters.scala:54:32]
      state_5_0 <= 1'h0;	// @[Arbiter.scala:117:26]
      state_5_1 <= 1'h0;	// @[Arbiter.scala:117:26]
    end
    else begin
      if (latch)	// @[Arbiter.scala:90:24]
        beatsLeft <= (winnerQual_0 & ~(auto_in_0_a_bits_opcode[2]) ? ~(_beatsAI_decode_T_1[11:4]) : 8'h0) | (winnerQual_1 & ~(auto_in_1_a_bits_opcode[2]) ? ~(_beatsAI_decode_T_5[11:4]) : 8'h0) | (winnerQual_2 & ~(auto_in_2_a_bits_opcode[2]) ? ~(_beatsAI_decode_T_9[11:4]) : 8'h0) | (winnerQual_3 & ~(auto_in_3_a_bits_opcode[2]) ? ~(_beatsAI_decode_T_13[11:4]) : 8'h0);	// @[Arbiter.scala:88:30, :99:79, :112:73, :113:44, Edges.scala:92:{28,37}, :221:14, package.scala:235:{46,71,76}]
      else	// @[Arbiter.scala:90:24]
        beatsLeft <= beatsLeft - {7'h0, auto_out_0_a_ready & x1_out_1_valid};	// @[Arbiter.scala:88:30, :114:52, :126:29, ReadyValidCancel.scala:49:33]
      if (latch & (|readys_valid))	// @[Arbiter.scala:28:{18,27}, :90:24, Cat.scala:33:92]
        readys_mask <= _readys_mask_T_3 | {_readys_mask_T_3[1:0], 2'h0};	// @[Arbiter.scala:24:23, Bundles.scala:259:74, package.scala:245:{43,53}]
      if (idle) begin	// @[Arbiter.scala:89:28]
        state_0 <= winnerQual_0;	// @[Arbiter.scala:99:79, :117:26]
        state_1 <= winnerQual_1;	// @[Arbiter.scala:99:79, :117:26]
        state_2 <= winnerQual_2;	// @[Arbiter.scala:99:79, :117:26]
        state_3 <= winnerQual_3;	// @[Arbiter.scala:99:79, :117:26]
      end
      if (latch_1)	// @[Arbiter.scala:90:24]
        beatsLeft_1 <= (winnerQual_1_0 & ~(auto_in_0_a_bits_opcode[2]) ? ~(_beatsAI_decode_T_1[11:4]) : 8'h0) | (winnerQual_1_1 & ~(auto_in_1_a_bits_opcode[2]) ? ~(_beatsAI_decode_T_5[11:4]) : 8'h0) | (winnerQual_1_2 & ~(auto_in_2_a_bits_opcode[2]) ? ~(_beatsAI_decode_T_9[11:4]) : 8'h0) | (winnerQual_1_3 & ~(auto_in_3_a_bits_opcode[2]) ? ~(_beatsAI_decode_T_13[11:4]) : 8'h0);	// @[Arbiter.scala:88:30, :99:79, :112:73, :113:44, Edges.scala:92:{28,37}, :221:14, package.scala:235:{46,71,76}]
      else	// @[Arbiter.scala:90:24]
        beatsLeft_1 <= beatsLeft_1 - {7'h0, auto_out_1_a_ready & bundleOut_1_out_1_valid};	// @[Arbiter.scala:88:30, :114:52, :126:29, ReadyValidCancel.scala:49:33]
      if (latch_1 & (|readys_valid_1))	// @[Arbiter.scala:28:{18,27}, :90:24, Cat.scala:33:92]
        readys_mask_1 <= _readys_mask_T_11 | {_readys_mask_T_11[1:0], 2'h0};	// @[Arbiter.scala:24:23, Bundles.scala:259:74, package.scala:245:{43,53}]
      if (idle_1) begin	// @[Arbiter.scala:89:28]
        state_1_0 <= winnerQual_1_0;	// @[Arbiter.scala:99:79, :117:26]
        state_1_1 <= winnerQual_1_1;	// @[Arbiter.scala:99:79, :117:26]
        state_1_2 <= winnerQual_1_2;	// @[Arbiter.scala:99:79, :117:26]
        state_1_3 <= winnerQual_1_3;	// @[Arbiter.scala:99:79, :117:26]
      end
      if (latch_2)	// @[Arbiter.scala:90:24]
        beatsLeft_2 <= (winnerQual_2_0 & auto_out_0_d_bits_opcode[0] ? ~(_beatsDO_decode_T_1[11:4]) : 8'h0) | {6'h0, winnerQual_2_1 & auto_out_1_d_bits_opcode[0] ? ~(_beatsDO_decode_T_5[5:4]) : 2'h0};	// @[Arbiter.scala:88:30, :99:79, :112:73, :113:44, Bundles.scala:259:74, Edges.scala:106:36, :221:14, Xbar.scala:265:23, package.scala:235:{46,71,76}]
      else	// @[Arbiter.scala:90:24]
        beatsLeft_2 <= beatsLeft_2 - {7'h0, auto_in_0_d_ready & out_14_valid};	// @[Arbiter.scala:88:30, :114:52, :126:29, ReadyValidCancel.scala:49:33]
      if (latch_2 & (|readys_valid_2))	// @[Arbiter.scala:28:{18,27}, :90:24, Cat.scala:33:92]
        readys_mask_2 <= _readys_mask_T_16 | {_readys_mask_T_16[0], 1'h0};	// @[Arbiter.scala:24:23, :29:29, package.scala:245:{43,53}]
      if (idle_2) begin	// @[Arbiter.scala:89:28]
        state_2_0 <= winnerQual_2_0;	// @[Arbiter.scala:99:79, :117:26]
        state_2_1 <= winnerQual_2_1;	// @[Arbiter.scala:99:79, :117:26]
      end
      if (latch_3)	// @[Arbiter.scala:90:24]
        beatsLeft_3 <= (winnerQual_3_0 & auto_out_0_d_bits_opcode[0] ? ~(_beatsDO_decode_T_1[11:4]) : 8'h0) | {6'h0, winnerQual_3_1 & auto_out_1_d_bits_opcode[0] ? ~(_beatsDO_decode_T_5[5:4]) : 2'h0};	// @[Arbiter.scala:88:30, :99:79, :112:73, :113:44, Bundles.scala:259:74, Edges.scala:106:36, :221:14, Xbar.scala:265:23, package.scala:235:{46,71,76}]
      else	// @[Arbiter.scala:90:24]
        beatsLeft_3 <= beatsLeft_3 - {7'h0, auto_in_1_d_ready & out_18_valid};	// @[Arbiter.scala:88:30, :114:52, :126:29, ReadyValidCancel.scala:49:33]
      if (latch_3 & (|readys_valid_3))	// @[Arbiter.scala:28:{18,27}, :90:24, Cat.scala:33:92]
        readys_mask_3 <= _readys_mask_T_21 | {_readys_mask_T_21[0], 1'h0};	// @[Arbiter.scala:24:23, :29:29, package.scala:245:{43,53}]
      if (idle_3) begin	// @[Arbiter.scala:89:28]
        state_3_0 <= winnerQual_3_0;	// @[Arbiter.scala:99:79, :117:26]
        state_3_1 <= winnerQual_3_1;	// @[Arbiter.scala:99:79, :117:26]
      end
      if (latch_4)	// @[Arbiter.scala:90:24]
        beatsLeft_4 <= (winnerQual_4_0 & auto_out_0_d_bits_opcode[0] ? ~(_beatsDO_decode_T_1[11:4]) : 8'h0) | {6'h0, winnerQual_4_1 & auto_out_1_d_bits_opcode[0] ? ~(_beatsDO_decode_T_5[5:4]) : 2'h0};	// @[Arbiter.scala:88:30, :99:79, :112:73, :113:44, Bundles.scala:259:74, Edges.scala:106:36, :221:14, Xbar.scala:265:23, package.scala:235:{46,71,76}]
      else	// @[Arbiter.scala:90:24]
        beatsLeft_4 <= beatsLeft_4 - {7'h0, auto_in_2_d_ready & out_22_valid};	// @[Arbiter.scala:88:30, :114:52, :126:29, ReadyValidCancel.scala:49:33]
      if (latch_4 & (|readys_valid_4))	// @[Arbiter.scala:28:{18,27}, :90:24, Cat.scala:33:92]
        readys_mask_4 <= _readys_mask_T_26 | {_readys_mask_T_26[0], 1'h0};	// @[Arbiter.scala:24:23, :29:29, package.scala:245:{43,53}]
      if (idle_4) begin	// @[Arbiter.scala:89:28]
        state_4_0 <= winnerQual_4_0;	// @[Arbiter.scala:99:79, :117:26]
        state_4_1 <= winnerQual_4_1;	// @[Arbiter.scala:99:79, :117:26]
      end
      if (latch_5)	// @[Arbiter.scala:90:24]
        beatsLeft_5 <= (winnerQual_5_0 & auto_out_0_d_bits_opcode[0] ? ~(_beatsDO_decode_T_1[11:4]) : 8'h0) | {6'h0, winnerQual_5_1 & auto_out_1_d_bits_opcode[0] ? ~(_beatsDO_decode_T_5[5:4]) : 2'h0};	// @[Arbiter.scala:88:30, :99:79, :112:73, :113:44, Bundles.scala:259:74, Edges.scala:106:36, :221:14, Xbar.scala:265:23, package.scala:235:{46,71,76}]
      else	// @[Arbiter.scala:90:24]
        beatsLeft_5 <= beatsLeft_5 - {7'h0, auto_in_3_d_ready & out_27_valid};	// @[Arbiter.scala:88:30, :114:52, :126:29, ReadyValidCancel.scala:49:33]
      if (latch_5 & (|readys_valid_5))	// @[Arbiter.scala:28:{18,27}, :90:24, Cat.scala:33:92]
        readys_mask_5 <= _readys_mask_T_31 | {_readys_mask_T_31[0], 1'h0};	// @[Arbiter.scala:24:23, :29:29, package.scala:245:{43,53}]
      if (idle_5) begin	// @[Arbiter.scala:89:28]
        state_5_0 <= winnerQual_5_0;	// @[Arbiter.scala:99:79, :117:26]
        state_5_1 <= winnerQual_5_1;	// @[Arbiter.scala:99:79, :117:26]
      end
    end
  end // always @(posedge)
  TLMonitor monitor (	// @[Nodes.scala:24:25]
    .clock                (clock),
    .reset                (reset),
    .io_in_a_ready        (_portsAOI_in_0_a_ready_WIRE),	// @[Mux.scala:27:73]
    .io_in_a_valid        (auto_in_0_a_valid),
    .io_in_a_bits_opcode  (auto_in_0_a_bits_opcode),
    .io_in_a_bits_param   (auto_in_0_a_bits_param),
    .io_in_a_bits_size    (auto_in_0_a_bits_size),
    .io_in_a_bits_source  (auto_in_0_a_bits_source),
    .io_in_a_bits_address (auto_in_0_a_bits_address),
    .io_in_a_bits_mask    (auto_in_0_a_bits_mask),
    .io_in_a_bits_corrupt (auto_in_0_a_bits_corrupt),
    .io_in_d_ready        (auto_in_0_d_ready),
    .io_in_d_valid        (out_14_valid),	// @[Arbiter.scala:126:29]
    .io_in_d_bits_opcode  (out_14_bits_opcode),	// @[Mux.scala:27:73]
    .io_in_d_bits_param   (out_14_bits_param),	// @[Mux.scala:27:73]
    .io_in_d_bits_size    (out_14_bits_size),	// @[Mux.scala:27:73]
    .io_in_d_bits_source  (out_d_bits_source),	// @[Mux.scala:27:73]
    .io_in_d_bits_sink    (out_14_bits_sink),	// @[Mux.scala:27:73]
    .io_in_d_bits_denied  (out_14_bits_denied),	// @[Mux.scala:27:73]
    .io_in_d_bits_corrupt (out_14_bits_corrupt)	// @[Mux.scala:27:73]
  );
  TLMonitor_1 monitor_1 (	// @[Nodes.scala:24:25]
    .clock                (clock),
    .reset                (reset),
    .io_in_a_ready        (_portsAOI_in_1_a_ready_WIRE),	// @[Mux.scala:27:73]
    .io_in_a_valid        (auto_in_1_a_valid),
    .io_in_a_bits_opcode  (auto_in_1_a_bits_opcode),
    .io_in_a_bits_param   (auto_in_1_a_bits_param),
    .io_in_a_bits_size    (auto_in_1_a_bits_size),
    .io_in_a_bits_source  (auto_in_1_a_bits_source),
    .io_in_a_bits_address (auto_in_1_a_bits_address),
    .io_in_a_bits_mask    (auto_in_1_a_bits_mask),
    .io_in_a_bits_corrupt (auto_in_1_a_bits_corrupt),
    .io_in_d_ready        (auto_in_1_d_ready),
    .io_in_d_valid        (out_18_valid),	// @[Arbiter.scala:126:29]
    .io_in_d_bits_opcode  (out_18_bits_opcode),	// @[Mux.scala:27:73]
    .io_in_d_bits_param   (out_18_bits_param),	// @[Mux.scala:27:73]
    .io_in_d_bits_size    (out_18_bits_size),	// @[Mux.scala:27:73]
    .io_in_d_bits_source  (out_1_d_bits_source),	// @[Mux.scala:27:73]
    .io_in_d_bits_sink    (out_18_bits_sink),	// @[Mux.scala:27:73]
    .io_in_d_bits_denied  (out_18_bits_denied),	// @[Mux.scala:27:73]
    .io_in_d_bits_corrupt (out_18_bits_corrupt)	// @[Mux.scala:27:73]
  );
  TLMonitor_1 monitor_2 (	// @[Nodes.scala:24:25]
    .clock                (clock),
    .reset                (reset),
    .io_in_a_ready        (_portsAOI_in_2_a_ready_WIRE),	// @[Mux.scala:27:73]
    .io_in_a_valid        (auto_in_2_a_valid),
    .io_in_a_bits_opcode  (auto_in_2_a_bits_opcode),
    .io_in_a_bits_param   (auto_in_2_a_bits_param),
    .io_in_a_bits_size    (auto_in_2_a_bits_size),
    .io_in_a_bits_source  (auto_in_2_a_bits_source),
    .io_in_a_bits_address (auto_in_2_a_bits_address),
    .io_in_a_bits_mask    (auto_in_2_a_bits_mask),
    .io_in_a_bits_corrupt (auto_in_2_a_bits_corrupt),
    .io_in_d_ready        (auto_in_2_d_ready),
    .io_in_d_valid        (out_22_valid),	// @[Arbiter.scala:126:29]
    .io_in_d_bits_opcode  (out_22_bits_opcode),	// @[Mux.scala:27:73]
    .io_in_d_bits_param   (out_22_bits_param),	// @[Mux.scala:27:73]
    .io_in_d_bits_size    (out_22_bits_size),	// @[Mux.scala:27:73]
    .io_in_d_bits_source  (out_2_d_bits_source),	// @[Mux.scala:27:73]
    .io_in_d_bits_sink    (out_22_bits_sink),	// @[Mux.scala:27:73]
    .io_in_d_bits_denied  (out_22_bits_denied),	// @[Mux.scala:27:73]
    .io_in_d_bits_corrupt (out_22_bits_corrupt)	// @[Mux.scala:27:73]
  );
  TLMonitor_3 monitor_3 (	// @[Nodes.scala:24:25]
    .clock                (clock),
    .reset                (reset),
    .io_in_a_ready        (_portsAOI_in_3_a_ready_WIRE),	// @[Mux.scala:27:73]
    .io_in_a_valid        (auto_in_3_a_valid),
    .io_in_a_bits_opcode  (auto_in_3_a_bits_opcode),
    .io_in_a_bits_param   (auto_in_3_a_bits_param),
    .io_in_a_bits_size    (auto_in_3_a_bits_size),
    .io_in_a_bits_source  (auto_in_3_a_bits_source),
    .io_in_a_bits_address (auto_in_3_a_bits_address),
    .io_in_a_bits_mask    (auto_in_3_a_bits_mask),
    .io_in_a_bits_corrupt (auto_in_3_a_bits_corrupt),
    .io_in_b_valid        (auto_out_1_b_valid),
    .io_in_b_bits_param   (auto_out_1_b_bits_param),
    .io_in_b_bits_size    (4'h6),	// @[BundleMap.scala:247:19]
    .io_in_b_bits_source  (2'h0),	// @[Bundles.scala:259:74]
    .io_in_b_bits_address (auto_out_1_b_bits_address),
    .io_in_c_ready        (auto_out_1_c_ready),
    .io_in_c_valid        (auto_in_3_c_valid),
    .io_in_c_bits_opcode  (auto_in_3_c_bits_opcode),
    .io_in_c_bits_param   (auto_in_3_c_bits_param),
    .io_in_c_bits_size    (auto_in_3_c_bits_size),
    .io_in_c_bits_source  (auto_in_3_c_bits_source),
    .io_in_c_bits_address (auto_in_3_c_bits_address),
    .io_in_c_bits_corrupt (auto_in_3_c_bits_corrupt),
    .io_in_d_ready        (auto_in_3_d_ready),
    .io_in_d_valid        (out_27_valid),	// @[Arbiter.scala:126:29]
    .io_in_d_bits_opcode  (out_27_bits_opcode),	// @[Mux.scala:27:73]
    .io_in_d_bits_param   (out_27_bits_param),	// @[Mux.scala:27:73]
    .io_in_d_bits_size    (out_27_bits_size),	// @[Mux.scala:27:73]
    .io_in_d_bits_source  (out_3_d_bits_source),	// @[Mux.scala:27:73]
    .io_in_d_bits_sink    (out_27_bits_sink),	// @[Mux.scala:27:73]
    .io_in_d_bits_denied  (out_27_bits_denied),	// @[Mux.scala:27:73]
    .io_in_d_bits_corrupt (out_27_bits_corrupt),	// @[Mux.scala:27:73]
    .io_in_e_valid        (auto_in_3_e_valid),
    .io_in_e_bits_sink    (auto_in_3_e_bits_sink)
  );
  assign auto_in_3_a_ready = _portsAOI_in_3_a_ready_WIRE;	// @[Mux.scala:27:73]
  assign auto_in_3_b_valid = auto_out_1_b_valid;
  assign auto_in_3_b_bits_param = auto_out_1_b_bits_param;
  assign auto_in_3_b_bits_address = auto_out_1_b_bits_address;
  assign auto_in_3_c_ready = auto_out_1_c_ready;
  assign auto_in_3_d_valid = out_27_valid;	// @[Arbiter.scala:126:29]
  assign auto_in_3_d_bits_opcode = out_27_bits_opcode;	// @[Mux.scala:27:73]
  assign auto_in_3_d_bits_param = out_27_bits_param;	// @[Mux.scala:27:73]
  assign auto_in_3_d_bits_size = out_27_bits_size;	// @[Mux.scala:27:73]
  assign auto_in_3_d_bits_source = out_3_d_bits_source;	// @[Mux.scala:27:73]
  assign auto_in_3_d_bits_sink = out_27_bits_sink;	// @[Mux.scala:27:73]
  assign auto_in_3_d_bits_denied = out_27_bits_denied;	// @[Mux.scala:27:73]
  assign auto_in_3_d_bits_data = (muxStateEarly_5_0 ? auto_out_0_d_bits_data : 128'h0) | (muxStateEarly_5_1 ? auto_out_1_d_bits_data : 128'h0);	// @[Arbiter.scala:118:30, Mux.scala:27:73]
  assign auto_in_3_d_bits_corrupt = out_27_bits_corrupt;	// @[Mux.scala:27:73]
  assign auto_in_2_a_ready = _portsAOI_in_2_a_ready_WIRE;	// @[Mux.scala:27:73]
  assign auto_in_2_d_valid = out_22_valid;	// @[Arbiter.scala:126:29]
  assign auto_in_2_d_bits_opcode = out_22_bits_opcode;	// @[Mux.scala:27:73]
  assign auto_in_2_d_bits_param = out_22_bits_param;	// @[Mux.scala:27:73]
  assign auto_in_2_d_bits_size = out_22_bits_size;	// @[Mux.scala:27:73]
  assign auto_in_2_d_bits_source = out_2_d_bits_source;	// @[Mux.scala:27:73]
  assign auto_in_2_d_bits_sink = out_22_bits_sink;	// @[Mux.scala:27:73]
  assign auto_in_2_d_bits_denied = out_22_bits_denied;	// @[Mux.scala:27:73]
  assign auto_in_2_d_bits_data = (muxStateEarly_4_0 ? auto_out_0_d_bits_data : 128'h0) | (muxStateEarly_4_1 ? auto_out_1_d_bits_data : 128'h0);	// @[Arbiter.scala:118:30, Mux.scala:27:73]
  assign auto_in_2_d_bits_corrupt = out_22_bits_corrupt;	// @[Mux.scala:27:73]
  assign auto_in_1_a_ready = _portsAOI_in_1_a_ready_WIRE;	// @[Mux.scala:27:73]
  assign auto_in_1_d_valid = out_18_valid;	// @[Arbiter.scala:126:29]
  assign auto_in_1_d_bits_opcode = out_18_bits_opcode;	// @[Mux.scala:27:73]
  assign auto_in_1_d_bits_param = out_18_bits_param;	// @[Mux.scala:27:73]
  assign auto_in_1_d_bits_size = out_18_bits_size;	// @[Mux.scala:27:73]
  assign auto_in_1_d_bits_source = out_1_d_bits_source;	// @[Mux.scala:27:73]
  assign auto_in_1_d_bits_sink = out_18_bits_sink;	// @[Mux.scala:27:73]
  assign auto_in_1_d_bits_denied = out_18_bits_denied;	// @[Mux.scala:27:73]
  assign auto_in_1_d_bits_data = (muxStateEarly_3_0 ? auto_out_0_d_bits_data : 128'h0) | (muxStateEarly_3_1 ? auto_out_1_d_bits_data : 128'h0);	// @[Arbiter.scala:118:30, Mux.scala:27:73]
  assign auto_in_1_d_bits_corrupt = out_18_bits_corrupt;	// @[Mux.scala:27:73]
  assign auto_in_0_a_ready = _portsAOI_in_0_a_ready_WIRE;	// @[Mux.scala:27:73]
  assign auto_in_0_d_valid = out_14_valid;	// @[Arbiter.scala:126:29]
  assign auto_in_0_d_bits_opcode = out_14_bits_opcode;	// @[Mux.scala:27:73]
  assign auto_in_0_d_bits_param = out_14_bits_param;	// @[Mux.scala:27:73]
  assign auto_in_0_d_bits_size = out_14_bits_size;	// @[Mux.scala:27:73]
  assign auto_in_0_d_bits_source = out_d_bits_source;	// @[Mux.scala:27:73]
  assign auto_in_0_d_bits_sink = out_14_bits_sink;	// @[Mux.scala:27:73]
  assign auto_in_0_d_bits_denied = out_14_bits_denied;	// @[Mux.scala:27:73]
  assign auto_in_0_d_bits_data = (muxStateEarly_2_0 ? auto_out_0_d_bits_data : 128'h0) | (muxStateEarly_2_1 ? auto_out_1_d_bits_data : 128'h0);	// @[Arbiter.scala:118:30, Mux.scala:27:73]
  assign auto_in_0_d_bits_corrupt = out_14_bits_corrupt;	// @[Mux.scala:27:73]
  assign auto_out_1_a_valid = bundleOut_1_out_1_valid;	// @[Arbiter.scala:126:29]
  assign auto_out_1_a_bits_opcode = (muxStateEarly_1_0 ? auto_in_0_a_bits_opcode : 3'h0) | (muxStateEarly_1_1 ? auto_in_1_a_bits_opcode : 3'h0) | (muxStateEarly_1_2 ? auto_in_2_a_bits_opcode : 3'h0) | (muxStateEarly_1_3 ? auto_in_3_a_bits_opcode : 3'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  assign auto_out_1_a_bits_param = (muxStateEarly_1_0 ? auto_in_0_a_bits_param : 3'h0) | (muxStateEarly_1_1 ? auto_in_1_a_bits_param : 3'h0) | (muxStateEarly_1_2 ? auto_in_2_a_bits_param : 3'h0) | (muxStateEarly_1_3 ? auto_in_3_a_bits_param : 3'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  assign auto_out_1_a_bits_size = (muxStateEarly_1_0 ? auto_in_0_a_bits_size[2:0] : 3'h0) | (muxStateEarly_1_1 ? auto_in_1_a_bits_size[2:0] : 3'h0) | (muxStateEarly_1_2 ? auto_in_2_a_bits_size[2:0] : 3'h0) | (muxStateEarly_1_3 ? auto_in_3_a_bits_size[2:0] : 3'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  assign auto_out_1_a_bits_source = (muxStateEarly_1_0 ? portsAOI_filtered_1_bits_source : 6'h0) | (muxStateEarly_1_1 ? portsAOI_filtered_1_1_bits_source : 6'h0) | (muxStateEarly_1_2 ? portsAOI_filtered_2_1_bits_source : 6'h0) | (muxStateEarly_1_3 ? portsAOI_filtered_3_1_bits_source : 6'h0);	// @[Arbiter.scala:118:30, Mux.scala:27:73, Xbar.scala:240:{29,55}, :265:23]
  assign auto_out_1_a_bits_address = (muxStateEarly_1_0 ? auto_in_0_a_bits_address : 32'h0) | (muxStateEarly_1_1 ? auto_in_1_a_bits_address : 32'h0) | (muxStateEarly_1_2 ? auto_in_2_a_bits_address : 32'h0) | (muxStateEarly_1_3 ? auto_in_3_a_bits_address : 32'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  assign auto_out_1_a_bits_mask = (muxStateEarly_1_0 ? auto_in_0_a_bits_mask : 16'h0) | (muxStateEarly_1_1 ? auto_in_1_a_bits_mask : 16'h0) | (muxStateEarly_1_2 ? auto_in_2_a_bits_mask : 16'h0) | (muxStateEarly_1_3 ? auto_in_3_a_bits_mask : 16'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  assign auto_out_1_a_bits_data = (muxStateEarly_1_0 ? auto_in_0_a_bits_data : 128'h0) | (muxStateEarly_1_1 ? auto_in_1_a_bits_data : 128'h0) | (muxStateEarly_1_2 ? auto_in_2_a_bits_data : 128'h0) | (muxStateEarly_1_3 ? auto_in_3_a_bits_data : 128'h0);	// @[Arbiter.scala:118:30, Mux.scala:27:73]
  assign auto_out_1_a_bits_corrupt = muxStateEarly_1_0 & auto_in_0_a_bits_corrupt | muxStateEarly_1_1 & auto_in_1_a_bits_corrupt | muxStateEarly_1_2 & auto_in_2_a_bits_corrupt | muxStateEarly_1_3 & auto_in_3_a_bits_corrupt;	// @[Arbiter.scala:118:30, Mux.scala:27:73]
  assign auto_out_1_b_ready = auto_in_3_b_ready;
  assign auto_out_1_c_valid = auto_in_3_c_valid;
  assign auto_out_1_c_bits_opcode = auto_in_3_c_bits_opcode;
  assign auto_out_1_c_bits_param = auto_in_3_c_bits_param;
  assign auto_out_1_c_bits_size = auto_in_3_c_bits_size[2:0];	// @[BundleMap.scala:247:19]
  assign auto_out_1_c_bits_source = {4'h8, auto_in_3_c_bits_source};	// @[Parameters.scala:54:32, Xbar.scala:262:55]
  assign auto_out_1_c_bits_address = auto_in_3_c_bits_address;
  assign auto_out_1_c_bits_data = auto_in_3_c_bits_data;
  assign auto_out_1_c_bits_corrupt = auto_in_3_c_bits_corrupt;
  assign auto_out_1_d_ready = requestDOI_1_0 & auto_in_0_d_ready & allowed_2_1 | requestDOI_1_1 & auto_in_1_d_ready & allowed_3_1 | requestDOI_1_2 & auto_in_2_d_ready & allowed_4_1 | requestDOI_1_3 & auto_in_3_d_ready & allowed_5_1;	// @[Arbiter.scala:122:24, Mux.scala:27:73, Parameters.scala:54:32]
  assign auto_out_1_e_valid = auto_in_3_e_valid;
  assign auto_out_1_e_bits_sink = auto_in_3_e_bits_sink;
  assign auto_out_0_a_valid = x1_out_1_valid;	// @[Arbiter.scala:126:29]
  assign auto_out_0_a_bits_opcode = (muxStateEarly_0 ? auto_in_0_a_bits_opcode : 3'h0) | (muxStateEarly_1 ? auto_in_1_a_bits_opcode : 3'h0) | (muxStateEarly_2 ? auto_in_2_a_bits_opcode : 3'h0) | (muxStateEarly_3 ? auto_in_3_a_bits_opcode : 3'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  assign auto_out_0_a_bits_param = (muxStateEarly_0 ? auto_in_0_a_bits_param : 3'h0) | (muxStateEarly_1 ? auto_in_1_a_bits_param : 3'h0) | (muxStateEarly_2 ? auto_in_2_a_bits_param : 3'h0) | (muxStateEarly_3 ? auto_in_3_a_bits_param : 3'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  assign auto_out_0_a_bits_size = (muxStateEarly_0 ? auto_in_0_a_bits_size : 4'h0) | (muxStateEarly_1 ? auto_in_1_a_bits_size : 4'h0) | (muxStateEarly_2 ? auto_in_2_a_bits_size : 4'h0) | (muxStateEarly_3 ? auto_in_3_a_bits_size : 4'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  assign auto_out_0_a_bits_source = (muxStateEarly_0 ? portsAOI_filtered_1_bits_source : 6'h0) | (muxStateEarly_1 ? portsAOI_filtered_1_1_bits_source : 6'h0) | (muxStateEarly_2 ? portsAOI_filtered_2_1_bits_source : 6'h0) | (muxStateEarly_3 ? portsAOI_filtered_3_1_bits_source : 6'h0);	// @[Arbiter.scala:118:30, Mux.scala:27:73, Xbar.scala:240:{29,55}, :265:23]
  assign auto_out_0_a_bits_address = (muxStateEarly_0 ? auto_in_0_a_bits_address[30:0] : 31'h0) | (muxStateEarly_1 ? auto_in_1_a_bits_address[30:0] : 31'h0) | (muxStateEarly_2 ? auto_in_2_a_bits_address[30:0] : 31'h0) | (muxStateEarly_3 ? auto_in_3_a_bits_address[30:0] : 31'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  assign auto_out_0_a_bits_mask = (muxStateEarly_0 ? auto_in_0_a_bits_mask : 16'h0) | (muxStateEarly_1 ? auto_in_1_a_bits_mask : 16'h0) | (muxStateEarly_2 ? auto_in_2_a_bits_mask : 16'h0) | (muxStateEarly_3 ? auto_in_3_a_bits_mask : 16'h0);	// @[Arbiter.scala:118:30, Bundles.scala:259:74, Mux.scala:27:73]
  assign auto_out_0_a_bits_data = (muxStateEarly_0 ? auto_in_0_a_bits_data : 128'h0) | (muxStateEarly_1 ? auto_in_1_a_bits_data : 128'h0) | (muxStateEarly_2 ? auto_in_2_a_bits_data : 128'h0) | (muxStateEarly_3 ? auto_in_3_a_bits_data : 128'h0);	// @[Arbiter.scala:118:30, Mux.scala:27:73]
  assign auto_out_0_a_bits_corrupt = muxStateEarly_0 & auto_in_0_a_bits_corrupt | muxStateEarly_1 & auto_in_1_a_bits_corrupt | muxStateEarly_2 & auto_in_2_a_bits_corrupt | muxStateEarly_3 & auto_in_3_a_bits_corrupt;	// @[Arbiter.scala:118:30, Mux.scala:27:73]
  assign auto_out_0_d_ready = requestDOI_0_0 & auto_in_0_d_ready & allowed_2_0 | requestDOI_0_1 & auto_in_1_d_ready & allowed_3_0 | requestDOI_0_2 & auto_in_2_d_ready & allowed_4_0 | requestDOI_0_3 & auto_in_3_d_ready & allowed_5_0;	// @[Arbiter.scala:122:24, Mux.scala:27:73, Parameters.scala:54:32]
endmodule

